### ISSUE TITLE
pandas.from_csv() is deprecated.

### ISSUE THREAD

**Issue by LongTianPy** [widdowquinn/pyani#101]
#### Summary:
The current version of pandas no longer has the function from_csv(), but anib.py is still using it.

#### Description:
anib.py:423: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### pyani Version:
Current
#### Python Version:
python 3

**Comment by widdowquinn** [comment]
Hi Long,

Thanks for reporting this. I’ve seen the same message, too. So far it’s just a warning and should not affect output.

This is corrected in the current extend_tests branch, 0.2.7.dev, with commit 73f3f08f45e650fc8aaf829c4e82512444bea9f0 and should make it into the master shortly.

Cheers,

L.

**Comment by LongTianPy** [comment]
Thanks. I have scrolled the pandas version to 0.20.0 and temporarily solved this problem.
