### ISSUE TITLE
ANIb concordance tests take too long for Travis-CI

### ISSUE THREAD

**Issue by widdowquinn** [widdowquinn/pyani#103]
Concordance tests fail because no response is returned for 10min. This happens because the BLAST ANI JSpecies concordance tests take too long.

The long-term proposed solution is to reduce the scale of the test inputs. In the meantime, the concordance tests will be skipped.

**Comment by baileythegreen** [comment]
These are running both locally and in CircleCI. Does that mean this can be closed?

**Comment by baileythegreen** [comment]
@widdowquinn Can this be closed?

**Comment by widdowquinn** [comment]
> These are running both locally and in CircleCI. Does that mean this can be closed?

Yes - I think you're right, and they can.
