### ISSUE TITLE
ANI plot or graphic Heat Map question

### ISSUE THREAD

**Issue by Ivalize** [widdowquinn/pyani#109]
#### Summary:
ANI or graphic Heat Map question

#### Description:
I hope my query is not so obvious, but I'm just getting to know the heatmap in python.

1. Any way (or where exactly) to change the scale or bar (z) in the identity percentages?
2. And some way to change the color scale like ?
All this in script: average_nucleotide_identity.py

Thanks.

**Comment by widdowquinn** [comment]
Hi Nico,

Thanks for your patience, and your interest in `pyani`!

1. There's not an easy way to do this at the command-line, but you can achieve what you want in more than one way.

- modify the contents of `pyani_config.py`; specifically there's a dictionary `cdict_spbnd_BuRd` that controls the colours used for species boundaries. You'd either have to modify this before installing the package from source, or modify directly in the installed package. That would change the boundaries for each time you run `average_nucleotide_identity.py`. I'd quite like to make this controllable by a configuration file in the next version.

- using the `pyani` package in your own `Python` code, you could use `pyani_graphics.get_seaborn_clustermap()` (or another relevant function), passing a custom colourmap with your desired settings as the `cmap` argument.

- you could import the relevant `.tab` output into `R`, `Python`, or another package/tool/language, and use any heatmap graphic renderer.

These last two options aren't very convenient either, I know.

2. The colour scale is defined as a series of breakpoints in RGB format, as a `LinearSegmentedColorMap` from `matplotlib` [docs](https://matplotlib.org/api/_as_gen/matplotlib.colors.LinearSegmentedColormap.html):

```python
cdict_spbnd_BuRd = {'red': ((0.0, 0.0, 0.7),
                            (0.7, 0.7, 0.0),
                            (0.9, 0.0, 0.0),
                            (0.95, 1.0, 1.0),
                            (1.0, 1.0, 1.0)),
                    'green': ((0.0, 0.0, 0.7),
                              (0.7, 0.7, 0.0),
                              (0.9, 0.0, 0.0),
                              (0.95, 1.0, 1.0),
                              (1.0, 0.0, 0.0)),
                    'blue': ((0.0, 0.0, 0.7),
                             (0.7, 0.7, 1.0),
                             (0.95, 1.0, 1.0),
                             (1.0, 0.0, 0.0))}
CMAP_SPBND_BURD = LinearSegmentedColormap("spbnd_BuRd",
                                          cdict_spbnd_BuRd)
```

You could modify this scale to have any number of breakpoints or hues, as you require.

**Comment by Ivalize** [comment]
Thanks, now I understand a little better the dynamics and especially the part of using `pyani_config.py`, to modify the gradient and the colors. Maybe the option to use `.tab` does not sound so bad (for now).

Thanks for everything.
