### ISSUE TITLE
Empty output folder

### ISSUE THREAD

**Issue by anaya1** [widdowquinn/pyani#111]
#### Summary:
Please provide a short summary (a couple of sentences).
Running average_nucleotide_identity.py creates empty output folder.

#### Description:
Describe the issue as clearly as possible.
I ran average_nucleotide_identity.py with input folder containing 134 genomes as .fa files. The output folder nucmer_output was created but there is nothing in it. The job was submitted with the following script to the University cluster:
#$ -cwd
#$ -V
#$ -l h_rt=05:00:00
#$ -l h_vmem=4G

average_nucleotide_identity.py -v -i metabat_bins90/ -o metabat_bins90/pyani/ --write_excel
The job error file contains information about it:

INFO: pyani version: 0.2.7
INFO: Namespace(blastall_exe='blastall', blastn_exe='blastn', classes=None, filter_exe='delta-filter', force=False, formatdb_exe='formatdb', fragsize=1020, gformat='pdf,png,eps', gmethod='mpl', graphics=False, indirname='metabat_bins90/', jobprefix='ANI', labels=None, logfile=None, makeblastdb_exe='makeblastdb', maxmatch=False, method='ANIm', noclobber=False, nocompress=False, nucmer_exe='nucmer', outdirname='metabat_bins90/pyani/', rerender=False, scheduler='multiprocessing', seed=None, sgeargs=None, sgegroupsize=10000, skip_blastn=False, skip_nucmer=False, subsample=None, verbose=True, workers=None, write_excel=True)
INFO: command-line: /opt/yarcc/biology/pyani/0.2.7/1/python-3.6.4/bin/average_nucleotide_identity.py -v -i metabat_bins90/ -o metabat_bins90/pyani/ --write_excel
INFO: Input directory: metabat_bins90/
INFO: Creating directory metabat_bins90/pyani/
INFO: Output directory: metabat_bins90/pyani/
INFO: Using ANI method: ANIm
INFO: Using scheduler method: multiprocessing
INFO: Identifying FASTA files in metabat_bins90/
INFO: Input files:
	metabat_bins90/BMS.11.fa
	metabat_bins90/BMS.126.fa
	metabat_bins90/BMS.127.fa
	metabat_bins90/BMS.142.fa
	metabat_bins90/BMS.145.fa
.
.
.
INFO: nucmer --mum -p metabat_bins90/pyani/nucmer_output/BMS.58_vs_SO.123 metabat_bins90/BMS.58.fa metabat_bins90/SO.123.fa; delta-filter -1 metabat_bins90/pyani/nucmer_output/BMS.58_vs_SO.123.delta > metabat_bins90/pyani/nucmer_output/BMS.58_vs_SO.123.filter
INFO: nucmer --mum -p metabat_bins90/pyani/nucmer_output/BMS.250_vs_SO.214 metabat_bins90/BMS.250.fa metabat_bins90/SO.214.fa; delta-filter -1 metabat_bins90/pyani/nucmer_output/BMS.250_vs_SO.214.delta > metabat_bins90/pyani/nucmer_output/BMS.250_vs_SO.214.filter
INFO: nucmer --mum -p metabat_bins90/pyani/nucmer_output/SO.242_vs_SO.24 metabat_bins90/SO.242.fa metabat_bins90/SO.24.fa; delta-filter -1 metabat_bins90/pyani/nucmer_output/SO.242_vs_SO.24.delta > metabat_bins90/pyani/nucmer_output/SO.242_vs_SO.24.filter
INFO: nucmer --mum -p metabat_bins90/pyani/nucmer_output/NAB.214_vs_NAB.40 metabat_bins90/NAB.214.fa metabat_bins90/NAB.40.fa; delta-filter -1 metabat_bins90/pyani/nucmer_output/NAB.214_vs_NAB.40.delta > metabat_bins90/pyani/nucmer_output/NAB.214_vs_NAB.40.filter
INFO: nucmer --mum -p metabat_bins90/pyani/nucmer_output/BMS.63_vs_SO.54 metabat_bins90/BMS.63.fa metabat_bins90/SO.54.fa; delta-filter -1 metabat_bins90/pyani/nucmer_output/BMS.63_vs_SO.54.delta > metabat_bins90/pyani/nucmer_output/BMS.63_vs_SO.54.filter
INFO: nucmer --mum -p metabat_bins90/pyani/nucmer_output/BMS.179_vs_NAB.238 metabat_bins90/BMS.179.fa metabat_bins90/NAB.238.fa; delta-filter -1 metabat_bins90/pyani/nucmer_output/BMS.179_vs_NAB.238.delta > metabat_bins90/pyani/nucmer_output/BMS.179_vs_NAB.238.filter
INFO: nucmer --mum -p metabat_bins90/pyani/nucmer_output/NAB.175_vs_SO.164 metabat_bins90/NAB.175.fa metabat_bins90/SO.164.fa; delta-filter -1 metabat_bins90/pyani/nucmer_output/NAB.175_vs_SO.164.delta > metabat_bins90/pyani/nucmer_output/NAB.175_vs_SO.164.filter

Your job 1812898 has finished

From this file it looks like sth was created but doesn't appear in the output file. 

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.
Nothing was created, no output files but output folder was created.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.
I was expecting to have an Excel file with a matrix of ANI values for each bin.

**Comment by widdowquinn** [comment]
Hi Anna,

I suspect that one or more of your `NUCmer` jobs may have failed. If that was the case, the SGE job you submitted would have completed as you describe, but you would see no output.

To test this, please could you rerun a smaller job (maybe 3-4 genomes) using the `-l <logfilename>` option, and inspect and include the log file that is produced. This would give more details about the cause of failure and enable further diagnosis.

L.
