### ISSUE TITLE
average_nucleotide_identity.py no working. Panda dependency

### ISSUE THREAD

**Issue by germant13** [widdowquinn/pyani#117]
#### Summary:
Panda problem

#### Description:
I tried to run the script average_nucleotide_identity.py but No worked. I have installed all dependencies but when I run the script,average_nucleotide_identity.py does not find the pandas dependency.

#### Reproducible Steps:
.

#### Current Output:
traglia@impam2:~/ruhlandii/achromo_GB/pyani/bin$ average_nucleotide_identity.py 
Traceback (most recent call last):
  File "./average_nucleotide_identity.py", line 159, in <module>
    import pandas as pd
ImportError: No module named 'pandas'

**Comment by widdowquinn** [comment]
Hi germant,

This sounds like an installation problem. 

The first thing to mention is that `pyani` is a Python3 package, and will not run on Python2. You report that you are using Python2, so you should upgrade and/or use one of the alternative installation options (e.g. Docker, as described on the home page: [https://widdowquinn.github.io/pyani/](https://widdowquinn.github.io/pyani/)).

If `pyani` is not seeing the `pandas` module, then the `pandas` module is not installed under the same Python environment as `pyani`. This is a problem that can crop up when more than one version of Python is installed on the system - it is possible to lose track of what is installed where. The `conda`, `pip` and `Docker` installation options are provided to minimise this issue, and I would suggest that you use one of these installation approaches.

If you need to use the development branch, then I would suggest creating a `conda` environment [link](https://conda.io/docs/user-guide/tasks/manage-environments.html) and installing the prerequisites before using `python setup.py install` to install the latest `pyani` branch under that same environment.

Cheers,

L.
