### ISSUE TITLE
error in running --rerender option

### ISSUE THREAD

**Issue by ghost** [widdowquinn/pyani#125]
Error in `--rerender`

When I use the command:
```bash
screen average_nucleotide_identity.py -v -i all_fna_files_renamed/ -o pyani_out -s 500 -l pyani.log -g --gformat png,pdf,eps,svg --write_excel -m ANIb --rerender
```

The following error appears:
```python
Traceback (most recent call last):
  File "/home/naiane/anaconda3/bin/average_nucleotide_identity.py", line 814, in <module>
    draw(methods[args.method][1], gfmt)
  File "/home/naiane/anaconda3/bin/average_nucleotide_identity.py", line 637, in draw
    params = pyani_graphics.Params(params_mpl(df)[filestem],
  File "/home/naiane/anaconda3/lib/python3.6/site-packages/pyani/pyani_config.py", line 109, in params_mpl
    return {'ANIb_alignment_lengths': ('afmhot', df.values.min(),
  File "/home/naiane/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
TypeError: '<=' not supported between instances of 'float' and 'str'
```

Do you know how to solve it?

Thanks.

**Comment by naianegri** [comment]
[all_fna_files_renames.zip](https://github.com/widdowquinn/pyani/files/2765352/all_fna_files_renames.zip)
It's 680 genomes files .fna like these attached

**Comment by naianegri** [comment]
.tab file example 
[ANIb_percentage_identity.zip](https://github.com/widdowquinn/pyani/files/2765453/ANIb_percentage_identity.zip)

**Comment by Anenovaes** [comment]
I was running pyani normally, but now I'm having this same problem. Do you already found the solution?

**Comment by Anenovaes** [comment]
Hi, 
I was running the pyANI (ANIb) normally, but now I'm having the same problem. How can I solve this?

**Comment by baileythegreen** [comment]
@widdowquinn The zip file provided above only contains an `ANIb_percentage_identity.tab` file, which is insufficient to run the command provided.

The error suggests the source is a formatting issue in `ANIb_alignment_lengths.tab`, where something is being incorrectly treated as a string, however, I am currently unable to reproduce the issue.

@ghost, @Anenovaes I realise you may have moved on, and apologise for the delay. If either of you still have a fileset which produces this issue, could you please provide the full set of output files? Thanks.
