### ISSUE TITLE
Having problem with average_nucleotide_identity.py

### ISSUE THREAD

**Issue by sushanta26** [widdowquinn/pyani#131]
Hi
I was trying to get ANI value for 33 bacterial species ,but when I run the "average_nucleotide_identity.py" command system shows following error message.Please correct me If I am making any mistake in command.
pyani was installed using pip3 

Command is 
average_nucleotide_identity.py -i /home/sdas/Desktop/test_ani_data/ --blastn_exe /home/sdas/Desktop/ANI/ncbi-blast-2.6.0+/bin/  -l /home/sdas/Desktop/logfile -o /home/sdas/Desktop/output/all -m ANIb

Error:
WARNING: At least one BLAST run failed. ANIb may fail.

**Comment by widdowquinn** [comment]
Hi @sushanta26 - thank you for your using `pyani`.

This error tends to come up when using `pyani` to calculate ANI for bacterial isolates with essentially zero sequence identity. This can show up as an absence of BLAST output, which `pyani` then interprets as a failed BLAST job (BLAST jobs can fail for numerous reasons).

I would suggest inspecting the logfile to see which BLAST jobs were run, and comparing the expected output filenames to those that were written (and seeing if any have zero content). Then try running the BLAST commands corresponding to the empty files/missing output.

If the BLAST run completes successfully, but there is no output, then it might be best to exclude at least one of the genomes you were using from the analysis.

**Comment by widdowquinn** [comment]
I'm assuming for now that the issue was with the input dataset. Please reopen if the advice above did not solve your issue.
