### ISSUE TITLE
File or directory contains white spaces

### ISSUE THREAD

**Issue by davidvilanova** [widdowquinn/pyani#133]
#### Summary:
Hi,
While trying to use average_nucleotide_identity with the test data it fails with the following error (see attached screenshot)

#### Reproducible Steps:

<img width="914" alt="Screenshot 2019-05-20 at 14 43 39" src="https://user-images.githubusercontent.com/11404840/58022405-ad12ea00-7b0d-11e9-91a6-7bd7f21fa710.png">

**Comment by davidvilanova** [comment]
was a problem of folder permissions

**Comment by widdowquinn** [comment]
Related to #11

**Comment by damedin** [comment]
> was a problem of folder permissions

Same error her, but changed the files to a folder in home can solve the error and allow to run average_nucleotide_identity without problems
