### ISSUE TITLE
How to generate an ANI scale in the tree like this

### ISSUE THREAD

**Issue by liangjinsong** [widdowquinn/pyani#138]
#### Summary:
Please provide a short summary (a couple of sentences).
Want to generate an ANI tree with an line ANI scale,but can't find how to generate it with pyani.

#### Description:
Describe the issue as clearly as possible.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.
![tree with ANI scale](https://user-images.githubusercontent.com/43932337/59970586-bb38a800-959c-11e9-87f2-d48503b342ea.png)

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

**Comment by widdowquinn** [comment]
Hi Liang,

I'm afraid `pyani` does not generate this kind of output.

However it may be that there are tools which can use the distance matrices that `pyani` generates to produce such a figure. If I was going to produce a tree like that I'd probably consider using `ete3` in Python.

Cheers,

L.

**Comment by liangjinsong** [comment]
Hi, thank you for you timely reply and helpful suggestion~


LIANG Jinsong
Environmental Biotechnology Lab
Department of Civil Engineering
The University of Hong Kong
Pokfulam Road, Hong Kong
On 6/23/2019 18:44，Leighton Pritchard<notifications@github.com> wrote：

Hi Liang,

I'm afraid pyani does not generate this kind of output.

However it may be that there are tools which can use the distance matrices that pyani generates to produce such a figure. If I was going to produce a tree like that I'd probably consider using ete3 in Python.

Cheers,

L.
