### ISSUE TITLE
restructure output directory 

### ISSUE THREAD

**Issue by alienzj** [widdowquinn/pyani#141]
#### Summary:
adjust pyani output directory

#### Description:
If we have 1000 genomes, we will get 1000000 files on the *nucmer_output* directory.
If we set sub directory, will good.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

#### Current Output:
nucmer_output/a_vs_a
nucmer_output/a_vs_b
nucmer_output/a_vs_c
nucmer_output/b_vs_a
nucmer_output/b_vs_b
nucmer_output/b_vs_c
nucmer_output/c_vs_a
nucmer_output/c_vs_b
nucmer_output/c_vs_c

#### Expected Output:
nucmer_output/a/a_vs_a
nucmer_output/a/a_vs_b
nucmer_output/a/a_vs_c
nucmer_output/b/b_vs_a
nucmer_output/b/b_vs_b
nucmer_output/b/b_vs_c
nucmer_output/c/c_vs_a
nucmer_output/c/c_vs_b
nucmer_output/c/c_vs_c

#### pyani Version:
average_nucleotide_identity.py: pyani 0.2.9

#### Python Version:
Python 3.6.7

#### Operating System:
Linux cngb-oxcompute-9.cngb.sz.hpc 2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018 x86_64 GNU/Linux

**Comment by alienzj** [comment]
https://github.com/alienzj/pyani/commit/047191a86a8efbd2434de370c9ec5da3295cc8fa

Hello, @widdowquinn 
I am try to do this, and  have done for ANIm method.
when I finish it, I will make a PR.

Best regards.
Jack

**Comment by widdowquinn** [comment]
Hi Jack,

This isn't a change that I'm going to make, I'm afraid.

The roadmap for `pyani` is to place all comparison output into a local SQLite database - this has already been implemented in the `development` branch. Eventually, the `nucmer` output will not be written into the output folder, but instead to a temporary location, and it will be deleted once data is transferred to the database (unless explicitly requested to be retained by the user).

If you need this format of output for some downstream work your desired directory organisation could be achieved with, for example, a for loop like the following in `bash`:

```bash
for fname in nucmer_output
do
    qname=nucmer_output/${fname%%"_"*}
    mkdir -p ${qname}
    mv ${fname} ${qname}
done
```

**Comment by alienzj** [comment]
@widdowquinn You are right.
Thanks very much~
