### ISSUE TITLE
ValueError: The condensed distance matrix must contain only finite values. (A Solution Found)

### ISSUE THREAD

**Issue by andrew-cardno** [widdowquinn/pyani#144]
#### Summary (Including potential solution)
Using the seaborn clustermap this error was shown. I am posting this as it took me some time to track this down and it may help others.
ValueError: The condensed distance matrix must contain only finite values.

#### Description:
I tried various different datasets, in short while not understanding why it seems like the method is quite fragile to the values of the data. I removed unique values using this code.
 df = df.loc[:, df.nunique() > 1] #Make sure columns have non unique values
        

I resolved the issue by changing the metric="euclidean", from metric = 'correlation'. 
gmt = sns.clustermap(df, metric="correlation", method="single", cmap="Blues", standard_scale=1) #, row_colors=row_colors)

gmt = sns.clustermap(df, metric="**euclidean**", method="single", cmap="Blues", standard_scale=1) #, row_colors=row_colors)

#### Python Version:
Python 3.7.4 

#### Operating System:
Windows 10

**Comment by widdowquinn** [comment]
I'm assuming for now that the error was in the dataset. Please reopen the issue if you'd like to share some example data that throws the error, so I can chase any bugs down.

**Comment by andrew-cardno** [comment]
Sorry yes I will try and make a dataset that causes the error, I have been
very busy
