### ISSUE TITLE
Finish putting documentation on ReadTheDocs

### ISSUE THREAD

**Issue by widdowquinn** [widdowquinn/pyani#149]
#### Summary:

Place user documentation for `pyani` on ReadTheDocs

**Comment by baileythegreen** [comment]
Missing files:
- [ ] - `subcmd_anib.rst`
- [ ] - `subcmd_classify.rst`
- [ ] - `subcmd_plot.rst`
- [ ] - `subcmd_report.rst`

**Comment by baileythegreen** [comment]
I've made a branch for this, `issue_149`. If there are other things to add, commit them there, or edit the checklist above so I know to add them.

**Comment by baileythegreen** [comment]
All of those documents have now been added.
