### ISSUE TITLE
Rerunning analyses

### ISSUE THREAD

**Issue by ninjatacoshell** [widdowquinn/pyani#15]
I used pyani to compare 23 genomes that are all around 5 Mb in size. Running on two of my laptop's processors, pyani took ~6 minutes to run the tetra analysis, ~1 hour to run the ANIg, and ~4 hours each to run the ANIb and ANIblastall analyses. Not long after that another genome became available. I was hoping that I could use pyani to compare the 24th genome to the other 23 without having to rerun all the previous comparisons. It looks to me like that's what the -f and --noclobber arguments are supposed to accomplish. But when I ran

`./average_nucleotide_identity.py -i tests/my_genomes/ -o tests/my_genomes_ANIm_output -m ANIm -g -v -f --noclobber`

pyani still re-calculated every possible pairwise ANI (which took a little over an hour).

It would be a real time-saver (especially for larger data sets) if pyani can check whether any pairwise comparisons have already been done and then skip them.

**Comment by peterjc** [comment]
I was just looking at this too, as you note combining ``--force`` or ``-f`` and ``--noclobber`` will run without deleting/recreating the directory, but does not seem to take advantage of any pre-existing comparison files. Rather it forces regeneration of all the ``*.delta`` files (or equivalent) and the final output.

In principle slight changes to the input folder like adding/removing a few FASTA files would mean only a few (or even no) new pairwise comparisons are needed.

Caveat: Enabling this would require ensuring that interrupting a run could never result in a partial/incomplete ``*.delta`` file (or equivalent)?

One way to implement this would be to store the ``*.delta`` files (or equivalent) separately from the final graphics (folder set by ``-o`` or ``--outdir``), perhaps as ``--paircache`` folder (which could default to the output directory as now)?

**Comment by peterjc** [comment]
Another simple use case, I just ran a large job without ``-g`` or ``--graphics`` and would like to be able to re-run the job to get the images *without* having to recalculate all the pairwise comparisons.

**Comment by widdowquinn** [comment]
For the last case, you can use `--skip_nucmer` or `--skip_blastn, as appropriate:

```
  --skip_nucmer         Skip NUCmer runs, for testing (e.g. if output already
                        present)
  --skip_blastn         Skip BLASTN runs, for testing (e.g. if output already
                        present)
```

Using the relevant argument above, and specifying `-g`/`--graphics` will give you the result you require without recalculation.

As you note in the earlier message, there are potentially difficulties caused by assuming that an appropriate comparison output filename implies a complete comparison result. I'm still thinking about how to approach that, and a separate output folder (or, rather, a subdirectory within the output folder…) may be a good idea for that, combined with a flag to indicate that all (or specified) prior analyses finished without error.

**Comment by peterjc** [comment]
Putting the ``*.delta`` files under a sub-folder would also help when there are tens of thousands of them - it makes the handful of summary files easier to see ;)

**Comment by peterjc** [comment]
Thanks for the tip about skipping the computations to generate the graphics. It wasn't obvious exactly how to do it, so I've prepared an example here.

First run forgetting to request graphics:

```
$ ~/repositories/pyani/average_nucleotide_identity.py -i . -o demo
$ ls -1 demo/ANIm_*
demo/ANIm_alignment_coverage.tab
demo/ANIm_alignment_lengths.tab
demo/ANIm_percentage_identity.tab
demo/ANIm_similarity_errors.tab
```

Then re-run to get the graphics adding ``--graphics --skip_nucmer --force --noclobber``,

```
$ ~/repositories/pyani/average_nucleotide_identity.py -i . -o demo --graphics --skip_nucmer --force --noclobber
WARNING: NOCLOBBER: not actually deleting directory
WARNING: Skipping NUCmer run (as instructed)!
$ ls -1 demo/ANIm_*
demo/ANIm_alignment_coverage.eps
demo/ANIm_alignment_coverage.pdf
demo/ANIm_alignment_coverage.png
demo/ANIm_alignment_coverage.tab
demo/ANIm_alignment_lengths.eps
demo/ANIm_alignment_lengths.pdf
demo/ANIm_alignment_lengths.png
demo/ANIm_alignment_lengths.tab
demo/ANIm_percentage_identity.eps
demo/ANIm_percentage_identity.pdf
demo/ANIm_percentage_identity.png
demo/ANIm_percentage_identity.tab
demo/ANIm_similarity_errors.eps
demo/ANIm_similarity_errors.pdf
demo/ANIm_similarity_errors.png
demo/ANIm_similarity_errors.tab
```

Cheers!

**Comment by widdowquinn** [comment]
Yes - a (sub)directory full of `*.delta` files is a real pain. Compressing the subdirectory after generation is also a nice thing to do for yourself and the filesystem, so that's something I'd also like to incorporate.

**Comment by widdowquinn** [comment]
Moving in the direction of allowing incremental additions of files for comparison, I've changed the way comparison output is written.

Now, BLAST and nucmer write their output to a subdirectory of the output file (the name used depends on the comparison method). By default, this data is processed, then compressed to `.tar.gz` and the original directory deleted. This is intended to keep all the comparison files neat/away from the tabular/graphical output, and nicely compressed to save space.

This behaviour can be turned off using the `--nocompress` option at the command line. Using this option will leave the output files in the output folder subdirectory.

**Comment by widdowquinn** [comment]
Moving in the direction of allowing incremental additions of files for comparison, I've changed the way comparison output is written ([this commit](https://github.com/widdowquinn/pyani/commit/450ba4f089350c7d9a2c230bb50e5a8afa9b9067)).

Now, BLAST and nucmer write their output to a subdirectory of the output file (the name used depends on the comparison method). By default, this data is processed, then compressed to `.tar.gz` and the original directory deleted. This is intended to keep all the comparison files neat/away from the tabular/graphical output, and nicely compressed to save space.

This behaviour can be turned off using the `--nocompress` option at the command line. Using this option will leave the output files in the output folder subdirectory.

**Comment by widdowquinn** [comment]
Not at the stage for incremental re-runs yet (though I think I have decided how to implement it: by a check for the output file in anim/anib module job creation) - but the `--rerender` option in `v0.2.0.dev` that came in with commit 1229d86 will allow generation of new graphical output from the `.tab` output of previous analyses.

**Comment by widdowquinn** [comment]
The current `classify` branch now allows for re-run behaviour, though the interface is quite different. As a pseudo-code example:

```
pyani index GENOME_DIR
pyani anim GENOME_DIR OUTDIR
# the pyani anim command will indicate a run number (RUN_NUMBER)
pyani report RUN_NUMBER OUTDIR
pyani plot RUN_NUMBER OUTDIR
```

Now, after adding new genomes to the original `GENOME_DIR`, running the commands above will only calculate pairwise comparisons for those comparisons involving the new genomes, and give a new `RUN_NUMBER`. Using this `RUN_NUMBER` will combine the previous comparison results with the new comparison results.
