### ISSUE TITLE
pyani.py command not found

### ISSUE THREAD

**Issue by algaraber** [widdowquinn/pyani#165]
#### Summary:
Briefly, I am unable to run pyani, despite seemingly installing it successfully with conda.

#### Description:
Describe the issue as clearly as possible.
I am installing pyani as per the instructions in the README (with conda) and attempting to run exactly the same commands that appear there, just as a test. Trying to run pyani.py returns "command not found"; other commands from the package seem to run fine.

I have also tried using pip3 to install it, and manually by downloading the repository and executing the setup.py file, but in both situations the result seems to be the same.

#### Reproducible Steps:
These are the commands as recorded by my bash history:

conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda install pyani
average_nucleotide_identity.py -h
pyani.py download C_blochmannia --email my.email@my.domain -t 203804 -v -l C_blochmannia_dl.log
tree C_blochmannia

#### Current Output:
Output of
average_nucleotide_identity.py -h 
is as expected,; the whole list of arguments

Output of 
pyani.py download C_blochmannia --email my.email@my.domain -t 203804 -v -l C_blochmannia_dl.log
is
-bash: pyani.py command not found

Output of
tree
is
-bash: tree: command not found

#### Expected Output:
Simply not expecting "command not found"

#### pyani Version:
v0.2.9
#### Python Version:
python3.7.3
#### Operating System:
GNU/Linux

**Comment by widdowquinn** [comment]
Hi @algaraber 

Many apologies - you're the first person to fall prey to me moving over to the new API of `pyani` - the documentation is out of sync.

The documentation on the main page, and at `ReadTheDocs` is for the forthcoming version 0.3. The *old* documentation can now be found with v0.2.7.9 at [this link](https://github.com/widdowquinn/pyani/tree/b2e978df9e38e125c209036faeda789a09ee4003).

I'll need to put a note in and update the v0.3 documentation to point users to the old docs, but until then that link should get you going. Please continue the conversation here if it doesn't help.

Apologies again,

L.

**Comment by algaraber** [comment]
Thank you for such a fast answer! Now I know why it was not working; everything seems to be running now.

**Comment by widdowquinn** [comment]
No problem. I feel embarrassed that I didn't put a link in to the old docs. Thank you so much for pointing out my oversight - it's very much appreciated!

I hope the new link and readme is enough to catch everyone's attention. Do feel free to raise any other issues you find!

Cheers,

L.

**Comment by Gahyeon-K** [comment]
I did 'conda -install  -c bioconda pyani'. But, there were 'pyani: command not found'.
But average_nucleotide_identity.py command works. 
How can I update to recent version??
Thank you.

**Comment by widdowquinn** [comment]
Hi @Gahyeon-K 

Thank you for your interest in `pyani`. Please note that this issue has been closed, and it is usual to open a new issue, rather than tag questions onto the end of someone else's issue.

However, there is a straightforward answer to your question. If you want to install `pyani` v0.3+ you should follow the instructions in the `README.md` file on the front page of the repository. This link should take you straight there: [https://github.com/widdowquinn/pyani#installation](https://github.com/widdowquinn/pyani#installation)

L.
