### ISSUE TITLE
Con't get pyani commond

### ISSUE THREAD

**Issue by James-Hao** [widdowquinn/pyani#169]
Hi widdowquinn ,

    I had installed pyani by bioconda commond: "conda install -c bioconda pyani", however, i can't start my job with pyani commond. When i try to use "$pyani " commond, there shows a eeror which is "bash: pyani: commond not found". Could you help me with it? Thanks very much!

**Comment by widdowquinn** [comment]
Hi James,

This is the same issue as #165 - the development/RTD documentation is not the same as the `conda` release. I've made major changes to the command-line API. The current `conda` version has documentation at: [https://github.com/widdowquinn/pyani/blob/master/README_v_0_2_x.md](https://github.com/widdowquinn/pyani/blob/master/README_v_0_2_x.md)

Briefly, you should be using the `average_nucleotide_identity.py` command, instead.

I hope this helps, but please reopen if you still can't get `pyani` working.

L.
