### ISSUE TITLE
Pyani installation using pip

### ISSUE THREAD

**Issue by stefanielager** [widdowquinn/pyani#170]
#### Summary:
I installed pyani using command:   pip3 install pyani --user
and the installation seems to work, I have average_nucleotide_identity.py in my path but not the command pyani? Where is that installed?

#### Description:
Describe the issue as clearly as possible.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

**Comment by widdowquinn** [comment]
Hi Stephanie,

Thank you for your interest in `pyani`. I'm afraid that `pip` installs v0.2.9, and the `pyani` commands are only available in v0.3.x (currently a source install only - some work to do before it's ready for `pip`).

The documentation for v0.2.x can be found at [this link](https://github.com/widdowquinn/pyani/blob/master/README_v_0_2_x.md). The results are the same whichever version you use.

There is a note linking to the older documentation in the [`README.md` file](https://github.com/widdowquinn/pyani/blob/master/README.md), and there are two closed issues describing this problem, too (#165 and #169), so I guess I need to make this more obvious on the page.

If you've any other questions, please do raise them here!

L.
