### ISSUE TITLE
Issue with installation - pyani-master

### ISSUE THREAD

**Issue by bharat1912** [widdowquinn/pyani#171]
#### Summary:
Please provide a short summary (a couple of sentences).

Downloaded the latest zip file, unzipped it 
1. I have a conda env (basic3) in which python3.6 is installed. 
   $conda activate basic3 
      (basic3) bharat@bharat-Precision-Tower-7810:
   $python3 setup.py install

2. The basic python is python 3.7
   $conda deactivate  
      (base) bharat@bharat-Precision-Tower-7810:
  $python3 setup.py install

Checked commands and no errors found
In both cases basic3 (conda activate) and basic, the installation seems to be okay
   $pyani -h
produced
usage: pyani.py [-h]
                {download,index,createdb,anim,anib,aniblastall,report,plot,classify}
optional arguments:
  -h, --help            show this help message and exit
subcommands:
  valid subcommands
  {download,index,createdb,anim,anib,aniblastall,report,plot,classify}
                        additional help

$pyani anib
produced 
usage: pyani.py anib [-h] [-l LOGFILE] [-v] [--disable_tqdm]
                     [--scheduler {multiprocessing,SGE}] [--workers WORKERS]
                     [--SGEgroupsize SGEGROUPSIZE] [--SGEargs SGEARGS]
                     [--jobprefix JOBPREFIX] [--name NAME] [--classes CLASSES]
                     [--labels LABELS] [--recovery] [--dbpath DBPATH]
                     [--blastn_exe BLASTN_EXE] [--format_exe FORMAT_EXE]
                     [--fragsize FRAGSIZE]
                     indir outdir
pyani.py anib: error: the following arguments are required: indir, outdir

$pyani download C_blochmannia --bharatgu19@gmail.com -t 20380 
 downloaded 6 (not 8) files from ncbi

$pyani index fna_new (this is my data folder name)
produced 
 classes.txt and labels.txt

#### Description:
Errors were raised when the test C.blochmannia dataset or my dataset were run (conda activated environment and deactivated environment (below)
Conda activated:
(basic3) bharat@bharat-Precision-Tower-7810:~/Desktop$ pyani anib fna_new/ fna_new/Anoxibacillus_pyani_anib --classes fna_new/classes.txt --labels fna_new/labels.txt 
fna_new/Anoxibacillus_pyani_anib/fragments/A_ayderensis_ABO4_NZ_JXTG01000001-fragments.fasta 53233
fna_new/Anoxibacillus_pyani_anib/fragments/Anoxybacillus_sp._BCO1_GUGAB_NZ_JRLC01000001-fragments.fasta 53164
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_subsp_yunnanesis_E13_NZ_KN127218-fragments.fasta 53078
fna_new/Anoxibacillus_pyani_anib/fragments/A_gonensis_NZ_G2_CP012152-fragments.fasta 52230
fna_new/Anoxibacillus_pyani_anib/fragments/A_amylolyticus_MR3C_NZ_SMDM01000001-fragments.fasta 67037
fna_new/Anoxibacillus_pyani_anib/fragments/A_rupensis_QUTGAB-fragments.fasta 70907
fna_new/Anoxibacillus_pyani_anib/fragments/A_geothermalis_GSSed3_NZ_JYCG01000001-fragments.fasta 132967
fna_new/Anoxibacillus_pyani_anib/fragments/A_suryakundensis_DSM27374_NZ_CYGZ01000001-fragments.fasta 48690
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_AK-1_NZ_APCD01000001-fragments.fasta 49441
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_subsp.flavithermus_DSM2641_NZ_CP020815-fragments.fasta 52383
fna_new/Anoxibacillus_pyani_anib/fragments/Anoxybacillus_sp._P3H1B_GUGAB_NZ_LPUG01000001-fragments.fasta 66256
fna_new/Anoxibacillus_pyani_anib/fragments/Anoxybacillus_sp._UARK-01_NZ_NASY01000001-fragments.fasta 69019
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_52-1A_NZ_CP021838-fragments.fasta 52742
fna_new/Anoxibacillus_pyani_anib/fragments/Anoxybacillus_sp._KU2-611_NZ_JPZN01000001-fragments.fasta 56399
fna_new/Anoxibacillus_pyani_anib/fragments/Anoxybacillus_sp.b2m1_NZ_CP015435-fragments.fasta 71154
fna_new/Anoxibacillus_pyani_anib/fragments/A_kamchatkensis_PD13_NZ_NQLB01000001-fragments.fasta 54619
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_25_NZ_JPZO01000001-fragments.fasta 54698
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_B4168_NZ_LQYU01000001-fragments.fasta 69716
fna_new/Anoxibacillus_pyani_anib/fragments/A_mongoliensis_MB4_NZ_MRZM01000010.-fragments.fasta 53079
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_QUTGAB-fragments.fasta 52419
fna_new/Anoxibacillus_pyani_anib/fragments/A_ayderensis_MT-Cab_NZ_NDEZ01000001-fragments.fasta 48822
fna_new/Anoxibacillus_pyani_anib/fragments/A_gonensis_G2_NZ_JRZG01000001-fragments.fasta 51849
fna_new/Anoxibacillus_pyani_anib/fragments/A_vitaminiphilus_CGMCC1.8979T_NZ_QLMH01000001-fragments.fasta 66780
fna_new/Anoxibacillus_pyani_anib/fragments/A_rupensis_DSM17127_Ga0373222-fragments.fasta 69283
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_NBRC109594_NZ_BARH01000090-fragments.fasta 52554
fna_new/Anoxibacillus_pyani_anib/fragments/A_gonensis_DT3-1_NZ_ANMT01000001-fragments.fasta 48812
fna_new/Anoxibacillus_pyani_anib/fragments/A_thermarum_AF-04_NZ_JXTH01000001-fragments.fasta 52182
fna_new/Anoxibacillus_pyani_anib/fragments/A_pushchinoensis_K1_NZ_FOJQ01000117-fragments.fasta 49885
fna_new/Anoxibacillus_pyani_anib/fragments/A_kamchatkensis_G10_NZ_CP025535.1-fragments.fasta 55194
fna_new/Anoxibacillus_pyani_anib/fragments/A_tepidamans_PS2_NZ_JHVN01000001-fragments.fasta 63033
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_WK1_NC_011567-fragments.fasta 53028
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_AF14_NZ_LUFB01000038-fragments.fasta 49205
fna_new/Anoxibacillus_pyani_anib/fragments/Anoxybacillus_sp._103_NZ_MQAD01000001-fragments.fasta 51132
fna_new/Anoxibacillus_pyani_anib/fragments/A_amylolyticus_DSM15939_NZ_CP015438-fragments.fasta 58877
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_FHS-PPAM212_NZ_SBBW01000001-fragments.fasta 51695
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_KU2-6_11_NZ_PEDM01000010-fragments.fasta 49963
fna_new/Anoxibacillus_pyani_anib/fragments/A_ayderensis_NZ_ANOC01000001-fragments.fasta 50951
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_TNO-09.006_NZ_KB205935-fragments.fasta 49532
fna_new/Anoxibacillus_pyani_anib/fragments/A_suryakundensis_DSM27374_NZ_LIOK01000001-fragments.fasta 48690
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_AF16_NZ_LUCQ01000090-fragments.fasta 50943
fna_new/Anoxibacillus_pyani_anib/fragments/Anoxybacillus_sp_b7m1_NZ_CP015436-fragments.fasta 72084
fna_new/Anoxibacillus_pyani_anib/fragments/A_geothermalis_QUTGAB-fragments.fasta 77886
Traceback (most recent call last):
  File "/home/bharat/opt/anaconda3/envs/basic3/bin/pyani", line 11, in <module>
    load_entry_point('pyani==0.3.0a0', 'console_scripts', 'pyani')()
  File "/home/bharat/opt/anaconda3/envs/basic3/lib/python3.6/site-packages/pyani-0.3.0a0-py3.6.egg/pyani/scripts/pyani_script.py", line 74, in run_main
  File "/home/bharat/opt/anaconda3/envs/basic3/lib/python3.6/site-packages/pyani-0.3.0a0-py3.6.egg/pyani/scripts/subcommands/subcmd_anib.py", line 170, in subcmd_anib
NotImplementedError

Conda deactivated:
(base) bharat@bharat-Precision-Tower-7810:~/Desktop$ pyani anib fna_new/ fna_new/Anoxibacillus_pyani_anib --classes fna_new/classes.txt --labels fna_new/labels.txt
fna_new/Anoxibacillus_pyani_anib/fragments/A_ayderensis_ABO4_NZ_JXTG01000001-fragments.fasta 53233
fna_new/Anoxibacillus_pyani_anib/fragments/Anoxybacillus_sp._BCO1_GUGAB_NZ_JRLC01000001-fragments.fasta 53164
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_subsp_yunnanesis_E13_NZ_KN127218-fragments.fasta 53078
fna_new/Anoxibacillus_pyani_anib/fragments/A_gonensis_NZ_G2_CP012152-fragments.fasta 52230
fna_new/Anoxibacillus_pyani_anib/fragments/A_amylolyticus_MR3C_NZ_SMDM01000001-fragments.fasta 67037
fna_new/Anoxibacillus_pyani_anib/fragments/A_rupensis_QUTGAB-fragments.fasta 70907
fna_new/Anoxibacillus_pyani_anib/fragments/A_geothermalis_GSSed3_NZ_JYCG01000001-fragments.fasta 132967
fna_new/Anoxibacillus_pyani_anib/fragments/A_suryakundensis_DSM27374_NZ_CYGZ01000001-fragments.fasta 48690
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_AK-1_NZ_APCD01000001-fragments.fasta 49441
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_subsp.flavithermus_DSM2641_NZ_CP020815-fragments.fasta 52383
fna_new/Anoxibacillus_pyani_anib/fragments/Anoxybacillus_sp._P3H1B_GUGAB_NZ_LPUG01000001-fragments.fasta 66256
fna_new/Anoxibacillus_pyani_anib/fragments/Anoxybacillus_sp._UARK-01_NZ_NASY01000001-fragments.fasta 69019
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_52-1A_NZ_CP021838-fragments.fasta 52742
fna_new/Anoxibacillus_pyani_anib/fragments/Anoxybacillus_sp._KU2-611_NZ_JPZN01000001-fragments.fasta 56399
fna_new/Anoxibacillus_pyani_anib/fragments/Anoxybacillus_sp.b2m1_NZ_CP015435-fragments.fasta 71154
fna_new/Anoxibacillus_pyani_anib/fragments/A_kamchatkensis_PD13_NZ_NQLB01000001-fragments.fasta 54619
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_25_NZ_JPZO01000001-fragments.fasta 54698
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_B4168_NZ_LQYU01000001-fragments.fasta 69716
fna_new/Anoxibacillus_pyani_anib/fragments/A_mongoliensis_MB4_NZ_MRZM01000010.-fragments.fasta 53079
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_QUTGAB-fragments.fasta 52419
fna_new/Anoxibacillus_pyani_anib/fragments/A_ayderensis_MT-Cab_NZ_NDEZ01000001-fragments.fasta 48822
fna_new/Anoxibacillus_pyani_anib/fragments/A_gonensis_G2_NZ_JRZG01000001-fragments.fasta 51849
fna_new/Anoxibacillus_pyani_anib/fragments/A_vitaminiphilus_CGMCC1.8979T_NZ_QLMH01000001-fragments.fasta 66780
fna_new/Anoxibacillus_pyani_anib/fragments/A_rupensis_DSM17127_Ga0373222-fragments.fasta 69283
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_NBRC109594_NZ_BARH01000090-fragments.fasta 52554
fna_new/Anoxibacillus_pyani_anib/fragments/A_gonensis_DT3-1_NZ_ANMT01000001-fragments.fasta 48812
fna_new/Anoxibacillus_pyani_anib/fragments/A_thermarum_AF-04_NZ_JXTH01000001-fragments.fasta 52182
fna_new/Anoxibacillus_pyani_anib/fragments/A_pushchinoensis_K1_NZ_FOJQ01000117-fragments.fasta 49885
fna_new/Anoxibacillus_pyani_anib/fragments/A_kamchatkensis_G10_NZ_CP025535.1-fragments.fasta 55194
fna_new/Anoxibacillus_pyani_anib/fragments/A_tepidamans_PS2_NZ_JHVN01000001-fragments.fasta 63033
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_WK1_NC_011567-fragments.fasta 53028
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_AF14_NZ_LUFB01000038-fragments.fasta 49205
fna_new/Anoxibacillus_pyani_anib/fragments/Anoxybacillus_sp._103_NZ_MQAD01000001-fragments.fasta 51132
fna_new/Anoxibacillus_pyani_anib/fragments/A_amylolyticus_DSM15939_NZ_CP015438-fragments.fasta 58877
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_FHS-PPAM212_NZ_SBBW01000001-fragments.fasta 51695
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_KU2-6_11_NZ_PEDM01000010-fragments.fasta 49963
fna_new/Anoxibacillus_pyani_anib/fragments/A_ayderensis_NZ_ANOC01000001-fragments.fasta 50951
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_TNO-09.006_NZ_KB205935-fragments.fasta 49532
fna_new/Anoxibacillus_pyani_anib/fragments/A_suryakundensis_DSM27374_NZ_LIOK01000001-fragments.fasta 48690
fna_new/Anoxibacillus_pyani_anib/fragments/A_flavithermus_AF16_NZ_LUCQ01000090-fragments.fasta 50943
fna_new/Anoxibacillus_pyani_anib/fragments/Anoxybacillus_sp_b7m1_NZ_CP015436-fragments.fasta 72084
fna_new/Anoxibacillus_pyani_anib/fragments/A_geothermalis_QUTGAB-fragments.fasta 77886
Traceback (most recent call last):
  File "/home/bharat/opt/anaconda3/bin/pyani", line 11, in <module>
    load_entry_point('pyani==0.3.0a0', 'console_scripts', 'pyani')()
  File "/home/bharat/opt/anaconda3/lib/python3.7/site-packages/pyani-0.3.0a0-py3.7.egg/pyani/scripts/pyani_script.py", line 74, in run_main
  File "/home/bharat/opt/anaconda3/lib/python3.7/site-packages/pyani-0.3.0a0-py3.7.egg/pyani/scripts/subcommands/subcmd_anib.py", line 170, in subcmd_anib
NotImplementedError

#### pyani Version:
version 3 (pyani-master)

#### Python Version: 
Conda activated:
(basic3) bharat@bharat-Precision-Tower-7810:~/Desktop$ python -V
      Python 3.6.7

Conda deactivated:
(base) bharat@bharat-Precision-Tower-7810:~/Desktop$ python -V
Python 3.7.3

#### Operating System: 
   Ubuntu 18.04

**Comment by widdowquinn** [comment]
Hi Bharat,

Thank you for your interest in `pyani`. The relevant part of the error message is this:

```python
File "/home/bharat/opt/anaconda3/lib/python3.7/site-packages/pyani-0.3.0a0-py3.7.egg/pyani/scripts/subcommands/subcmd_anib.py", line 170, in subcmd_anib
NotImplementedError
```

You are trying to use the ANIb functionality of `pyani` v0.3.x, which is the development version of the software, and not yet implemented in full (as indicated by the `NotImplementedError`). If you need to use the ANIb method then you should install an earlier version, e.g. from source by downloading the v0.2.9 release

- [v0.2.9](https://github.com/widdowquinn/pyani/releases/tag/v0.2.9)

or using `conda`:

```bash
conda install pyani
```

The documentation for this version is linked from the development version's `README.md`, and can be found [here](https://github.com/widdowquinn/pyani/blob/master/README_v_0_2_x.md)

The ANIm method is implemented fully in v0.3.x, and is preferable to ANIb in a number of features, if you would like to try that approach.

I hope this helps you run the analysis you need.

L.
