### ISSUE TITLE
pyani doesn´t works after installation

### ISSUE THREAD

**Issue by zakisaati** [widdowquinn/pyani#176]
#### Summary:
The installation works well, but pyani command is not found

#### Description:
I installed pyani trying with conda install, with pip3 and from source, following steps detailed in the docs. It seems that everything is ok, but when I try to do "pyani --version" the system says "command not found".

When I print average_nucleotide_identity.py --version I obtain:
average_nucleotide_identity.py: pyani 0.2.9

So I guess that the problem is the installation of the pyani program itself.

I have python3.7 (and python 2.7) installed in my ubuntu system.

How could I solve it?

**Comment by widdowquinn** [comment]
Hi @zakisaati 

Thank you for your interest in `pyani`. You're not the first to find this issue. The problem is that the instructions are slightly out of step with the version. Please see these other issue pages for help with resolving this:

- #169 
- #165 

I apologise for the inconvenience.

L.

**Comment by zakisaati** [comment]
Thank you very much, the method works fine :)

**Comment by widdowquinn** [comment]
Brilliant! Please raise another issue if you have any issues or comments.
