### ISSUE TITLE
Add clearer instructions to `README.md` about the scheduler options

### ISSUE THREAD

**Issue by juliambrosman** [widdowquinn/pyani#179]
#### Summary:
Quick questions. 

There aren't instructions in the README that I can find about how to take advantage of a scheduler.  Is that documentation available?  

Also, you say it will work with an OGE/SGE type scheduler.  What about PBS?

Thanks much!  We find this software very useful, and I'm excited to try out version 0.3+ (we'd been using pyani 0.2.7).

#### pyani Version:
0.3+

#### installed dependencies
not an issue

#### Python Version:
3.6

#### Operating System:
CentOS Linux 7

**Comment by widdowquinn** [comment]
Hi Julia,

Thank you very much for your kind comments about `pyani`!

The bad news first - I've not made `pyani` work on PBS, yet. It should be possible, but I don't have a local PBS example to test against (or any experience with PBS… truth be told). If you're interested in adding support for PBS I do take pull requests :D

The good news is that using SGE is done by adding the argument `--scheduler SGE`. So long as you are able to run jobs with `qsub`, that is enough to distribute the pairwise comparisons. It will batch the comparisons to avoid clogging up your scheduler queue, in chunks of 10000 - but each one will run as a single-core slot. You can add other arguments to SGE with `--SGEargs "<your arguments here>"`, but I haven't needed to.

I absolutely need to update the `README.md` to make this clear. Thank you for raising it!

I'm also looking forward to getting v0.3 out! It's been hanging on too long, as it is…

Cheers,

L.
