### ISSUE TITLE
Document version of Python required

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#18]
It wasn't clear from the README which versions of Python are supported (probably just Python 2.7 right now, see also #12 for Python 3 support).

Note following the dependency chain from `requirements.txt`, recent versions of rpy2 and pandas do not support Python 2.6 any more.

**Comment by widdowquinn** [comment]
Thanks, @peterjc - I'll take a look at that.

I was hoping to sort existing dependency issues out when moving to v0.2. As you note elsewhere (#19) this is something that could be kept an eye on better with something like TravisCI.
