### ISSUE TITLE
Add FastANI to this wrapper

### ISSUE THREAD

**Issue by jianshu93** [widdowquinn/pyani#183]
FastANI is fast and easy to use. here is the link: https://github.com/ParBLiSS/FastANI 
Can we work together to make it happen? Just one more wrapper and some modification to the major part, add an -- fastANI method.

#### Description:
Describe the issue in detail, as clearly as possible.

#### Reproducible Steps:
Please report a series of steps (e.g. command-line instructions) that would enable someone else to reproduce the issue. If possible, please attach a small set of input files/data that would be sufficient to allow someone else to reproduce the issue. 

If it's not possible to reproduce the issue, please include a description of how you discovered the issue.

#### Current Output:
The output you get from `pyani` or at the terminal, with this issue. It is very useful to know the current "wrong" behavior on your system.

#### Expected Output:
Describe what you expect the output to be. It is also very useful to know the expected "correct" behavior on your systems.

#### installed dependencies
If you are running a version of `pyani` v0.3 or later, then please run the command `pyani listdeps` at the command line, and enter the output below.

**Comment by widdowquinn** [comment]
It's a very good idea (and was in my to-do list, just not an issue, yet). Do you feel up to writing the appropriate module for `pyani`?

**Comment by jianshu93** [comment]
I am working on it. I will let you know when I have something new. Also it good to add usearch based alignment method. In that case, all the implementation of ANI will be included.

**Comment by jianshu93** [comment]
I am working on it. I will let you know when I have something new. Also it good to add usearch based alignment method. In that case, all the implementation of ANI will be included.

**Comment by jianshu93** [comment]
I am working on it. I will let you know when I have something new. Also it good to add usearch based alignment method. In that case, all the implementation of ANI will be included.

**Comment by jianshu93** [comment]
I am working on it. I will let you know when I have something new. Also it good to add usearch based alignment method. In that case, all the implementation of ANI will be included.

**Comment by widdowquinn** [comment]
Thank you for making a start on this. Please do try to keep to the same style choices (`black`, `flake8` etc. - the `pre-commit` config may be helpful to you, there), and make suggestions as PRs.

In the issues, here, I also have gANI #155 and wANI #156 and Mash #137. The usearch implementation should be a separate issue to this one, I think, for ease of management.

**Comment by baileythegreen** [comment]
PR #299, implementing this, has just been merged.
