### ISSUE TITLE
TravisCI integration

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#19]
It would be great to have pyani automatically tested via TravisCI. However, the dependencies are a bit of a pain.

First effort: https://github.com/peterjc/pyani/tree/travis

Today's efforts: https://github.com/peterjc/pyani/tree/travis2

Installing numpy and scipy etc is fairly quick if you can use pre-compiled wheels (coming to PyPI soon).

The current version of rpy2 available on PyPI is rpy2 v2.7.8 https://pypi.python.org/pypi/rpy2/2.7.8 and this no longer supports Python 2.6, or R v2.x. Furthermore, the current white-listed ``r-base`` ``r-base-dev`` apt-get packages from Ubuntu Precise give R 2.14.1 which is too old for the latest rpy. So we can't easily test the R based graphics...

**Comment by widdowquinn** [comment]
I've no direct experience with TravisCI yet but, as we've discussed off-GitHub, it's something I'd like to see/do.

**Comment by widdowquinn** [comment]
`pyani` now has full Travis-CI, and `codecov.io` integration.
