### ISSUE TITLE
Command not found error for pyani

### ISSUE THREAD

**Issue by ramibaghdan** [widdowquinn/pyani#192]
#### Summary:
I installed using pip3, conda, and from the source; however, I seem to get a "command not found" error. 

#### Description:

Getting command not found error for pyani after various installations.

#### Reproducible Steps:

I tried installing using pip3 and conda following the tutorial.
Lastly, I tried installing from the source:

wget https://github.com/widdowquinn/pyani/archive/v0.2.9.tar.gz
tar -zxf v0.2.9.tar.gz
cd pyani-0.2.9
python setup.py install

pyani --version

#### Current Output:

-bash: pyani: command not found

#### Expected Output:
pyani version

#### installed dependencies

N/A.

**Comment by widdowquinn** [comment]
Hi Rami,

Thank you for your interest in `pyani`.

The issue you have is that you have installed `pyani` v0.2.9, but are using the command-line for v0.3+ This is noted in the project `README.md` (which refers to the development version), and the documentation you require for v0.2 is here: [https://github.com/widdowquinn/pyani/blob/master/README_v_0_2_x.md](https://github.com/widdowquinn/pyani/blob/master/README_v_0_2_x.md). I apologise for the inconvenience.

(duplicates #176 #171 #169 #165)

If you have any other questions, please do raise a new issue.

L.
