### ISSUE TITLE
Set number of threads

### ISSUE THREAD

**Issue by ddomman** [widdowquinn/pyani#20]
First off, the pyani package looks great. I was wondering if it was possible to limit the number of threads used in the multiprocessing mode to a set number? I'm trying to run the script on a non-SGE server and I'm concerned that the script as is, will try and use all available threads on the node... which is not so good.

Thanks!

**Comment by widdowquinn** [comment]
Not yet, @ddomman - but it should be a fairly straightforward change. I'll make it in the `v0.2` branch, when I do.

FWIW, I think using all the threads available to you is generally a good thing ;)

**Comment by widdowquinn** [comment]
That should be the appropriate option enabled in the `v0.2` branch with commit . If you'd like to pull it and check it does the job, I'll close this thread.

To use the new option, add the `--workers n` argument to the command-line. This will default to the maximum available number of threads if not specified, and cannot use more than the available number of cores if the specified value is too high. For example:

```
./average_nucleotide_identity.py -v -f \
  -i tests/test_ani_data/ \
  -o tests/test_ANIm_output/ \
  -g --gformat png,pdf,eps \
  --classes tests/test_ani_data/classes.tab --labels tests/test_ani_data/labels.tab \
  --workers 1
```

should use a single core.

**Comment by sarah872** [comment]
Although I specify `--workers`, mummer/nucmer is still running on the maximum number of cores. How can I limit the number of cores for nucmer?

**Comment by widdowquinn** [comment]
Thanks for the report, Sarah. I can't seem to reproduce that behaviour, though. For me, using:

- `pyani` v0.2.7 (the current `master` branch)
- OSX 10.14 (Mojave)
- `mummer` v3.1
- `python` 3.6.6

and executing the command described above:

```bash
./average_nucleotide_identity.py -v -f \
  -i tests/test_ani_data/ \
  -o tests/test_ANIm_output/ \
  -g --gformat png,pdf,eps \
  --classes tests/test_ani_data/classes.tab --labels tests/test_ani_data/labels.tab \
  --workers 1
```

I see only one `mummer` process.

With the alternative command:

```bash
./average_nucleotide_identity.py -v -f \
  -i tests/test_ani_data/ \
  -o tests/test_ANIm_output/ \
  -g --gformat png,pdf,eps \
  --classes tests/test_ani_data/classes.tab --labels tests/test_ani_data/labels.tab \
  --workers 4
```

I see four `mummer` processes.

For me, `--workers` seems to work as expected.

Can you please describe your system and how you're running the command?
