### ISSUE TITLE
Output directory output would overwrite existing files (exiting)

### ISSUE THREAD

**Issue by Biofarmer** [widdowquinn/pyani#205]
#### Summary:
Hello, there is "ERROR: Output directory output would overwrite existing files (exiting)" when I run pyani in MacOS terminal.

#### Description:
Describe the issue in detail, as clearly as possible.
I installed the pyani with MacOS terminal, and run average_nucleotide_identity.py -i input -o output with the four test sequencing (NC_002696.fna, NC_010338.fna, NC_011916.fna, NC_014100.fna). Then, an error was got: "ERROR: Output directory output would overwrite existing files (exiting)".

Can anyone know where there is the problem? Thanks in advance.

**Comment by widdowquinn** [comment]
Hi @Biofarmer,

Thanks for using `pyani`!

The issue you have is that the output directory exists already. To preserve your existing results, `pyani` will by default *not* overwrite these. To do so you would need to use the `-f` option:

```bash
average_nucleotide_identity.py -i input -o output -f
```

Alternatively, you could specify a different output directory name, or manually delete the existing output. Either of these should also fix your issue.

L.

**Comment by Biofarmer** [comment]
> Hi @Biofarmer,
> 
> Thanks for using `pyani`!
> 
> The issue you have is that the output directory exists already. To preserve your existing results, `pyani` will by default _not_ overwrite these. To do so you would need to use the `-f` option:
> 
> ```shell
> average_nucleotide_identity.py -i input -o output -f
> ```
> 
> Alternatively, you could specify a different output directory name, or manually delete the existing output. Either of these should also fix your issue.
> 
> L.

Hi @widdowquinn,
It works, thank you very much. In addition, may I ask further whether there is any requirement for the input fasta? I mean if the input fasta files are contigs/scaffolds, is it fine? And is it necessary to order the contigs based a reference genome before calculating the ANI?

Thank you very much.

**Comment by widdowquinn** [comment]
Hi @Biofarmer 

You might find the original reference for ANIm helpful for more detail/deeper understanding:

- Richter M, Rossello-Mora R (2009) Shifting the genomic gold standard for the prokaryotic species definition. Proc Natl Acad Sci USA 106: 19126-19131. doi:10.1073/pnas.0906412106

Briefly, though:

 - ANIm will identify maximally-matching homologous regions between pairs of genomes. For the most part, it does not matter practically whether a genome is presented as contigs or scaffolds, but there are limits (e.g. if your contigs are all 20bp, it's not going to do all that well). So long as approximately all of your genome is sequenced, you should be fine.
- There is no need to order contigs - each matched *region* should only match to its "best" counterpart in the other genome of any pairwise comparison.

**Comment by Biofarmer** [comment]
> Hi @Biofarmer
> 
> You might find the original reference for ANIm helpful for more detail/deeper understanding:
> 
> * Richter M, Rossello-Mora R (2009) Shifting the genomic gold standard for the prokaryotic species definition. Proc Natl Acad Sci USA 106: 19126-19131. doi:10.1073/pnas.0906412106
> 
> Briefly, though:
> 
> * ANIm will identify maximally-matching homologous regions between pairs of genomes. For the most part, it does not matter practically whether a genome is presented as contigs or scaffolds, but there are limits (e.g. if your contigs are all 20bp, it's not going to do all that well). So long as approximately all of your genome is sequenced, you should be fine.
> * There is no need to order contigs - each matched _region_ should only match to its "best" counterpart in the other genome of any pairwise comparison.

Hi @widdowquinn,
Thank you very much for answering. It is very helpful.
