### ISSUE TITLE
TypeError: subcmd_index() missing 1 required positional argument: 'logger'

### ISSUE THREAD

**Issue by sammywinchester19** [widdowquinn/pyani#206]
#### Summary:
I am trying to index my local fasta format genomes and it gives the error that 1 positional argument 'logger' is missing

#### Description:
I am doing pyANI analysis, I downloaded the script from github and its dependencies. While indexing my fasta files for subsequent scirpts. It give a postional error in the script.
**Script**
pyani index indir ../../genomes/

#### Reproducible Steps:
Downloading any fasta format file from NCBI
Establishing pyANI (pyani version: 0.3.0-alpha) and its dependencies
running the script as mentioned with the indir argument.
pyani index indir ../../genomes/

#### Current Output:
TypeError: subcmd_index() missing 1 required positional argument: 'logger'

#### Expected Output:
md5 index files from fasta

#### pyani Version:
(pyani version: 0.3.0-alpha)

#### installed dependencies
bioconda 

#### Python Version:
Python 3.8

**Comment by widdowquinn** [comment]
Thanks for the report, @sammywinchester19 - I'll look into it.

If you need results quickly, please do try v0.2.x - the results should be the same. v0.3.x is the development version and isn't fully working, yet.

Cheers,

L.

**Comment by widdowquinn** [comment]
@add-contributors please add @sammywinchester19 for bug

**Comment by widdowquinn** [comment]
@all-contributors please add @sammywinchester19 for bug
