### ISSUE TITLE
Help with script: --write_excel error

### ISSUE THREAD

**Issue by Michelle-Pena** [widdowquinn/pyani#208]
Hi, it is my first time running pyani on SSH. 

I'm using the pyani/0.2.7b version, and every time I try to run it I get the error: 
average_nucleotide_identity.py: error: unrecognized arguments: --write_excel 

I tried to change the script in many ways and I ended up getting files like .delta and .filter

Here is my script:

#!/bin/bash
source /opt/asn/etc/asn-bash-profiles-special/modules.sh
module load pyani/0.2.7b
average_nucleotide_identity.py -o aniresult -i /scratch/aubmmp/JGI_NPX/FastANI -g --gformat pdf -m ANIm --write_excel

Thank you!

**Comment by widdowquinn** [comment]
Hi Michelle,

Thank you for using `pyani`! I've had a look at v0.2.7 (63bc40ec) and the `--write_excel` argument should be accepted. I don't understand why this would not be the case on the server you're using. It may be (judging from the v0.2.7b number you cite) that your sysadmin found that `--write_excel` was not working (the `openpyxl` package is required for this, and is not in the `requirements.txt` file - it would also need to be installed for v0.2.10).

A workaround might be to not specify `--write_excel` but to take the `.tab` file output and import it into Excel instead. The output is a tab-separated plain text file, and should be straightforward to import and use.

It's worth noting that v0.2.7 is three years old now, and the current version on `conda`/'PyPI` is v0.2.10. It looks like you're working with a managed system like [Lmod](https://lmod.readthedocs.io/en/latest/), so perhaps you could install the later version within that system, or ask your sysadmin to do so if you don't have the relevant permissions.

Cheers,

L.
