### ISSUE TITLE
Preserve extension when naming MD5 hash file?

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#211]
Quoting the README, you expect files named like this:

```
$ tree C_blochmannia
C_blochmannia
├── GCF_000011745.1_ASM1174v1_genomic.fna
├── GCF_000011745.1_ASM1174v1_genomic.fna.gz
├── GCF_000011745.1_ASM1174v1_genomic.md5
...
```

i.e. When building the expected MD5 hash filename, you drop and replace the extension with ``.md5``.

https://github.com/widdowquinn/pyani/blob/340ed5f4df066e2cbcd5233df8a86d6678f6ff21/pyani/pyani_files.py#L97

However, adding ``.md5`` is a more common convention - recognising for example that ``GCF_000011745.1_ASM1174v1_genomic.fna.md5`` and ``GCF_000011745.1_ASM1174v1_genomic.fna.gz.md5`` would be different. This also allows for other extensions and checksums, like ``GCF_000011745.1_ASM1174v1_genomic.bam.md5``

Usecase: I'm trying to run pyani on a folder of locally assembled FASTA files (not using pyani to download reference assemblies from NCBI), and having discovered the MD5 files were essential ran: ``for f in *.fasta; do md5sum $f > $f.md5; done`` - workaround ``$ for f in *.fasta; do md5sum $f > ${f%.*}.md5; done``

Suggestion One: Replace ``stem.md5`` with ``stem.ext.md5`` as hashfile for FASTA file ``stem.ext``

Suggestion Two: Allow ``stem.ext.md5`` as well as ``stem.md5`` given FASTA file ``stem.ext``

**Comment by widdowquinn** [comment]
Thanks for the suggestion.

In a case where the files `GCF_000011745.1_ASM1174v1_genomic.fna` and `GCF_000011745.1_ASM1174v1_genomic.fna.gz` are provided, there should not be a clash of `.md5` suffixed filenames:

```python
>>> p = Path("myfile.fna")
>>> g = Path("myfile.fna.gz")
>>> p.with_suffix(".md5")
PosixPath('myfile.md5')
>>> g.with_suffix(".md5")
PosixPath('myfile.fna.md5')
```

But I take the point about convention.

I note that `myfile.fna` and `myfile.bam` would give rise to the same `.md5` files but, as we only take in FASTA files, I'm not so worried about that. However, the `.md5` files resulting from `myfile.fna` and `myfile.fasta` would conflict, which isn't great. I was implicitly expecting that filestems would be unique to an assembly, and that could have been clearer in the documentation. In any case, adding `.md5` to the full filename - as in suggestion one - is better, as it is explicit and clear.

**Comment by peterjc** [comment]
Good point on ``myfile.fna`` vs ``myfile.fasta`` potentially both being present.

If you are willing to change this, I agree adding ``.md5`` to the filename is the simplest solution.

**Comment by widdowquinn** [comment]
Specifically for the second point (using `md5sum` in a one-liner), there is a `pyani` subcommand that will generate the appropriate `.md5` hashes, and also (where possible) the label and class files: https://pyani.readthedocs.io/en/latest/subcmd_index.html - this might be more convenient.
