### ISSUE TITLE
pyani for nucleotides

### ISSUE THREAD

**Issue by Sanrrone** [widdowquinn/pyani#216]
Dears, 
is there a way to use this software with nucleotide fastas? or might you thinking on add it as new feature?.

Cheers

**Comment by widdowquinn** [comment]
Hi @Sanrrone 

Thank you for your interest in `pyani`. I'm happy to say that `pyani` works with nucleotide sequences in FASTA format. Please take a look at the walkthrough ([v0.2.x README.md](https://github.com/widdowquinn/pyani/blob/master/README_v_0_2_x.md))  for a guided example in how to use this kind of data.

Cheers,

L.
