### ISSUE TITLE
plot failing with FloatingPointError: NaN dissimilarity value.

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#219]
#### Summary:

Added some reference genomes to a bunch of SPADES assemblies, redid the database and anim in recovery mode. Then attempted plots.

Getting ``FloatingPointError: NaN dissimilarity value.`` during plotting. Could be missing data from an imperfect recovery? Could it be one of my genomes is an big outlier?

#### Current Output:

```sh
$ pyani plot --formats png,pdf --method seaborn spades_contigs_anim 2
```
```python
Traceback (most recent call last):
  File "/mnt/xxx/conda/bin/pyani", line 8, in <module>
    sys.exit(run_main())
  File "/mnt/xxx/conda/lib/python3.7/site-packages/pyani/scripts/pyani_script.py", line 105, in run_main
    returnval = args.func(args)
  File "/mnt/xxx/conda/lib/python3.7/site-packages/pyani/scripts/subcommands/subcmd_plot.py", line 93, in subcmd_plot
    write_run_heatmaps(run_id, session, outfmts, args)
  File "/mnt/xxx/conda/lib/python3.7/site-packages/pyani/scripts/subcommands/subcmd_plot.py", line 130, in write_run_heatmaps
    run_id, matdata, result_label_dict, result_class_dict, outfmts, args
  File "/mnt/xxx/conda/lib/python3.7/site-packages/pyani/scripts/subcommands/subcmd_plot.py", line 189, in write_heatmap
    params=params,
  File "/mnt/xxx/conda/lib/python3.7/site-packages/pyani/pyani_graphics/sns/__init__.py", line 161, in heatmap
    fig = get_clustermap(dfr, params, title=title)
  File "/mnt/xxx/conda/lib/python3.7/site-packages/pyani/pyani_graphics/sns/__init__.py", line 118, in get_clustermap
    annot=annot,
  File "/mnt/xxx/conda/lib/python3.7/site-packages/seaborn/matrix.py", line 1391, in clustermap
    tree_kws=tree_kws, **kwargs)
  File "/mnt/xxx/conda/lib/python3.7/site-packages/seaborn/matrix.py", line 1208, in plot
    tree_kws=tree_kws)
  File "/mnt/xxx/conda/lib/python3.7/site-packages/seaborn/matrix.py", line 1054, in plot_dendrograms
    tree_kws=tree_kws
  File "/mnt/xxx/conda/lib/python3.7/site-packages/seaborn/matrix.py", line 772, in dendrogram
    label=label, rotate=rotate)
  File "/mnt/xxx/conda/lib/python3.7/site-packages/seaborn/matrix.py", line 584, in __init__
    self.linkage = self.calculated_linkage
  File "/mnt/xxx/conda/lib/python3.7/site-packages/seaborn/matrix.py", line 644, in calculated_linkage
    return self._calculate_linkage_fastcluster()
  File "/mnt/xxx/conda/lib/python3.7/site-packages/seaborn/matrix.py", line 637, in _calculate_linkage_fastcluster
    metric=self.metric)
  File "/mnt/xxx/conda/lib/python3.7/site-packages/fastcluster.py", line 247, in linkage
    linkage_wrap(N, X, Z, mthidx[method])
FloatingPointError: NaN dissimilarity value.
```

#### Expected Output:
Describe what you expect the output to be. It is also very useful to know the expected "correct" behavior on your systems.

#### pyani Version:

Current master branch

#### installed dependencies
If you are running a version of `pyani` v0.3 or later, then please run the command `pyani listdeps` at the command line, and enter the output below.

```
$ pyani listdeps
System information
	Platorm==Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-centos-7.8.2003-Core
	Python==3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48) 
[GCC 7.3.0]
Installed pyani Python dependendencies...
	Pillow==Not Installed (-)
	biopython==1.77.dev0 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
	matplotlib==3.1.3 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
	namedlist==1.7 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
	networkx==2.3 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
	numpy==1.17.4 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
	openpyxl==Not Installed (-)
	pandas==1.1.0 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
	scipy==1.4.1 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
	seaborn==0.10.1 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
	sqlalchemy==1.3.6 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
	tqdm==4.41.1 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
Installed pyani development dependendencies...
	bandit==1.6.2 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
	black==19.3b0 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
	codecov==Not Installed (-)
	coverage==Not Installed (-)
	doc8==Not Installed (-)
	flake8==3.7.9 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
	jinja2==2.10.1 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
	mypy==Not Installed (-)
	pydocstyle==5.0.2 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
	pylint==Not Installed (-)
	pytest==Not Installed (-)
	pytest-cov==Not Installed (-)
	sphinx==2.3.1 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
Installed pyani pip-install dependendencies...
	pre-commit==Not Installed (-)
	pytest-ordering==Not Installed (-)
	sphinx-rtd-theme==0.4.3 (/mnt/xxx/apps/conda/lib/python3.7/site-packages)
Installed third-party tool versions...
	blast+==Linux_2.9.0+
	nucmer==Linux_3.1
Traceback (most recent call last):
...
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('blastall'): PosixPath('blastall')
```

See #218.

Also relevant:

```
$ python -c "import fastcluster; print(fastcluster.__version__)"
1.1.26
```

#### Python Version:

```
$ python --version
Python 3.7.6
```

#### Operating System:

Linux

**Comment by peterjc** [comment]
I removed the new reference genomes, and re-ran pyani createdb, index, anim, report, plot - still have the exception.

That set of files worked previously - to me this is strongly suggestive of a corrupt/partial file in the nucmer cache. e.g. an aborted ``pyani anim ...`` run without ``--recovery`` perhaps?

**Comment by peterjc** [comment]
As an aside, with ~500 genomes, that's 125,000 comparisons - rather too many files in one folder to easily list them sorted by date or size.

**Comment by peterjc** [comment]
I removed the new reference genomes, and removed the nucmer cache, and re-ran pyani createdb, index, anim, report, plot - still have the exception.

This should be the same dataset as was working for me earlier, so this is strange.

**Comment by peterjc** [comment]
Probably need to add some debugging earlier in the plotting to catch and report NaN...

**Comment by widdowquinn** [comment]
I'll take a look if you've got a minimal reproducing dataset… don't fancy the 125k comparison set for the debugging cycle ;)

**Comment by peterjc** [comment]
Me neither!

**Comment by widdowquinn** [comment]
By the time we get to drawing the heatmaps, results are pulled from the database. Have you had a look for an unusual-looking result value in your db?

**Comment by peterjc** [comment]
Lots of NaN entries in the matrix, which I think reflects missing data in the DB. Perhaps if a cluster job did not complete, the output file was missing, but this wasn't enough to abort loading after loading what data there was into the DB?

**Comment by widdowquinn** [comment]
Maybe. The database is `sqlite`, so if you could open it up, check for NaNs in the results table, and trace one back to a specific comparison - then rerun that comparison - we might know for sure.

**Comment by baileythegreen** [comment]
@widdowquinn , @peterjc Is this issue still relevant? and is there something that can be used to reproduce it?

If it could be reproduced, we could at least attempt to handle it gracefully.

**Comment by peterjc** [comment]
I don't think I ever trimmed this down to a reproducible example, but last time I used PyANI we did some work on recovery mode so that side seemed to be working fine.

I'm OK with closing this issue now?
