### ISSUE TITLE
Large matrix plots unweildy

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#222]
#### Summary:

Using pyani with ~500 genomes, I find the PNG matrix plots give a good overview but the labels are too small to read (too pixelated when zoomed in), while the PDF is painfully slow to render in macOS preview (panning when zoomed in enough to read the labels takes too long to be usable).

This is with the default (seaborn) method.

#### Ways forward:

Would the mpl or plotly output be any better?

Should I use a different PDF viewer? Or might SVG perform better?

Could we simplify the images (with a switch or perhaps automatically on large datasets), for example leaving off the numbers within each coloured box should help with PDF rendering?

**Comment by peterjc** [comment]
Good news: the matplotlib output via ``--method mpl`` is much better with large datasets. The PNG captions are legible (although not clear), and the PDF is smaller and faster - and lacks the score text for each combination (I was considering turning that off in the seaborn output).

The matrix is flipped top to bottom (meaning the matplotlib diagonal is ``/`` while the Seaborn diagonal is ``\``).

**Comment by widdowquinn** [comment]
I think it will be worth adding this information to the documentation about visualisation.
