### ISSUE TITLE
where to find pyani

### ISSUE THREAD

**Issue by AlisaGU** [widdowquinn/pyani#226]
I think it's a silly question...
I can't find pyani's directory after `pip3 install pyani`.
Only the `average_nucleotide_identity.py -h` is available.

Could you give me some tips?

Best regards,

**Comment by widdowquinn** [comment]
Hi @AlisaGU - thank you for your interest in `pyani`.

The issue you have is that you have installed pyani v0.2.9, but are using the command-line for v0.3+ This is noted in the project README.md (which refers to the development version), and the documentation you require for v0.2 is here: https://github.com/widdowquinn/pyani/blob/master/README_v_0_2_x.md. I apologise for the inconvenience.

(duplicates #192 #176 #171 #169 #165)

If you have any other questions, please do raise a new issue.

L.

**Comment by AlisaGU** [comment]
Thanks for your quick reply.
You are right!

**Comment by EricDeveaud** [comment]
maybee you will want to tag a 3.x release version ?
