### ISSUE TITLE
Compare distinct sequences

### ISSUE THREAD

**Issue by cms72** [widdowquinn/pyani#227]
#### Summary:
I keep getting this error: 

```
INFO: Processing pairwise ANIb BLAST output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyani/anib.py", line 514, in parse_blast_tab
    data = pd.read_csv(filename, header=None, sep="\t", index_col=0)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/usr/local/bin/average_nucleotide_identity.py", line 967, in <module>
    results = methods[args.method][0](infiles, org_lengths)
  File "/usr/local/bin/average_nucleotide_identity.py", line 728, in unified_anib
    blastdir, org_lengths, fraglengths=fraglengths, mode=args.method
  File "/usr/local/lib/python3.7/site-packages/pyani/anib.py", line 443, in process_blast
    resultvals = parse_blast_tab(blastfile, fraglengths, identity, coverage, mode)
  File "/usr/local/lib/python3.7/site-packages/pyani/anib.py", line 516, in parse_blast_tab
    except pd.io.common.EmptyDataError:
AttributeError: module 'pandas.io.common' has no attribute 'EmptyDataError'

```
#### Description:
I have at least 20 different sequences that I would like to show that there is NO homology between all 20 genes. But I think because they are so distinct, I keep getting the above error. 

#### Reproducible Steps:
```average_nucleotide_identity.py -i ./ -o ./ANIb_output -m ANIb -g -v 2>&1 >error.log```

#### Current Output:
See above

#### Expected Output:
I was hoping I get an ANI of 0 homology

#### pyani Version:
0.12.0

#### Python Version:
3.7 

#### Operating System:
MACOS

**Comment by widdowquinn** [comment]
Hi @cms72 - thank you for your interest in `pyani`.

It sounds like you are comparing genes, but `pyani` is intended only for whole-genome analysis. Also, `pyani` requires that there is sufficient sequence similarity between input genome sequences to get a meaningful result, where it sounds like you are trying to demonstrate the *absence* of sequence similarity; `pyani` is not designed to do that and, in cases where no alignment is possible, it is likely that it will throw an error - such as you see here. The error:

```
File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

suggests that BLAST gives you no alignments because the query and subject sequences are so dissimilar.

It may be worth keeping in mind that, due to the nature of DNA sequences (namely their four-letter alphabet), alignments with less than about 70% sequence identity cannot typically be detected (these are too likely to occur at random).

I'd suggest that, to demonstrate the absence of sequence similarity between genes, you might generate a number of "fake" genes of the same length as your candidates here, and obtain some measures of pairwise alignment quality. This will give you a distribution of alignment qualities for sequences with *no* real similarity.

Then you can compare the pairwise alignment scores for your candidate sequences against that distribution, and see whether they look like random sequence or not.

I hope this helps,

L.

**Comment by cms72** [comment]
Hi Leighton,

Thank you for the reply. 

Sorry, I didn't mean genes but 20 regions ranging from different genomes that ranging from 3kb to 25kb. I was hoping to demonstrate that there are no similarities between any of these regions.

I think I understand the concept you're trying to make with using the measures of pairwise alignment quality - I just got a bit lost when you said to generate a number of fake genes to do this?

Thank you again for your help and advice.

Kind regards,
C

**Comment by widdowquinn** [comment]
No problem - the "fake gene" idea is meant to generate a distribution of scores that correspond to "no detectable homology." For that, you need a set of sequences that looks like your dataset but has no real homology. One way to generate such a set is to take an input sequence sample (one sequence, or a set like you have) and shuffle the symbols. The result will have the same base composition, length and so on, but the sequence order will no longer be preserved: there will be no homology.

You could run this shuffling many times, and then do pairwise comparisons between lots of different sequence pairs. This will (probably) give you a distribution of alignment scores/distances between sequences - no matter how you choose to measure that sequence. That's a distribution of scores when you know there is no homology.

Then, you can conduct pairwise comparisons between your "real" sequences/sets of regions, and see whether the scores lie convincingly within your distribution. If they do, then that's consistent with an absence of detectable homology. If they do not - specificially if the scores are "better" - then there may be some level of relatedness.

It's like doing a null hypothesis significance test, but with an empirical distribution for the null hypothesis.

Cheers,

L.

**Comment by cms72** [comment]
I see. Is the fake gene any better than if I were to construct pairwise comparisons with the actual regions themselves and create a matrix, like what pyani does?

i.e
```
                region 1      region 2      region 3     region 4
region 1        1
region 2                           1
region 3                                              1
region 4                                                                 1
```

Thank you again for your help.

C

**Comment by widdowquinn** [comment]
It may depend on the question you're asking.

Suppose that you get any particular score for a pairwise comparison (bit score, E-value) - how do you determine whether that score indicates detectable homology or something else (e.g. random matching)? The matrix is a collection of pairwise scores, and doesn't - I think - help in answering *that* question.

The "fake gene" idea allows you to set a reference for "no homology" that you can compare each alignment result to. There are certainly other ways to do that, and I'd consider it reasonable to assert that BLAST/MUMmer/whatever's failure to identify alignable regions indicates that there is no detectable homology.

Cheers,

L.

**Comment by cms72** [comment]
Ahh.. I see. Thanks again for your help!

**Comment by peterjc** [comment]
The rewrite pyANI-plus (which should be close to release now) records failed pairwise comparisons as null/NA, handling this much more gracefully: https://github.com/pyani-plus/pyani-plus
