### ISSUE TITLE
docker 

### ISSUE THREAD

**Issue by nclaesnacw** [widdowquinn/pyani#228]
#### Summary:
Please provide a short summary of your issue (in a couple of sentences).
average_nucleotide_identity missing manifest at leightonpritchard 
docker: Error response from daemon:
manifest for leightonpritchard/average_nucleotide_identity:latest not found: manifest unknown

#### Description:
Describe the issue in detail, as clearly as possible.
docker run -v ${PWD}:/host_dir leightonpritchard/genbank_get_genomes_by_taxon ... downloads image and runs successfully
docker run -v ${PWD}:/host_dir leightonpritchard/average_nucleotide_identity ... gives not found:manifest unknown error
This is a different error than one found if average_nucleotide_identity did not exist
#### Reproducible Steps:
Please report a series of steps (e.g. command-line instructions) that would enable someone else to reproduce the issue. If possible, please attach a small set of input files/data that would be sufficient to allow someone else to reproduce the issue. 
In description
If it's not possible to reproduce the issue, please include a description of how you discovered the issue.

#### Current Output:
The output you get from `pyani` or at the terminal, with this issue. It is very useful to know the current "wrong" behavior on your system.
In description

#### Expected Output:
Describe what you expect the output to be. It is also very useful to know the expected "correct" behavior on your systems.

#### installed dependencies
If you are running a version of `pyani` v0.3 or later, then please run the command `pyani listdeps` at the command line, and enter the output below.

**Comment by widdowquinn** [comment]
Hi @nclaesnacw 

Thank you for your patience. This appears to be due to a missing `:latest` tag on that image. Please could you try running:

```bash
docker run -v ${PWD}:/host_dir leightonpritchard/average_nucleotide_identity:v0.2.9
```

Many thanks,

L.
