### ISSUE TITLE
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module

### ISSUE THREAD

**Issue by warming151** [widdowquinn/pyani#229]
#### Summary:
Please provide a short summary of your issue (in a couple of sentences).
Hi I just installed pyani. When I run "nosetests --cover-erase --cover-package=pyani --cover-html --with-coverage", it showed "nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module". I don't know what to do. 

#### Description:
Describe the issue in detail, as clearly as possible.

#### Reproducible Steps:
Please report a series of steps (e.g. command-line instructions) that would enable someone else to reproduce the issue. If possible, please attach a small set of input files/data that would be sufficient to allow someone else to reproduce the issue. 

If it's not possible to reproduce the issue, please include a description of how you discovered the issue.

#### Current Output:
The output you get from `pyani` or at the terminal, with this issue. It is very useful to know the current "wrong" behavior on your system.

#### Expected Output:
Describe what you expect the output to be. It is also very useful to know the expected "correct" behavior on your systems.

#### installed dependencies
If you are running a version of `pyani` v0.3 or later, then please run the command `pyani listdeps` at the command line, and enter the output below.

**Comment by widdowquinn** [comment]
Hi @warming151 - how did you install `pyani`? There is currently a stable version available through `conda` (and in the `version_0_2`) branch; and a development version on the `master` branch. These are configured differently and I would need to know which you are using to advise further.

Without that information, my guess is that installing the `coverage` package might fix your issue - though I have moved testing over to `pytest` from `nose`, and the `README.md` is behind the times.

**Comment by warming151** [comment]
Thank you for your reply!
Actually I've already installed it successfully. Thanks.

Min
________________________________
发件人: Leighton Pritchard <notifications@github.com>
发送时间: 2021年1月5日 18:35
收件人: widdowquinn/pyani <pyani@noreply.github.com>
抄送: warming151 <minhuang15@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [widdowquinn/pyani] nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module (#229)


Hi @warming151<https://github.com/warming151> - how did you install pyani? There is currently a stable version available through conda (and in the version_0_2) branch; and a development version on the master branch. These are configured differently and I would need to know which you are using to advise further.

Without that information, my guess is that installing the coverage package might fix your issue - though I have moved testing over to pytest from nose, and the README.md is behind the times.

―
