### ISSUE TITLE
sqlalchemy requirement missing from setup.py

### ISSUE THREAD

**Issue by EricDeveaud** [widdowquinn/pyani#233]
#### Summary:

sqlalchemy is missing from `install_requires` in setup.py

it is mentionned in `requirements.txt` but install_requires is used to declare dependencies on packages that are required for the package to work and are used by developer of the package, while requirements.txt is used to automate installing of environments

regards

Eric

**Comment by widdowquinn** [comment]
Thank you for these bug reports. Please do note that this is a **version under active restructuring and development**. Some parts of it are out of sync, such as the relationship between `setup.py` and `requirements.txt`.

**Comment by widdowquinn** [comment]
If you need a stable version of `pyani`, please do consider using v0.2.10.

**Comment by EricDeveaud** [comment]
we are already using 0.2.10
just checked out 0.3 to give a look at it

**Comment by baileythegreen** [comment]
@widdowquinn  Should this issue still be open? It looks like `sqlalchemy` has been added to `setup.py`.

**Comment by widdowquinn** [comment]
Fixed with #244 by #246
