### ISSUE TITLE
ZeroDivisionError using average_nucleotide_identity.py

### ISSUE THREAD

**Issue by Veroman** [widdowquinn/pyani#237]
#### Summary:

I am working with average_nucleotide_identity.py to compare short and long read sequence genomes. All the genomes are from the same species. The genomes I am getting an error were downloaded from NCBI. 

#### Description:
First I got this error: 'utf-8' codec can't decode byte 0xb0 in position 37, so I changed my .fna files from ASCII to UTF-8 

but the error I am getting now is:

  File "/users/veroman/.conda/envs/local3/bin/average_nucleotide_identity.py", line 967, in <module>
    results = methods[args.method][0](infiles, org_lengths)
  File "/users/veroman/.conda/envs/local3/bin/average_nucleotide_identity.py", line 569, in calculate_anim
    results = anim.process_deltadir(deltadir, org_lengths, logger=logger)
  File "/users/veroman/.conda/envs/local3/lib/python3.6/site-packages/pyani/anim.py", line 224, in process_deltadir
    query_cover = float(tot_length) / org_lengths[qname]
ZeroDivisionError: float division by zero

I hope you can help me see figure out the problem. thanks.

**Comment by widdowquinn** [comment]
Hi @Veroman - thanks for your interest in `pyani`.

I can't tell what the problem might be from your error message alone. Can you please provide a minimal dataset and the command-line you use that reproduces this error.

Without that dataset, my guess would be that at least one of your sequences is not the same species as the others, despite what you believe the taxonomy to be, before the analysis. Can you please check the output files the alignment generates to ensure that they all gave usable output.

L.

**Comment by Veroman** [comment]
Sure.
For the database, I used the attached file
[Archive.zip](https://github.com/widdowquinn/pyani/files/5990157/Archive.zip)

I downloaded the genomes using the dataset command-line tool from NCBI.

The command I used was:
average_nucleotide_identity.py -i /FASTAgenomes -o /pyani/XTm -m ANIm -g

In the output folder, I only got the nucmer_output folder.  I got the delta and filter files.

thanks!

V

**Comment by widdowquinn** [comment]
Hi @Veroman,

I think the issue may be the way you have structured your input dataset. The `Archive.zip` file expands into a top folder (`Archive`) with one subfolder per genome:

```bash
$ tree Archive
Archive
├── GCA_000313775.1
│   └── GCA_000313775.1_XTG29_genomic.fna
└── GCA_000331775.1
    └── GCA_000331775.1_ASM33177v1_genomic.fna
```

`pyani` requires that all the genomes (or, at least, links to those genomes) are on the same level in a single folder, as for:

```bash
$ tree Archive
Archive
├── GCA_000313775.1_XTG29_genomic.fna
└── GCA_000331775.1_ASM33177v1_genomic.fna
```

Running

```bash
average_nucleotide_identity.py -i Archive -o Archive_out -v -m ANIm --force -g --gmethod seaborn --gformat pdf,png
```

on these genomes gives me good output. Attempting to run a similar command on the decompresse `Archive.zip` gives me an error.

I hope this helps. Let me know if it does, and I'll close the issue.

L.

**Comment by Veroman** [comment]
Thanks @widdowquinn 

Yes, it worked.

I think it was either a problem with the way I downloaded the NCBI genomes (I used datasets command) or the way I tried to move the fasta files to the same folder. 

Thanks again for your quick reply!

V.
