### ISSUE TITLE
`pyani` v0.2.x on Python 3.8

### ISSUE THREAD

**Issue by widdowquinn** [widdowquinn/pyani#239]
#### Summary:
Does `pyani` v0.2 work on Python 3.8?

#### Description:
I've just installed pyani via conda and am getting a bunch of errors with text formatting in the logs. Here is the error output. Is there a simple/easy fix?
 
@davidmam

#### Current Output:

$ average_nucleotide_identity.py -v -g -i genome_data/Elizabethkingia/ -o Elizabethkingia_ANIm --labels genome_data/Elizabethkingia/labels.txt --classes genome_data/Elizabethkingia/classes.txt -l Elizabethkingia_ANIm.log
INFO: pyani version: 0.2.10
INFO: Namespace(blastall_exe='blastall', blastn_exe='blastn', classes='genome_data/Elizabethkingia/classes.txt', filter_exe='delta-filter', force=False, formatdb_exe='formatdb', fragsize=1020, gformat='pdf,png,eps', gmethod='mpl', graphics=True, indirname='genome_data/Elizabethkingia/', jobprefix='ANI', labels='genome_data/Elizabethkingia/labels.txt', logfile='Elizabethkingia_ANIm.log', makeblastdb_exe='makeblastdb', maxmatch=False, method='ANIm', noclobber=False, nocompress=False, nucmer_exe='nucmer', outdirname='Elizabethkingia_ANIm', rerender=False, scheduler='multiprocessing', seed=None, sgeargs=None, sgegroupsize=10000, skip_blastn=False, skip_nucmer=False, subsample=None, verbose=True, workers=None, write_excel=False)
INFO: command-line: /cluster/dtu/miniconda3/envs/BS32011/bin/average_nucleotide_identity.py -v -g -i genome_data/Elizabethkingia/ -o Elizabethkingia_ANIm --labels genome_data/Elizabethkingia/labels.txt --classes genome_data/Elizabethkingia/classes.txt -l Elizabethkingia_ANIm.log
INFO: Input directory: genome_data/Elizabethkingia/
INFO: Creating directory Elizabethkingia_ANIm
INFO: Output directory: Elizabethkingia_ANIm
INFO: Using ANI method: ANIm
INFO: Using scheduler method: multiprocessing
INFO: Identifying FASTA files in genome_data/Elizabethkingia/
 
.... lots snipped.
 
TypeError: %d format: a number is required, not tuple
Call stack:
  File "/cluster/dtu/miniconda3/envs/BS32011/bin/average_nucleotide_identity.py", line 977, in <module>
    draw(methods[args.method][1], gfmt)
  File "/cluster/dtu/miniconda3/envs/BS32011/bin/average_nucleotide_identity.py", line 802, in draw
    pyani_tools.get_labels(args.classes, logger=logger),
  File "/cluster/dtu/miniconda3/envs/BS32011/lib/python3.8/site-packages/pyani/pyani_tools.py", line 187, in get_labels
    logger.warning("%d: %s", (count, line.strip()))
Message: '%d: %s'
Arguments: ((33, 'SRR3240399_finaloutbreak'),)
--- Logging error ---
Traceback (most recent call last):
  File "/cluster/dtu/miniconda3/envs/BS32011/lib/python3.8/site-packages/pyani/pyani_tools.py", line 183, in get_labels
    key, label = line.strip().split("\t")
ValueError: not enough values to unpack (expected 2, got 1)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/cluster/dtu/miniconda3/envs/BS32011/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/cluster/dtu/miniconda3/envs/BS32011/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/cluster/dtu/miniconda3/envs/BS32011/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/cluster/dtu/miniconda3/envs/BS32011/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not tuple
Call stack:
  File "/cluster/dtu/miniconda3/envs/BS32011/bin/average_nucleotide_identity.py", line 977, in <module>
    draw(methods[args.method][1], gfmt)
  File "/cluster/dtu/miniconda3/envs/BS32011/bin/average_nucleotide_identity.py", line 802, in draw
    pyani_tools.get_labels(args.classes, logger=logger),
  File "/cluster/dtu/miniconda3/envs/BS32011/lib/python3.8/site-packages/pyani/pyani_tools.py", line 187, in get_labels
    logger.warning("%d: %s", (count, line.strip()))
Message: '%d: %s'
Arguments: ((33, 'SRR3240399_finaloutbreak'),)
WARNING: (skipping line)
INFO: Done: Tue Feb 16 17:30:25 2021.
INFO: Time taken: 42.18s

#### Expected Output:

Actual pyani analysis result

#### pyani Version:

v0.2.10

#### Python Version:

3.8

**Comment by widdowquinn** [comment]
Hi @davidmam - I do see this issue, too. I'll look into it.

**Comment by widdowquinn** [comment]
I think the problem is in the `classes.txt` file for the `Elizabethkingia` directory. Two of the lines appear to have spaces for tabs (maybe introduced with an editor that automatically puts spaces in for tabs?). Replacing these with tabs produces the expected output.

I admit, `pyani` does not fail gracefully here… apologies for that.

I'm attaching a fixed `classes.txt` file that may help. Let me know if this works, and I'll close the issue.

L.

[classes.txt](https://github.com/widdowquinn/pyani/files/5994977/classes.txt)

**Comment by davidmam** [comment]
That seems to do the job! I'll now know what to look out for if I see similar for our own data.

..d
