### ISSUE TITLE
Classification of genomes from the results of the analysis is empty

### ISSUE THREAD

**Issue by oliviaastencio** [widdowquinn/pyani#243]
Section 6 of the Readme file (Classification of genomes from the results of the analysis) is empty and without information. I want to classify 8 different strains of the same genus by comparing them to 64 NCBI complete genomes. What would be the correct guidelines using Pyani?

Thanks you

Olivia A

**Comment by widdowquinn** [comment]
Hi @oliviaastencio,

Thank you for your interest in `pyani`.

The `pyani classify` subcommand is experimental and prone to change, but you're welcome to use it if you're trying v0.3. We appreciate constructive feedback.

For basic use, you need only specify the directory you want to write results to, and the ID of your run in the database, e.g.:

```bash
pyani classify ANIm_my_orgs 1
```

Right now we don't guarantee the results of this command, which is more limited than it will eventually be, but you may find them interesting.

You can get more help  with the command `pyani classify -h`:

```bash
$ pyani classify -h
usage: pyani.py classify [-h] [-l LOGFILE] [-v] [--debug] [--disable_tqdm] [--citation] [--dbpath DBPATH] [--cov_min COV_MIN] [--id_min ID_MIN] [--min_id MIN_ID] [--max_id MAX_ID]
                         [--resolution RESOLUTION] [--show_all]
                         outdir run_id

positional arguments:
  outdir                output directory
  run_id                run ID to classify

optional arguments:
  -h, --help            show this help message and exit
  -l LOGFILE, --logfile LOGFILE
                        logfile location (default: None)
  -v, --verbose         report verbose progress to log (default: False)
  --debug               report debug messages to log (default: False)
  --disable_tqdm        Turn off tqdm progress bar (default: False)
  --citation            Display pyani citation after run (default: False)
  --dbpath DBPATH       path to pyani database (default: .pyani/pyanidb)
  --cov_min COV_MIN     minimum %coverage for an edge (default: 0.5)
  --id_min ID_MIN       minimum %identity for an edge (default: 0.8)
  --min_id MIN_ID       minimum identity threshold to test (default: None)
  --max_id MAX_ID       maximum identity threshold to test (default: None)
  --resolution RESOLUTION
                        number of identity thresholds to test (default: 0.0001)
  --show_all            report all intervals in log (default: only intervals where all subgraphs are k-complete (default: False)
```

**Comment by oliviaastencio** [comment]
Hi @widdowquinn 

Thanks for pyani and your answer
I have used the subcommand pyani classify. It runs correctly and without error sign but the output directory is without files or output information so I don't get reassignment results.

Thanks 
Olivia

**Comment by widdowquinn** [comment]
Hi @oliviaastencio 

Would you be able to provide a minimal dataset, and an account of the commands you used, so I can try to reproduce this problem, please?

L.

**Comment by oliviaastencio** [comment]
Hi @widdowquinn 

I have test run with "Candidatus Blochmannia" (Readme file). This genus currently has 8 different strains described (https://www.ncbi.nlm.nih.gov/genome/browse#!/prokaryotes/Candidatus%20Blochmannia).
 The "Blochmannia endosymbiont of Colobopsis nipponica" and "Blochmannia endosymbiont of Camponotus nipponensis" were identified in 2020. To classify these new genomes in the genus I have used the following commands: 

pyani download C_blochmannia --email oliastenciogomez@gmail.com -t 203804 -v -l C_blochmannia_dl.log 
pyani createdb 
pyani anim --workers 8 C_blochmannia C_blochmannia_ANIm -v -l C_blochmannia_ANIm.log --labels C_blochmannia/labels.txt --classes C_blochmannia/classes.txt
pyani report -v --runs C_blochmannia_ANIm/ --formats html,excel,stdout --genomes > report.log
pyani report C_blochmannia_ANIm --formats=stdout --run_matrices 1 > matrices.log
pyani plot C_blochmannia_ANIm 1 -v --formats png,pdf
pyani classify ANIm_my_orgs 1

I get the graphical representation with pyani plot but not the results of the classify command.

Thanks
Olivia

**Comment by widdowquinn** [comment]
**NOTE:** the `pyani classify` tool is still under development and not all features are ready for use

To get the information `pyani classify` currently outputs, you need to use the command:

```bash
$ pyani classify -v ANIm_my_orgs 1
[...]
[INFO] [pyani.scripts.subcommands.subcmd_classify]: 2 intervals with special property:
	0.9802718488000001	Cliquesinfo(n_nodes=8, n_subgraphs=7, all_k_complete=True)
	1	Cliquesinfo(n_nodes=8, n_subgraphs=8, all_k_complete=True)
```

There's a trivial separation of all the genomes into individual blocks where the threshold is %identity = 1. That just means the genomes are not identical.

The interesting one is at 98.03% identity; that's the point where the Cb pennsylvanicus and Cb chromaiodes genomes form a "clique" distinct from all other genomes (which are also in cliques of size 1) - and as this is at >95% identity, I'd say pennsylvanicis and chromaiodes are the same species.

However, this doesn't inform about genus assignment - which seems to be your question of interest.

There is no formal or widely-accepted genome-based definition of species (though see Barco *et al.* (2020) *mBio* [https://dx.doi/10.1128/mBio.02475-19](https://dx.doi/10.1128/mBio.02475-19) for one approach). I tend to use a 50% coverage heuristic (genomes sharing less than 50% coverage could each share the majority of their genomes with completely different organisms). Inspecitng the graph for your genomes, there is one genus-level grouping of three genomes:  {Cb pennsylvanicus, Cb chromaiodes, B. endosymb. C. nipponensis}, and the rest share less than 7% of homologous genome sequence with each other - these are all different and distinct genera. With either interpretation, the coverage plot tells me there are six distinct genus-level groups being represented by these genomes.

I hope this is useful, but let me know if I can help further.

**Comment by oliviaastencio** [comment]
Hi @widdowquinn 

I am new to using Pyani, thanks for your  feedback. First all I understand that the two cliques include different genomes and they are the same species depending on the identity value (> 95%) . Based on your results, How do you know that Cb pennsylvanicus and Cb chromaiodes genomes form the cliques of size 0.9802 and the others genome the size 1 and not otherwise? The genomes represent the diferents node? and Wich represent de n_subgraphs?

Thanks 
Olivia

**Comment by widdowquinn** [comment]
> How do you know that Cb pennsylvanicus and Cb chromaiodes genomes form the cliques of size 0.9802

I looked at the output figures.

> Wich represent de n_subgraphs?

Clique identification proceeds by constructing a graph that connects genomes (nodes) by the strength of their similarity as identified by `pyani`. First we remove edges with <50% coverage; then we step through removing edges from lowest identity to highest. `n_subgraph` refers to the number of (disjoint) subgraphs identified at each step.

**Comment by oliviaastencio** [comment]
Hi @widdowquinn 

  I am currently have 5 strains of the genus _Shewanella_.sp and I don't know the species to which it belongs. We want to use pyani to classify these strains by comparing them with 82 complete genomes of _Shewanella_.sp. But pyani compares all genomes with each other and generating figures that are difficult to visualize. Is there any possibility of filtering only the classification of these 5 strains of interest? 

Thanks
Olivia
