### ISSUE TITLE
Is Apache `superset` a better dashboard interface to the `pyani` database than `flask`?

### ISSUE THREAD

**Issue by widdowquinn** [widdowquinn/pyani#249]
We should investigate whether this is a useful view onto the `pyanidb` database.

- `superset` repo: https://github.com/apache/superset

**Comment by baileythegreen** [comment]
@widdowquinn We don't currently use either, right? So this is just deciding on the better option to implement?

**Comment by widdowquinn** [comment]
Yes. It's a reminder to check it out when we get to implementing some kind of visual UI onto the results database.
