### ISSUE TITLE
ANIb with custom fragment size

### ISSUE THREAD

**Issue by JosephAdelskov** [widdowquinn/pyani#25]
I really like using your script for ANI calculations, however whenever I try to set the fragment size for ANIb with the '-s' option the script fails to run.

```
joseph@JADESKTOP:~/comparative_genomics/NDB3Y10/ANI_analysis$ average_nucleotide_identity.py -i ../all_genomes/ -o ANIb_100 -s 100 -m ANIb
usage: average_nucleotide_identity.py [-h] [-o OUTDIRNAME] [-i INDIRNAME] [-v]
                                      [-f] [-s] [-l LOGFILE] [--skip_nucmer]
                                      [--skip_blastn] [--noclobber] [-g]
                                      [--gformat GFORMAT] [--gmethod GMETHOD]
                                      [--labels LABELS] [--classes CLASSES]
                                      [-m METHOD] [--scheduler SCHEDULER]
                                      [--maxmatch] [--nucmer_exe NUCMER_EXE]
                                      [--blastn_exe BLASTN_EXE]
                                      [--makeblastdb_exe MAKEBLASTDB_EXE]
                                      [--blastall_exe BLASTALL_EXE]
                                      [--formatdb_exe FORMATDB_EXE]
                                      [--write_excel]
average_nucleotide_identity.py: error: unrecognized arguments: 100
```
I've had a similar result with your 'calculate_ani.py' script. Am I doing something wrong?

I'm using Python 2.7.6

**Comment by widdowquinn** [comment]
Hi @JosephAdelskov - many thanks for reporting this. You're not doing anything wrong - it's an error in the code.

I've found the issue, and am fixing it in both the `v0.2` and `master` branches. Please try reinstalling from the latest commit ([`master`](https://github.com/widdowquinn/pyani/commit/9cf094194ca8c70d58d1f2301c18ae91636063e0), [`v0.2`](https://github.com/widdowquinn/pyani/commit/0872acdb2fe37a25f1638eb5e8ff1e4cea686a91)), and if there's still a problem, I'll reopen the issue.

I would recommend using ANIm over ANIb. It's faster, and the result isn't influenced by choice of fragment size.
