### ISSUE TITLE
Anaconda Python3.5 requires 'rpy2' v.2.8.0 for pyani to function

### ISSUE THREAD

**Issue by edgingtonn1** [widdowquinn/pyani#26]
It seems that pyani requires a rpy2 version of 2.8.0 (and not 2.7.0) if one is using the Anaconda Python distribution (at least for Mac OS X 'El Capitan', python 3.5), otherwise you get this error:
`File "~/anaconda/lib/python3.5/site-packages/rpy2/robjects/vectors.py", line 336, in <module>
    class StrVector(Vector, StrSexpVector):
TypeError: type 'rpy2.rinterface.StrSexpVector' is not an acceptable base type`

See [here](http://stackoverflow.com/questions/36721933/anaconda-import-error-for-rpy2) for more information on the bug in rpy2 2.7.0.

**Comment by widdowquinn** [comment]
Thanks, Nick. That should be fixed with 9b9de43. If it doesn't do the job for a `pip` install, then please do reopen the issue.
