### ISSUE TITLE
Differences between JSpecies and pyani

### ISSUE THREAD

**Issue by kevinmyers** [widdowquinn/pyani#265]
#### Summary:
I'm comparing two metagenomic samples (multiple MAGs in each) against each other. Traditionally we've used JSpecies, but it's so time consuming that I'd like to use pyani. I'm curious about some differences between the two programs.

#### Description:
I am using JSpecies default settings and looking at both ANIb and ANIm. For pyani, I am using ANIm default, ANIm MaxMatch, and ANIb (all other settings default). In general, there is a good agreement between the two. However, I'm noticing differences in the coverage percentages between JSpecies and pyani and I'm not sure why. For one comparison, JSpecies gives results of ANIm of 100% and coverage of 91% while pyani, for the same comparison, gives different results of ANIm of 100%, coverage of 69%. I am curious why the difference in coverage. I saw in the code references to rounding differences, but this seems more than that.

#### pyani Version:
0.2.10

#### installed dependencies
Numpy, Pandas, Biopython, Scipio, mummer, openpyxl, blast (all installed via Conda, most recent versions of all)

#### Python Version:
3.8.8

#### Operating System:
CentOS 7

**Comment by kevinmyers** [comment]
Hi @widdowquinn - thanks for the quick reply! I'm attaching the two FASTA files that gave this particular result here. Hopefully it works as I've never tried this before! 

If it helps, I am also using the standard `average_nucleotide_identity.py` command for this, with the only differences being the --maxmatch for one ANIm run.

[fasta_examples.zip](https://github.com/widdowquinn/pyani/files/6436022/fasta_examples.zip)

**Comment by widdowquinn** [comment]
Thanks for sharing those two sequences. I think I might have at least a partial answer.

For your two sequences, `pyani` reports two coverage values: 69% and 92%. Coverage is asymmetrical - if an assembly (A) of length 4Mbp aligns to another (B) of 5Mbp as a single continuous sequence with 100% identity, the coverage of A is 100%, but the coverage of B can be no greater than 80%.

I think the same is true for your sequences.

TS32_31.fna has length 1.25Mbp but TS43_20.fna has length 1.66Mbp. The alignment they have in common is about 1.2Mbp. This gives the two coverage values - 69% for TS43_20, and 92% for TS32_31.

![ANIm_alignment_coverage](https://user-images.githubusercontent.com/63981/117333811-39508000-ae91-11eb-93b4-a997fbf5734e.png)

JSpecies also reports two coverage values: 70.35% (TS43_20) and 93.63% (TS32_31). So I think the two applications are in reasonable agreement. 

<img width="921" alt="Screenshot 2021-05-06 at 17 33 10" src="https://user-images.githubusercontent.com/63981/117333891-4f5e4080-ae91-11eb-86a7-55aa512d2fd1.png">

<img width="935" alt="Screenshot 2021-05-06 at 17 33 16" src="https://user-images.githubusercontent.com/63981/117333908-54bb8b00-ae91-11eb-85db-203c19bed80d.png">

I believe much of the difference between the ANIm output of the tools is that we enforce a 1-to-1 mapping between aligned regions in `pyani` where JSpecies does not.

Many thanks for using `pyani`, and please do raise another issue if anything else looks odd. If this answers your question, feel free to close the issue - if not, post up another message and I'll get back to you.

**Comment by kevinmyers** [comment]
Thanks @widdowquinn for the thorough reply! I was looking only at one side of the correlation plots in a quick summary script I wrote to make my life easier, but I see now that it is not ideal. I was doing the same thing for JSpecies. Apologies for not noticing it before emailing you. Is it acceptable to average the two if I wanted a single value or should I just report both? (Sorry I'm relatively new to this field and not sure what is standard practice.)

I do have a few quick questions if you don't mind me asking them in this thread. If it's easier I can make a new thread and delete this comment. What are the *hadamard* results that are printed? What is the difference between ANIb and ANIblastall?

Thanks again! I really think pyani is great and so much easier and quicker to use than JSpecies in my opinion.

**Comment by widdowquinn** [comment]
No worries - it's a more subtle area than it first seems ;) Asking more questions here is fine, and I'll try to take them in order.

- I wouldn't average the two. The meaning of the average value isn't clear to me, and treating the two values as different is informative for your MAG assemblies. Here, for instance, I might treat this as evidence - if these were relatively short and numerous contigs - that the shorter of the two assemblies may be missing some regions from its bin, or the longer one may have some inappropriate sequence included. If, on the other hand, these were complete single-contig Nanopore assemblies, I'd trust the numbers and be interested in the evolutionary implications of the additional 400kbp.

- The Hadamard matrix is the product of the identity and coverage matrices. It's of limited diagnostic use. I'm not entirely sure how to interpret it myself, yet ;)

- ANIb uses the BLAST+ program; ANIblastall uses the legacy BLAST program. The legacy BLAST tool has been deprecated, and is absolutely not recommended. It gives different results to BLAST+, in part because the default algorithm for `blastn` in BLAST+ is completely different to that used in legacy BLAST. You can make it use the old algorithm, but we use the new default.

Thank you for your kind words about `pyani` - I wrote it originally because I was frustrated with JSpecies and wanted something quicker and easier to use :D

**Comment by kevinmyers** [comment]
Thank you! That is all very helpful. Can I ask another question? I see some relatively big differences in ANI values when I run ANIm and ANIm MaxMatch (FASTAs are attached). For this comparison, with ANIm I get around 99% value and with maxmatch on I get 87% value (this is similar to what JSpecies ANIm gives me). Can you elaborate on the maxmatch option? This comparison has very low coverage, so I can eliminate them with that variable, but I'm curious about the differences if you don't mind.

[fasta_examples2.zip](https://github.com/widdowquinn/pyani/files/6436944/fasta_examples2.zip)

**Comment by widdowquinn** [comment]
The ANIm method uses `nucmer` as its alignment tool. `--maxmatch` is a `nucmer` option that changes alignment behaviour.

By default, we use the `--mum` (maximal unique match) option. This restricts alignment anchor sequence only to those that are unique in the reference and query sequence. The `--maxmatch` option uses any qualifying anchor sequence, regardless of whether it is unique in either the query or the subject sequence.

The reason we'd usually employ the `--maxmatch` option is to identify and align repeat regions. It allows you to match, say, region A on the query to similar regions A, A', A'' (and so on) on the reference. This isn't what we want, most of the time, as a single region on the query might contribute more than once to the identity and coverage scores; also, it's likely that some of those matching regions might be quite sequence distant, so it could end up reducing the reported percentage identity, inappropriately.

The guiding principle here for `pyani` is that we want to identify 1-to-1 mapping homologous regions, and assess (1) how similar they are and (2) how much of each genome they cover. `nucmer` is really good for doing this in ways that `BLAST` and other tools are not.

**Comment by kevinmyers** [comment]
Thank you! I really appreciate you taking the time to answer my (probably naïve) questions.

**Comment by widdowquinn** [comment]
No problem at all, @kevinmyers - they're good questions and it helps me to remember why we made the decisions we did. I hope they still make sense!
