### ISSUE TITLE
The repo for black has changed locations

### ISSUE THREAD

**Issue by baileythegreen** [widdowquinn/pyani#270]
#### Summary:
The `.pre-commit-config.yaml` file contains an old URL for black. This did not cause a problem for me when running black from the command line, but when attempting to commit from within atom, I got this error:

`[WARNING] The 'rev' field of repo 'https://github.com/ambv/black' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.`

Changing the URL in the pre-commit file from `https://github.com/ambv/black` to `https://github.com/psf/black`
(which the former now redirects to) resolved the problem. — I have done this only for the `fastANI` branch, so far.

#### Reproducible Steps:
I'm unclear if this issue is likely to be common, or if it relies upon my specific setup.

#### Python Version:
I think atom is running 3.8.

#### Operating System:
MacOS 10.13.6

**Comment by widdowquinn** [comment]
Since we provide the `.pre-commit-config.yaml` file as an aid to developers, we really should fix this. I'll get on it.

**Comment by widdowquinn** [comment]
The solution looks to be a little different to that proposed.

The warning comes from the `rev:` tag - this was advised in the `black`/`pre-commit` (I forget which) documentation to point to `stable` - a mutable reference that ought to point at a specific revision/release. That doesn't work for `black`, as noted in psf/black#420.

So, as indicated there and adopted by a number of other projects, I'm going to pin `black` to a specific version. We'll have to keep an eye on this as we go to make sure we're reasonably up to date.

**Comment by widdowquinn** [comment]
For future reference, the `pre-commit autoupdate` command will update the latest pinned version for each tool listed in the config file.

**Comment by baileythegreen** [comment]
However you want to fix this is fine with me; I only meant to bring the issue to your attention and explain how I had resolved it.

Do you want me to test something on this end, to make sure it works in the environment that originally had the problem?

**Comment by widdowquinn** [comment]
I've pushed PR #271 which has you requested as a reviewer ;)

As it happens, changing the GitHub URL to point to `psf` doesn't fix the problem. The warning seems to appear only on first run to let the user know that the `stable` tag will not update `black` in future then - after that first time - uses the installed version and doesn't warn again. 

The change of URL has no effect as there's an automatic redirection from `https://github.com/ambv/black` to `https://github.com/psf/black`

**Comment by baileythegreen** [comment]
> The warning seems to appear only on first run to let the user know that the `stable` tag will not update `black` in future then - after that first time - uses the installed version and doesn't warn again.

This is not entirely true. Perhaps it depends on something in the configuration, but I got the same error 10 different times—every time I tried submitting my commit. I tried several things to fix it. The only thing that led to the error no longer being raised was changing `ambv` to `psf` in the pre-commit file.

**Comment by widdowquinn** [comment]
Changing the URL does not affect the warning.

```bash
$ git status
On branch test_270
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .pre-commit-config.yaml
[...]
$ head .pre-commit-config.yaml 
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
[...]
$ git add .pre-commit-config.yaml
$ git commit
[WARNING] The 'rev' field of repo 'https://github.com/ambv/black' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
[...]
$ head .pre-commit-config.yaml 
repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
[...]
$ git add .pre-commit-config.yaml 
$ git commit
[WARNING] The 'rev' field of repo 'https://github.com/psf/black' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
```

Pinning the `black` version removes the warning

```bash
$ head .pre-commit-config.yaml 
repos:
-   repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
    - id: black
      language_version: python3
[...]
$ git add .pre-commit-config.yaml
$ git commit
black................................................(no files to check)Skipped
blacken-docs.........................................(no files to check)Skipped
```

**Comment by baileythegreen** [comment]
Well, it changes whether I get the warning in Atom, and whether I can commit from within the editor itself. I don't how, or if, that makes sense.
