### ISSUE TITLE
ANI matrix from .dataframe files

### ISSUE THREAD

**Issue by ZiliaMR** [widdowquinn/pyani#298]
Hello, 

#### Summary:
Possibility to build matrices ANI from .dataframe files

#### Description, command, version:
I am analyzing 2118 data and my analysis took more than 7 days to run, but in the final part of analysis I got an error (see in the end). Is there a possibility to build all ANI matrices (similarity_errors, percentage_identity, etc) from *dataframe files, which are in the output directory?  

Thanks in advance :).

This is the command I ran:

```
average_nucleotide_identity.py -v -l ANIb_2.log -i fasta -o ANIb_output_2 -m ANIb -g --gformat png,pdf --classes classes.tab --labels labels.tab
```

This is the version:
```
(pyani_env) [zilia@rackham3 core_genome]$ average_nucleotide_identity.py --version
average_nucleotide_identity.py: pyani 0.2.10
```

Error:
```
(pyani_env) [zilia@rackham3 core_genome]$ tail -n 30 pyani_core_2118_210609_ZYMR.txt
INFO: All multiprocessing jobs complete.
INFO: Processing pairwise ANIb BLAST output.
Traceback (most recent call last):
  File "/home/zilia/.conda/envs/pyani_env/lib/python3.8/site-packages/pyani/anib.py", line 514, in parse_blast_tab
    data = pd.read_csv(filename, header=None, sep="\t", index_col=0)
  File "/home/zilia/.conda/envs/pyani_env/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/zilia/.conda/envs/pyani_env/lib/python3.8/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/zilia/.conda/envs/pyani_env/lib/python3.8/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/zilia/.conda/envs/pyani_env/lib/python3.8/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/zilia/.conda/envs/pyani_env/lib/python3.8/site-packages/pandas/io/parsers.py", line 1898, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 521, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zilia/.conda/envs/pyani_env/bin/average_nucleotide_identity.py", line 967, in <module>
    results = methods[args.method][0](infiles, org_lengths)
  File "/home/zilia/.conda/envs/pyani_env/bin/average_nucleotide_identity.py", line 727, in unified_anib
    data = anib.process_blast(
  File "/home/zilia/.conda/envs/pyani_env/lib/python3.8/site-packages/pyani/anib.py", line 443, in process_blast
    resultvals = parse_blast_tab(blastfile, fraglengths, identity, coverage, mode)
  File "/home/zilia/.conda/envs/pyani_env/lib/python3.8/site-packages/pyani/anib.py", line 516, in parse_blast_tab
    except pd.io.common.EmptyDataError:
AttributeError: module 'pandas.io.common' has no attribute 'EmptyDataError'
```

**Comment by widdowquinn** [comment]
Hi @ZiliaMR 

Many thanks for your interest in `pyani`.

It looks from your error message that `pyani` is trying to read an empty file, hence the "No columns to parse from file". This suggests either that (i) BLAST found no similarities between the genomes being compared or (ii) the BLAST run failed for some reason.

This should have been caught by the `pd.io.common.EmptyDataError` on line 516 of `pyani/anib.py` when parsing the BLAST ouptut. That exception appears to have been deprecated in the a recent `pandas` release, replaced by `pd.errors.EmptyDataError` - and you're the first user to catch this problem! 🎉

The intent to move the `pandas` error messages was [announced in 2017](https://pandas.pydata.org/docs/whatsnew/v0.20.0.html#whatsnew-0200-privacy), but I missed it! This exception was finally removed in commit [4574fa](https://github.com/pandas-dev/pandas/commit/4574fa56731ca9c6a646194d012eb41b26f56e62) in April 2020 and - again - I missed it. Many apologies.

The fix to this should be relatively minor, so I'll get on to it. I'll post here when it's done.

Don't delete any of your results! You can repeat the analysis without recalculating any BLAST results, using the `--noclobber --skip_blastn` options (the first should ensure that no output is delete when you re-run; the second skips all the BLAST comparisons, and will reuse the ones you already have).

L.

**Comment by ZiliaMR** [comment]
ooh! 😮 😯 😲  Many thanks. 
I will then wait for the pyani update. 
Thank you for your response.

**Comment by widdowquinn** [comment]
v0.2.11 should be available on PyPI now: https://pypi.org/project/pyani/ - I think this will fix the problem. If not, please come back and comment (with error messages).

I'm still getting the release onto bioconda.

L.

**Comment by ZiliaMR** [comment]
Hi, 

I already installed the new version v0.2.11 and I run this command:

```
average_nucleotide_identity.py -v -l ANIb_2.log -i fasta -o ANIb_output -m ANIb -g --gformat png,pdf --classes classes.tab --labels labels.tab --noclobber --skip_blastn
```

and I have this error:


```
INFO: pyani version: 0.2.11
INFO: Namespace(blastall_exe='blastall', blastn_exe='blastn', classes='classes.tab', filter_exe='delta-filter', force=False, formatdb_exe='formatdb', fragsize=1020, gformat='png,pdf', gmethod='mpl', graphics=True, indirname='fasta', jobprefix='ANI', labels='label$
INFO: command-line: /home/zilia/.conda/envs/pyani_env2.11/bin/average_nucleotide_identity.py -v -l ANIb_2.log -i fasta -o ANIb_output -m ANIb -g --gformat png,pdf --classes classes.tab --labels labels.tab --noclobber --skip_blastn
INFO: Input directory: fasta
ERROR: Output directory ANIb_output would overwrite existing files (exiting)
```

Thanks again,

**Comment by widdowquinn** [comment]
Ah. I forgot to mention you need to "take off the safety" and also use the `-f` or `--force` option.

`--noclobber` should ensure that the existing files are not overwritten. But if you want to be cautious, back them up with a `tar -zcf` first…

**Comment by widdowquinn** [comment]
(I'd be cautious ;) )

**Comment by ZiliaMR** [comment]
what do you mean with "take off the safety"? only I have to add ``-f`` or ``--force`` option??

**Comment by widdowquinn** [comment]
> what do you mean with "take off the safety"? only I have to add `-f` or `--force` option??

Yes. By default `pyani` will refuse to continue in the case that it "sees" your existing output, as a safety measure. Using `-f` (or `--force`) will prevent that check.

The combination: `--force --noclobber --skip_blastn` *should* reuse your existing output.

**Comment by ZiliaMR** [comment]
Hi, 

I ran it, but nothing seems to happen. (I did make a backup). 

So, I ran the analysis again in another place (from the zero), so I'm waiting for the results.

**Comment by widdowquinn** [comment]
I would have expected there to have eventually been some output. With 2000+ input genomes and running BLAST, there will be over 4m output files to process - this takes some time. It may have been busy with file IO even if it looked like nothing was happening. Using the `-v` verbose option can be reassuring of activity.

I'm glad you're making progress, anyway - I hope you get the results you're looking for!
