### ISSUE TITLE
ANIm ouput files need some explanation

### ISSUE THREAD

**Issue by phbrito** [widdowquinn/pyani#303]
I am using pyani and it is great, easy to use with nice figures. Yet, I need more information regarding some of the output data that I get with ANIm and I can´t find it anywhere else. Please help!

I am running pyani for a large multispecies dataset and my goal is to get ANIm estimations of all pairwise genome comparisons so I can estimate average intraspecific and interspecific ANIm.

I need help interpreting these output files:
ANIm_alignment_coverage
ANIm_alignment_lengths
ANIm_hadamard
ANIm_similarity_errors

And I am not sure if I can trust results for which I got ANIm=0.84 but
alignment coverage = 0.10, 
alignment  length = 1/10 of intraspecific alignment length
Hadamard=0.09 while intraspecific is 0.98
Similarity error file does vary according to intra/interspecific comparisons.

Thanks
Patricia

#### pyani Version:
pyani 0.2.11

#### installed dependencies
installed with conda

**Comment by widdowquinn** [comment]
Hi @phbrito 

Thank you for your interest in `pyani`.

- alignment coverage is the proportion of the query genome that aligns against the reference genome (this can be asymmetrical: comparing genome A to genome B may give different coverage values for A and B).
- alignment length is the count of bases in the pairwise alignment of two genomes
- similarity errors is a measure of the number of bases/positions that do not match
- hadamard is the product (identity x coverage)

Given the values you state, I would consider that the two genomes being compared come from different genera, as their coverage is so low.

I would say that you can trust the ANIm results, and that the results are telling you that particular comparison is between two organisms from different genera.

I hope this is helpful,

L.

**Comment by phbrito** [comment]
Hi @widdowquinn 
thanks for your fast reply. It is clear now.
(for Similarity error what I meant to say was that results do NOT vary according to intra or interspecific comparisons, but I guess you understood that).
thanks
Patricia
