### ISSUE TITLE
NUCmer run failure

### ISSUE THREAD

**Issue by snehamurthy21** [widdowquinn/pyani#312]
WARNING: Total alignment length reported in ANI_out/nucmer_output/Aedes-albopictus-C6-36-cell-line_SCAFFOLDS_GCA_001876365.2_vs_GCF_006496715.1_Aalbo_primary.1_genomic.filter is zero!
ERROR: This has possibly been a NUCmer run failure, please investigate
ERROR: NoneType: None

This is my error for my pyANI

please help me crack this open

I am running ANI for 5 mosquito genomes, 3 are of same species different isolates, 1 is different species and 1 is different mosquito genus.

**Comment by widdowquinn** [comment]
Hi @snehamurthy21 

Thank you for your interest in `pyani` - this is an interesting issue.

Firstly, I should say that `pyani` is designed for microbial genomics, and mosquitoes are not microbes. There are major differences between eukaryotic and prokaryotic genomes, and I would not recommend using `pyani` for eukaryotes (with a few exceptions).

The issue you're seeing right now suggests that there is no identifiable homology between the two sequence files being compared. If you expect that there *is* in fact some sequence homology there, you could use another comparison tool (e.g. pairwise BLAST) possibly with a suitable visualisation package (e.g. IGV) to get more information. But, for now, it appears that the `nucmer` comparison `pyani` is using does not find any significant sequence identity between those sequences.

If you have other genomes in your analysis - and they give good output - you may want to consider dropping one of these sequences.

If your goal is to find a phylogeny for these organisms, I would recommend finding a multigene tree - `pyani` is not really set up for this kind of comparison between eukaryotes.

Cheers,

L.

**Comment by snehamurthy21** [comment]
Thank you for your reply, my bad i didnt realise its specific to microbes, i should have read through

Will definitely do more on the grounds you mention,
Thank you once again
