### ISSUE TITLE
Add install instructions for devs

### ISSUE THREAD

**Issue by baileythegreen** [widdowquinn/pyani#316]
#### Summary:
Even if I am the only one who ever uses it. I am currently trying to remember how I had this installed on my laptop so I can make sure it is all working the same on this new computer.

**Comment by widdowquinn** [comment]
https://github.com/widdowquinn/pyani/blob/master/CONTRIBUTING.md#setting-up-a-development-environment

**Comment by baileythegreen** [comment]
The:

```python
pip install pyani -e .
```

line, for one.

**Comment by baileythegreen** [comment]
I'll have to reread through that whole thing to see what else should maybe be added.

**Comment by widdowquinn** [comment]
Related to this - but possibly a discussion item also - there's a recent PEP ([https://www.python.org/dev/peps/pep-0665/]) about specifying installation requirements.

**Comment by baileythegreen** [comment]
Is there any indication of a timeline for adoption, or whether that PEP *will be* adopted? It would certainly represent a departure from what we do now, and after reading it, I am still left unsure what we would use to generate such a lock file, or whether `conda` and `pip` currently support the format.

**Comment by widdowquinn** [comment]
I don't think we need to do more at this point than know the PEP is there.

Is there anything that needs to be done for this issue, or can it now be closed?

**Comment by baileythegreen** [comment]
I think once we settle on how to introduce the `pip install -e .` command in the documentation it can be closed. See PR #334.
