### ISSUE TITLE
Add `plotly` support to `pyani graphics`, or remove the option from the parser

### ISSUE THREAD

**Issue by baileythegreen** [widdowquinn/pyani#318]
#### Summary:
`plotly` is listed as one of the three plotting options when running `pyani plot -h`, but there is no code currently supporting this.

#### Reproducible Steps:

Assuming an existing database with the default name (`.pyani/pyanidb`), with at least one run in it:

`pyani plot -h`
`pyani plot outdir 1 --method plotly`

If it's not possible to reproduce the issue, please include a description of how you discovered the issue.

#### Current Output:
```python
Traceback (most recent call last):
  File "/Users/baileyharrington/miniconda3/bin/pyani", line 33, in <module>
    sys.exit(load_entry_point('pyani', 'console_scripts', 'pyani')())
  File "/Users/baileyharrington/Software/pyani/pyani/scripts/pyani_script.py", line 117, in run_main
    returnval = args.func(args)
  File "/Users/baileyharrington/Software/pyani/pyani/scripts/subcommands/subcmd_plot.py", line 94, in subcmd_plot
    write_run_heatmaps(run_id, session, outfmts, args)
  File "/Users/baileyharrington/Software/pyani/pyani/scripts/subcommands/subcmd_plot.py", line 134, in write_run_heatmaps
    write_heatmap(
  File "/Users/baileyharrington/Software/pyani/pyani/scripts/subcommands/subcmd_plot.py", line 202, in write_heatmap
    GMETHODS[args.method](
KeyError: 'plotly'
```

#### Expected Output:
Plots.

#### pyani Version:
0.3.0-alpha

**Comment by widdowquinn** [comment]
We've discussed this at meetings. Adding `plotly` support is a goal, in part intended for the proposed `Flask` support, so that we can have interactive, rather than static, graphics in that interface.

**Comment by widdowquinn** [comment]
It's OK for the documentation to be slightly out of sync during development.

**Comment by baileythegreen** [comment]
I don't remember discussion `plotly`, though I know there is a discussion about `Flask`. I just noticed that option wasn't implemented when I was adding scatterplot code.

**Comment by widdowquinn** [comment]
I remember discussion of `plotly` in the context of `matplotlib` vs `seaborn` (vs…) and in the context of a candidate `Flask`interface. In any case, the point about synchronisation of code and docs is the important one. Writing docs ahead of implementation (including inline docs) can set a target to code to, just as writing tests ahead of implementation (aka test-driven development) gives a target to code to.

My view is that the appropriate course of action here is to create an issue like #124 for `plotly` as an output option and include it in the milestones for a release version in the `Project` section.
