### ISSUE TITLE
`pyani report` help information could be clearer

### ISSUE THREAD

**Issue by baileythegreen** [widdowquinn/pyani#332]
#### Summary:
Usage of `pyani report` does not seem clearly conveyed by the `help` information for the subcommand.

#### Description:
I tried producing reports for a `pyani` run, and found it took me several tries to correctly specify the options. It has been a while since I used it, and I had forgotten details about it. I expected it would be similar to the `pyani plot` interface, and I think it is—on the backend—but that is not clear from the help information. Details below.

Usage information for `pyani report` and `pyani plot` for comparison:
```bash
pyani report -h
          [--runs_genomes] [--genomes_runs] [--run_results RUN_RESULTS] [--run_matrices 
          RUN_MATRICES] [--formats FORMATS] outdir

positional arguments:
  outdir                output analysis results directory

optional arguments:
  -h, --help            show this help message and exit
  -l LOGFILE, --logfile LOGFILE
                        logfile location (default: None)
  -v, --verbose         report verbose progress to log (default: False)
  --debug               report debug messages to log (default: False)
  --disable_tqdm        Turn off tqdm progress bar (default: False)
  --version
  --citation
  --dbpath DBPATH       path to pyani database (default: .pyani/pyanidb)
  --runs                Report table of analysis runs in database (default: False)
  --genomes             Report table of genomes in database (default: False)
  --runs_genomes        Report table of all genomes for each run in database (default: False)
  --genomes_runs        Report table of all runs in which each genome in the database participates (default: False)
  --run_results RUN_RESULTS
                        Report table of results for a pyani run (default: False)
  --run_matrices RUN_MATRICES
                        Report matrices of results for a pyani run (default: False)
  --formats FORMATS     Output formats (in addition to .tab) (default: None)


pyani plot -h
         [-h] [-l LOGFILE] [-v] [--debug] [--disable_tqdm] [--version] [--citation] [--dbpath 
         DBPATH] [--formats FORMATS] [--method {seaborn,mpl,plotly}] outdir run_id

positional arguments:
  outdir                output directory
  run_id                run ID to plot

optional arguments:
  -h, --help            show this help message and exit
  -l LOGFILE, --logfile LOGFILE
                        logfile location (default: None)
  -v, --verbose         report verbose progress to log (default: False)
  --debug               report debug messages to log (default: False)
  --disable_tqdm        Turn off tqdm progress bar (default: False)
  --version
  --citation
  --dbpath DBPATH       path to pyani database (default: .pyani/pyanidb)
  --formats FORMATS     graphics output format (pdf/png/svg/jpg) (default: png)
  --method {seaborn,mpl,plotly}
                        graphics method to use for plotting (default: seaborn)
```

The default value of `False` makes it seem like options such as `--run_results` require a boolean argument, but:
```bash
! pyani report scratch --run_results True --dbpath scratch/scratch.db
```
produces tables with `True` in the name. Upon reconsidering the help output, I thought perhaps an argument was not required, and ran:
```bash
! pyani report scratch --run_results --dbpath scratch/scratch.db

pyani.py report: error: argument --run_results: expected one argument
```
but this produced a file with only a header, so an argument clearly is required. I tried specifying a number, as I know this is how `pyani plot` works (though `pyani plot` asks for `run_id` by way of conveying this idea):

```bash
! pyani report scratch --run_results 1 --dbpath scratch/scratch.db
```
this worked, but I do not feel that the `help` output is particularly *helpful*; had I not already known there were `run_id`s and how `pyani plot` worked, I might have become very frustrated.

#### Expected Output:
Describe what you expect the output to be. It is also very useful to know the expected "correct" behavior on your systems.

I would expect more consistency in how the user communicates with the subcommands. A fix might be as simple as referring to `run_id`s in the `pyani report` parser, and maybe changing the default values to `None`.

#### pyani Version:
`pyani version: 0.3.0-alpha`

**Comment by widdowquinn** [comment]
Yes, this needs significant expansion in the documentation/walkthroughs.

**Comment by baileythegreen** [comment]
I am also going to advocate for changing what `help` prints out; if not things in the actual parser. We can discuss this first (if you want), or I can do what i think makes sense, and we can discuss a PR.

**Comment by widdowquinn** [comment]
I'm happy with the `argparse` approach, by and large, but if you have ideas for making that more helpful then here's a reasonable place to present them. It may save work to get something we're both happy with before coding and making the PR.

**Comment by baileythegreen** [comment]
Oh, I am also happy with `argparse`. I mean making the help strings more clear, and possibly changing the default values for some of them. (The latter depends on how much that affects the rest of the code; I think in this case, since it only really interacts with `argparse` and not the ORM, it shouldn't be a big hassle.)
