### ISSUE TITLE
Sparse distance matrix

### ISSUE THREAD

**Issue by snayfach** [widdowquinn/pyani#350]
The matrix outputs (*.tab) become unwieldy with thousands of genomes. It would be great if there was an option to output a sparse distance matrix instead (fields: id1, id2, ani, alignment length, alignment coverage). I'm running pyani 0.2.11)

**Comment by widdowquinn** [comment]
Hi @snayfach 

Many thanks for using `pyani`!

My understanding is that a sparse matrix is one that mostly contains zero elements (e.g. https://en.wikipedia.org/wiki/Sparse_matrix), which means that considerable space/processing time is saved by representing only non-zero entries in the manner you describe.

However, `pyani`'s output is rarely, if ever, of this form so sparse matrix representation isn't appropriate, as I understand it.

`pyani` 0.3+ stores output in a local SQLite database, similar to the structure you describe. However, the most efficient representations of the datasets are still, to our measurement at least, stored 2D matrices. As a result we store the run representation in this way, and the pairwise comparison representation as a table row.

It's possible I may be misunderstanding, or that your dataset has characteristics that make it amenable to sparse representation. Would you be able to give us some more information about your dataset to establish that sparse matrices improve data representation in this case?

Cheers,

L.
