### ISSUE TITLE
Default labels in matrix output, 1:1 2:2 3:3 etc

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#357]
#### Summary:

Matrix output is not applying labels, e.g. example with 17 genomes:

```
$ head -n 1 matrix_identity_1.tab 
1:1	2:2	3:3	4:4	5:5	6:6	7:7	8:8	9:9	10:10	11:11	12:12	13:13	14:14	15:15	16:16	17:17
```

#### Description:

The problem is a string vs integer mapping, cross reference b54106f36428f017a2589b05de33c0a6d3ed9ea4 (15 Oct 2019) addressing a similar issue with Seaborn plotting.

#### Reproducible Steps:

I have added debug logging:

```
$ git diff
diff --git a/pyani/scripts/subcommands/subcmd_report.py b/pyani/scripts/subcommands/subcmd_report.py
index 3b1d1bb..6d79009 100644
--- a/pyani/scripts/subcommands/subcmd_report.py
+++ b/pyani/scripts/subcommands/subcmd_report.py
@@ -263,6 +263,8 @@ def subcmd_report(args: Namespace) -> int:
             logger.debug("Extracting matrices for run %s", run_id)
             run = session.query(Run).filter(Run.run_id == run_id).first()
             matlabel_dict = get_matrix_labels_for_run(session, run_id)
+            logger.debug("Have %i matrix labels for run", len(matlabel_dict))
+            logger.debug("Matrix labels %s", matlabel_dict)
             for matdata in [
                 MatrixData(*_)
                 for _ in [
@@ -277,7 +279,9 @@ def subcmd_report(args: Namespace) -> int:
                 matrix = pd.read_json(matdata.data)
                 # Matrix rows and columns are labelled if there's a label dictionary,
                 # and take the dataframe index otherwise
+                logger.debug("Matrix columns before labels %s...", repr(matrix.columns)[:150])
                 matrix = label_results_matrix(matrix, matlabel_dict)
+                logger.debug("Matrix columns after labels %s...", repr(matrix.columns)[:150])
                 pyani_report.write_dbtable(
                     matrix,
                     Path(
```

This shows ``matlabel_dict`` is loaded by function ``get_matrix_labels_for_run`` with string keys, ``'1'`` to ``'17'``. See b54106f36428f017a2589b05de33c0a6d3ed9ea4 which added string casting.

However, function ``label_results_matrix`` is still looking up integer row/column indexes, and finding no match and applying the default value giving label strings of ``'1:1'``, ..., ``'17:17'`` instead.

I think we need a string cast in ``label_results_matrix`` prior to dictionary lookup, but fear side effects... this fixes my example, PR to follow.

(Updated - was trying the tests without the development environment active)

**Comment by peterjc** [comment]
Pull request #358 has the small change which fixes my example and does not break any tests - but may have some side effects in the graphical plots?

**Comment by baileythegreen** [comment]
What does the result of this look like for you?

The start of my first and second rows with your code look like this:

```
Dickeya undicola strain FVG1-MFV-O17 Dickeya_sp._FVG1-MFV-O17_contig_1, whole genome shotgun sequence:1	Brenneria roseae subsp. americana strain LMG 27715 scaffold1, whole genome shotgun sequence:2
1.0	0.789859
```

I would think that the first entry on every subsequent row should be a name, also, but I don't know what the intention was when this was written. @widdowquinn?

I don't see any difference between results plotted from this PR's code and from the primary branch, and I don't think the bit that's been changed is called during plotting, as that code comes from `pyani/pyani_graphics/sns/__init__.py`.

**Comment by peterjc** [comment]
True, I only see column labels - no row labels. Which isn't a blocker for what I want to do with the matrix, but could be a different bug. I have not searched the tests for a sample output file which I think we probably should record.

As to the graphs, hopefully they are unchanged - but I was wary about the integer vs string key change (since I didn't follow why that was done in the first place).

**Comment by widdowquinn** [comment]
> I would think that the first entry on every subsequent row should be a name, also, but I don't know what the intention was when this was written. @widdowquinn?

The matrix output code here is placeholder code, and I was anticipating the `.tab` matrices to be essentially the same format as in v0.2.

Suggestions for improvement over that are welcome - though I did want to take advantage of `pandas`' ability to do the reformatting rather than have to reimplement a bunch of it.

**Comment by peterjc** [comment]
Ah, I hadn't thought to compare the master branch (pre-release v3) with the v2 behaviour.

**Comment by peterjc** [comment]
Reopen following #360?
