### ISSUE TITLE
ANI identity values missing on pyani plots

### ISSUE THREAD

**Issue by papicbojan** [widdowquinn/pyani#363]
#### Description and Current Output:
When running pyani with options -m ANIm -g, my graphical outputs are almost complete, but lack ANI identity values; only colored squares without the values are present in ANIm_percentage_identity output figures. 

#### Expected Output:
I would like to plot ANI identity values onto ANIm_percentage_identity output figures, as exemplified in the manual: https://pyani.readthedocs.io/en/latest/quickstart.html?highlight=graphical#graphical-output 
I kindly ask for advice on how ANI values can be plotted onto the output figures.

#### pyani Version:
pyani v0.2.11

#### Operating System:
Linux Debian

**Comment by widdowquinn** [comment]
Hi @papicbojan 

Thank you for using `pyani`. To obtain identity values in the cells of the heatmaps, you have to use the `seaborn` graphics method (this is not the default).

I hope this helps,

L.

**Comment by papicbojan** [comment]
> 

Thank you, adding _--gmethod seaborn_ to the command solved the issue. 
Kind regards, 
Bojan
