### ISSUE TITLE
White space error in absence of white spaces

### ISSUE THREAD

**Issue by rmostowy** [widdowquinn/pyani#366]
#### Summary:
I am trying to launch pyani on a set of genomes provided in the github repo
`pyani/tests/test_input/sequences`
and I keep getting the following error:
`ERROR: File or directory 'NC_002696.fna' contains whitespace
ERROR: This will cause issues with MUMmer and BLAST
ERROR: (exiting)`

#### Description:
The full command I ran is:
`average_nucleotide_identity.py -i /Users/username/Applications/pyani/tests/test_input/sequences -o /Users/username/Data/tmp-phage-ani/benchmark/aaa -m ANIb`

#### Reproducible Steps:
I installed pyani using conda by following the instructions for version 0.2

#### Expected Output:
I realise that this seems similar the issue #11 but my paths do not contain any white spaces

#### pyani Version:
`average_nucleotide_identity.py: pyani 0.2.11`

#### installed dependencies
If you are running a version of `pyani` v0.3 or later, then please run the command `pyani listdeps` at the command line, and enter the output below.

#### Python Version:
`Python 3.8.12`

#### Operating System:
MacOS 11.6.2 (20G314)

**Comment by rmostowy** [comment]
So after a while I realised that the path where I launched pyani had whitespaces, sorry!

**Comment by baileythegreen** [comment]
Hi @rmostowy!

I was just writing to you to ask for some more information. Glad you got it sorted out!
