### ISSUE TITLE
PyANI not on path after installation

### ISSUE THREAD

**Issue by dparks1134** [widdowquinn/pyani#372]
#### Summary:
I am following the instrustion to install PyANI via miniconda at:
https://pyani.readthedocs.io/en/latest/installation.html

Installation works as expected except that pyani is not on the system path. It is unclear how to gracefully resolve this issue

#### Description:
Describe the issue in detail, as clearly as possible.

#### Reproducible Steps:
Follow installation instrustion for miniconda at:
https://pyani.readthedocs.io/en/latest/installation.html

#### Current Output:
The output I get from `pyani` at the terminal is:

#### Expected Output:
Describe what you expect the output to be. It is also very useful to know the expected "correct" behavior on your systems.
```
(pyani):~$ pyani
pyani: command not found
```

#### pyani Version:
Installation was attempted on Jan. 13, 2021. This looks to be trying to install version 0.2.11.

#### Python Version:
Python 3.7 as specified in the installation instructions.

#### Operating System:
Ubuntu

**Comment by dparks1134** [comment]
OK - this looks to be a PyANI v0.2.x versus v0.3+ issue on my end. Apologies.

**Comment by widdowquinn** [comment]
No need to apologise - our documentation could (should) be much clearer!
