### ISSUE TITLE
Which coordinate in the percentage heat map drawn by pyaini is used as a reference

### ISSUE THREAD

**Issue by Reynababy** [widdowquinn/pyani#386]
Hello, I'd like to ask which coordinate in the percentage heat map drawn by pyaini is used as a reference.Thanks!

**Comment by Reynababy** [comment]
Thank you very much for your answer. One question is whether the vertical axis represents the reference genome or the horizontal axis represents the reference genome in the heat map of the results of pyani analysis? In other words, which coordinate axis is used for reference?

**Comment by baileythegreen** [comment]
Hi @Reynababy, sorry it's taken so long for us to get back to you. We were both out of the office last week.

I believe the query genomes are always along the vertical axis, though if you attempt plotting with both `matplotlib` and `seaborn`, you will see that they plot the diagonal differently, by default. The queries should be on the vertical axis either way.

I've spent a while digging through examples to make sure of this, but iI'll let @widdowquinn have the final word, if he wants, as he wrote that particular code.

**Comment by widdowquinn** [comment]
Thanks for checking this @baileythegreen - queries on the y-axis (vertical) was my expectation - and if you've checked the output, then that's what the code does ;)

**Comment by Reynababy** [comment]
@baileythegreen @widdowquinn Thank you very much for your reply. Your reply is very useful to me. Thanks very much.
