### ISSUE TITLE
ERROR: This has possibly been a NUCmer run failure, please investigate > ERROR: NoneType: None

### ISSUE THREAD

**Issue by neelam19051** [widdowquinn/pyani#393]
Hi; i am trying to run pyani and it gives this error-

```bash
average_nucleotide_identity.py -i \
/home/bvs/neelam/genome_clust/Clust_13 \
-o AND/AMR_ANIm_output -m ANIm \
-g --worker 40 --maxmatch
```
```python
WARNING: At least one NUCmer comparison failed. ANIm may fail.
WARNING: Total alignment length reported in AND/AMR_ANIm_output/nucmer_output/P_aeruginosa_E90_vs_P_aeruginosa_P9W.filter is zero!
WARNING: Total alignment length reported in AND/AMR_ANIm_output/nucmer_output/P_aeruginosa_E90_vs_P_aeruginosa_AR_458.filter is zero!
ERROR: This has possibly been a NUCmer run failure, please investigate
ERROR: NoneType: None
```

Thank you!

**Comment by widdowquinn** [comment]
Hi @neelam19051 

Thank you for using `pyani`!

The error message is asking you to check the outputs of two of your comparisons involving the E90 isolate - one against P9W and one against AR 458. `pyani` is finding that the algnment runs suggest there are no regions of similar sequence between the two genomes, in each case.

There is more than one possible reason for this.

- it may be the case that there are no similar regions in those genomes; if this is the case you may wish to change your set of input genomes to remove an uninformative comparison
- it may be that the `nucmer` comparison has failed for a technical reason; to check this, please try running the corresponding `nucmer` command (if you are using the `-l` logging, and/or the `-v` verbose output you should be able to see the set of commands that are run, and that may help you)
- it may be that there is a bug or other issue in the `pyani` code; there is not enough information to determine this, at the moment and you should first investigate the two options above, to eliminate those possibilities

I hope this is useful - please do ask further questions and report your results in this issue thread.

L.

**Comment by neelam19051** [comment]
Hi, can you please tell me how to give lable.txt and class.txt file for those genome which are not downloaded by pyani download option ..i mean i want to label ani result but i don't have this two files because i had already downloaded data.


Thank you

**Comment by widdowquinn** [comment]
> Hi, can you please tell me how to give lable.txt and class.txt file for those genome which are not downloaded by pyani download option ..i mean i want to label ani result but i don't have this two files because i had already downloaded data.

As this is a different question to the original I've moved it to a new issue: #394
