### ISSUE TITLE
How do I provide a labels.txt or classes.txt file?

### ISSUE THREAD

**Issue by widdowquinn** [widdowquinn/pyani#394]
From #393

> Hi, can you please tell me how to give lable.txt and class.txt file for those genome which are not downloaded by pyani download option ..i mean i want to label ani result but i don't have this two files because i had already downloaded data.

**Comment by widdowquinn** [comment]
The quickest way to do this is to use v0.3 and the `pyani index` command.

As you (@neelam19051) are using v0.2 you'll hae to construct your `labels.txt` and `classes.txt` files manually. Spreadsheet software like Excel or Google Sheets might be useful for you.

In v0.2, your labels file should resemble this:

```text
NC_002696	C.crescentus CB15
NC_014100	C.segnis ATCC 21756
NC_011916	C.crescentus NA1000
NC_010338	Caulobacter sp. K31
```

and the classes file this:

```text
NC_002696	C. crescentus
NC_014100	2
NC_011916	C. crescentus
NC_010338	3
```

The first column is the filestem for the sequence file, and the second column is the label or class in each case. The columns are separated by a tab character.

**Comment by neelam19051** [comment]
Hi, How to classify strain of same species for classes.txt file and how to intrepret ANI result .

**Comment by widdowquinn** [comment]
Hi @neelam19051 

> How to classify strain of same species for classes.txt file and how to intrepret ANI result? . i don't see here any link for attachment so can i mail to you?

For questions unrelated to the original topic in the header, please open a new issue.

How to classify bacteria as the same or different species is an open scientific question, and there is no single correct answer that is accepted by everyone. I have opinions on the topic, but I recommend that you start with the relevant literature for your organism, e.g.

- [Minimal standards for the description of new genera and species of rhizobia and agrobacteria](https://doi.org/10.1099/ijsem.0.003426)

or for the topic in general, e.g.

- [Proposed minimal standards for the use of genome data for the taxonomy of prokaryotes](https://doi.org/10.1099/ijsem.0.002516)
- [Improving Phylogenies Based on Average Nucleotide Identity, Incorporating Saturation Correction and Nonparametric Bootstrap Support](https://doi.org/10.1093/sysbio/syab060)

We have documentation for v0.3 describing basic interpretation of `pyani` output, and where the plots are similar to those produced by v0.2, the interpretation is the same.

- [Interpreting graphical output](https://pyani.readthedocs.io/en/latest/interpreting_plots.html)

L.
