### ISSUE TITLE
Update v2 distribution on PyPI (and bioconda)

### ISSUE THREAD

**Issue by baileythegreen** [widdowquinn/pyani#396]
This issue is to track progress on the new release of `VERSION_2`(hereinafter referred to as v2) for upload to PyPI (and bioconda). There are some questions at the end for @widdowquinn.

## Preparing a new release
Make sure that the version is ready for release. A possibly incomplete checklist for this would be:

- [x] Are the changes intended for this version complete?
- [x] Are the changes logged in `CHANGES.md`
- [x] Are new contributors logged in `CONTRIBUTORS.md`
- [x] Is the documentation up to date? (e.g. `README.md` and ReadTheDocs)
- [x] Do all the tests pass?
- [x] Is the version number updated?
- [x] Have you checked that you are ready to release a new version? (i.e. communicate the intent to release to @widdowquinn for comment)

When ready to release:

- [x] Make the release and tag

### Issues that are include in this release
• #177

### Questions related to this update
• Are there any other changes that should be included for v2? I have all of the changes that have been made to the repo branch on my local branch, but are there other things waiting for v2 that you would like to include here? (I can look through the issues, but you have worked with the legacy version more than I, so might already know.)
• Do people who report an issue, but are otherwise uninvolved in the process of resolving it get added as contributors? (E.g., the person who created issue 177.)
• For v2, I believe we're only concerned about whether the legacy tests pass. Is that correct? Or is the test suite not intended to work with v2 at all?
    • Currently, when I try to run the test suite on this branch—even if only for the legacy tests—I get errors due to a missing `nose` module. This is thrown by test files for files that do not exist in v2, even when I am not trying to run those tests.
• Should the version number be `0.2.12`, and if the file being generated by `sdist` does not have that number, can it be easily resolve? (I will look into this, but perhaps you have seen this before.)

**Comment by baileythegreen** [comment]
> 3: Upload the distribution files to pypi's test server
> `python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*`

I am unable to successfully perform the upload; I believe this is because the test server is a different server to the standard PyPI one; I have made an account, but it is not tied to the project.

**Comment by widdowquinn** [comment]
> • Do people who report an issue, but are otherwise uninvolved in the process of resolving it get added as contributors? (E.g., the person who created issue 177.)

If it's a substantial issue (e.g. a bug report) theyt should be acknowledged _via_ `all-contributors` but not in `CONTRIBUTORS.md`, as we discussed.

> • For v2, I believe we're only concerned about whether the legacy tests pass. Is that correct? Or is the test suite not intended to work with v2 at all?

The v2 test suite should pass with v2. 

> • Currently, when I try to run the test suite on this branch—even if only for the legacy tests—I get errors due to a missing `nose` module. This is thrown by test files for files that do not exist in v2, even when I am not trying to run those tests.

Please raise a corresponding issue, create the appropriate branch, fix this issue in that branch, and merge back into the `version_0_2` branch.

> Should the version number be 0.2.12, and if the file being generated by sdist does not have that number, can it be easily resolve? (I will look into this, but perhaps you have seen this before.)

Please read the [documentation for Semantic Versioning](https://semver.org/) if you have not already. This is a backwards-compatible bug fix (as I understand it) so should increment the point version. 

Which file(s) generated by `sdist` do not have the version number? More context is required to answer the query.

**Comment by widdowquinn** [comment]
> I am unable to successfully perform the upload; I believe this is because the test server is a different server to the standard PyPI one; I have made an account, but it is not tied to the project.

I would need more information - where did you make the account? Yes, `TestPyPI` is a different server to the main `PyPI` resource - please [read the corresponding documentation](https://packaging.python.org/en/latest/guides/using-testpypi/).

**Comment by baileythegreen** [comment]
> I would need more information - where did you make the account? Yes, TestPyPI is a different server to the main PyPI resource - please [read the corresponding documentation](https://packaging.python.org/en/latest/guides/using-testpypi/).

I made the account on https://test.pypi.org/. This is in addition to the account I already had for PyPI.

I am not a maintainer of the project on the TestPyPI server.

```bash
python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/pyani-0.2.12* --verbose
Uploading distributions to https://test.pypi.org/legacy/
INFO     dist/pyani-0.2.12-py3-none-any.whl (58.4 KB)                           
INFO     dist/pyani-0.2.12.tar.gz (291.5 KB)                                    
INFO     Querying keyring for username                                          
Enter your username: baileythegreen
INFO     Querying keyring for password                                          
Enter your password: 
INFO     username: baileythegreen                                               
INFO     password: <hidden>                                                     
Uploading pyani-0.2.12-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.2/84.2 kB • 00:00 • 30.4 MB/s
INFO     Response from https://test.pypi.org/legacy/:                           
         403 The user 'baileythegreen' isn't allowed to upload to project       
         'pyani'. See https://test.pypi.org/help/#project-name for more         
         information.                                                           
INFO 
```

```html
<html>                                                                 
          <head>                                                                
              <title>403 The user 'baileythegreen' isn't allowed to upload to      
                  project 'pyani'. See https://test.pypi.org/help/#project-name for more 
                  information.
              </title>                                                   
          </head>                                                               
          <body>                                                                
               <h1>403 The user 'baileythegreen' isn't allowed to upload to project 
                 'pyani'. See https://test.pypi.org/help/#project-name for more         
                 information.
                </h1>                                                      
          Access was denied to this resource.<br/><br/>                        
          The user &#x27;baileythegreen&#x27; isn&#x27;t allowed to upload to    
          project &#x27;pyani&#x27;. See https://test.pypi.org/help/#project-name
          for more information.                                                                                                                                  
          </body>                                                               
</html>           
```

**Comment by baileythegreen** [comment]
> The v2 test suite should pass with v2.

> Please raise a corresponding issue, create the appropriate branch, fix this issue in that branch, and merge back into the version_0_2 branch.

I was mistaken about the tests for v2, and also the reason for the tests failing. It turned out `nose` was missing from my virtual environment because the contents of the `test_requirements.txt` file from the `version_0_2` branch had not been installed. Once I solved that, all tests pass.

> Which file(s) generated by sdist do not have the version number? More context is required to answer the query.

`sdist` only produces one file, the `.tar.gz`, which had the incorrect (old) version number in the name.  I didn't know where the version number was being pulled from, originally; I have since traced it to the `pyani/__init__.py` file, in which it is hard-coded.

**Comment by baileythegreen** [comment]
> I made the account on https://test.pypi.org/. This is in addition to the account I already had for PyPI.
> I am not a maintainer of the project on the TestPyPI server.

@widdowquinn, I seem to have missed an invitation being sent that would have allowed me to upload the release and finish following the steps outlined in the relevant Discussion. The invitation expired after a short period of time, so can you resend it?

**Comment by baileythegreen** [comment]
the release is up on PyPI. Theoretically, it will be picked up by bioconda soon—though I don't know how frequently it checks for things.

**Comment by baileythegreen** [comment]
Got the tag pushed to GitHub, made the release, and it now appears on `conda`. I think that's everything, so I'm closing this.
