### ISSUE TITLE
Updating `Contributors.md`

### ISSUE THREAD

**Issue by baileythegreen** [widdowquinn/pyani#400]
This file is fairly out-of-date. Given the desire to acknowledge several kinds of contributions with the `all-contributors` bot, the file needs to be expanded.

The `all-contributors` bot normally adds each person in an individual PR, so for the purposes of this issue, to avoid lots of very tiny, nearly identical, PRs, I will attempt to add people manually in one branch—[`add_contributors`](https://github.com/widdowquinn/pyani/tree/add_contributors), based on previous `all-contributors` additions to the repo.

**Comment by baileythegreen** [comment]
Currently all issues after Issue 200 have been looked at for missing contributors, and people added in to `.all-contributorsrc`.

**Comment by widdowquinn** [comment]
> This file is fairly out-of-date.

Do you mean `CONTRIBUTORS.md` is out of date?

> Given the desire to acknowledge several kinds of contributions with the `all-contributors` bot, the file needs to be expanded.

As we discussed, `CONTRIBUTORS.md` should include only those with commits in the codebase/documentation. `all-contributors` provides recognition for other types of contribution, in addition to this.

**Comment by baileythegreen** [comment]
>> This file is fairly out-of-date.

> Do you mean `CONTRIBUTORS.md` is out of date?

Yes. For instance, it did not list me. It now includes everyone who has had a commit/PR merged into the codebase; however, it also includes Will Trimble and Ram Krishna Shrestha, who both submitted PRs that were not merged. Is it correct that they should be listed in `CONTRIBUTORS.md`, even so? I ask because they were included in this file before I modified it.
