### ISSUE TITLE
Problem with EASY-INSTALL-ENTRY-SCRIPT for miniconda

### ISSUE THREAD

**Issue by baileythegreen** [widdowquinn/pyani#403]
#### Summary:
`pyani` is not running locally; no matter what I try to do.

#### Description:
Describe the issue in detail, as clearly as possible.

```bash
pyani
pyani -h
pyani anim -i scratch/small_test_genomes/ -o scratch/debugging -v -l scratch/debugging/debugging.log
```

et cetera, all fail with:

```python
! pyani
Traceback (most recent call last):
  File "/Users/baileythegreen/Software/miniconda3/bin/pyani", line 33, in <module>
    sys.exit(load_entry_point('pyani', 'console_scripts', 'pyani')())
  File "/Users/baileythegreen/Software/miniconda3/bin/pyani", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

This is new behaviour; I am unaware of what might have changed. Researching the problem online led me to this: https://stackoverflow.com/questions/62579080/issue-with-loading-entry-point-possibly-connected-to-version-including-dev-tag, which advocates fixes like creating a new `conda` environment and reinstalling.  I did this following the instructions in the `pyani` `Readme.md`:

```bash
conda create --name pyani_env python=3.8 -y
conda activate pyani_env
conda install pyani
```

and I still get the same error.

I do not fully understand the purpose or syntax of the `/Users/baileythegreen/Software/miniconda3/bin/pyani` file, so as of yet, I have not been able to determine if some other work-around might solve the problem.

I am also not sure if this is a general problem; a local one; or even branch-specific as I will need to stash some unrelated things before I can try another branch.

#### Reproducible Steps:
I discovered this when I was trying to determine why a test was failing by running `pyani anim`.

#### Current Output:
```python
! pyani
Traceback (most recent call last):
  File "/Users/baileythegreen/Software/miniconda3/bin/pyani", line 33, in <module>
    sys.exit(load_entry_point('pyani', 'console_scripts', 'pyani')())
  File "/Users/baileythegreen/Software/miniconda3/bin/pyani", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

#### Expected Output:
Describe what you expect the output to be. It is also very useful to know the expected "correct" behavior on your systems.

#### pyani Version:
bleeding edge

#### installed dependencies
This will not run.

#### Python Version:
Python 3.8

#### Operating System:
macOS High Sierra

**Comment by widdowquinn** [comment]
There are some clues in your issue report:

- The "bleeding edge" version of `pyani` is not the one installed using `conda`. `conda` installs v2.11.0
- The command used to run `pyani` v2.x is `average_nucleotide_identity.py`
- You are using the `pyani` v3.x command `pyani` to check your tests

The `pyani` executable in your `$PATH` is at `/Users/baileythegreen/Software/miniconda3/bin/pyani` whose path suggests that this executable is in the base environment for `miniconda`, not your `pyani_env` environment. As `pyani` is not an executable provided with v0.2, it looks as though your shell may be attempting to run an executable from the base environment that which points to code that is not available in your environment.

I would suggest:

1. Uninstalling `pyani` from the base environment to avoid future confusion
2. Using the `average_nuclotide_identity.py` command to run `pyani` v2.x

This may solve the immediate problem of getting `pyani` v2.x to run.

However, if you are aiming to test features in `pyani` v3.x you should clone the repository and use one of the usual installation methods (`make setup_env`, `pip install -e .`, `python setup.py` - as appropriate).
