### ISSUE TITLE
pyani: command not found

### ISSUE THREAD

**Issue by Gahyeon-K** [widdowquinn/pyani#406]
#### Summary:
I installed 'latest (master)' pyani package following instructions (https://pyani.readthedocs.io/en/latest/installation.html) using conda, pip, and source (source code from v0.2.11/ https://github.com/widdowquinn/pyani/archive/refs/tags/v0.2.11.tar.gz). But, the output was 'pyani: command not found', but 'average_nucleotide_identity.py: pyani 0.2.11'.
So, Are there any issues in the compatibility of conda or python with pyani? 
I tried python versions 3.7, 3.8, and 3.10. Conda version is 4.13.0
I'll  really appreciate for your solutions.
Thanks!

**Comment by widdowquinn** [comment]
Hi @Gahyeon-K 

As noted in #165 there are two versions of `pyani`. The command for v0.2, which is installed through pip/conda, is `average_nucleotide_identity.py`; the command for v0.3 is `pyani` (and the CLI is quite different). You have installed v0.2 so should use the instructions appropriate to that version: https://github.com/widdowquinn/pyani/blob/version_0_2/README.md

If you want to use v0.3, then please follow the instructions at https://github.com/widdowquinn/pyani#installation instead.

Many thanks,

L.
