### ISSUE TITLE
`pyani` command not found

### ISSUE THREAD

**Issue by friedsh2** [widdowquinn/pyani#412]
#### Summary:
Can't seem to install pyani v0.3+ despite following the v0.3+ documentation

#### Description:
Despite following the installation instructions from the README (https://github.com/widdowquinn/pyani#conda), the pyani command is still not working. `average_nucleotide_identity.py` and `genbank_get_genomes_by_taxon.py` works.

#### Reproducible Steps:
The instructions from the README were followed to a tee.

#### Current Output:
`pyani: command not found`

#### Expected Output:
Would expect the `pyani` command to work

#### pyani Version:
0.2.12

#### Python Version:
3.8

#### Operating System:
Ubuntu 20.04 LTS on WSL

**Comment by widdowquinn** [comment]
Hi @friedsh2 

Thank you for your interest in `pyani`. You appear to have installed `pyani` v0.2, rather than v0.3. If you would like to install v0.3, you should clone the repository and install from there using, e.g. `python setup.py install`.


L.

**Comment by friedsh2** [comment]
Thanks for the quick reply. I am now facing another error upon running the `pyani` command. 

Error output:
`Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pyani_env/bin/pyani", line 33, in <module>
    sys.exit(load_entry_point('pyani==0.3.0a0', 'console_scripts', 'pyani')())
  File "/home/user/miniconda3/envs/pyani_env/bin/pyani", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration`

I installed v0.3 using `python setup.py install` in the cloned repository.
