### ISSUE TITLE
Cannot run anim in pyani 0.3.0-alpha using provided data, on macosx 12.6, nucmer fails.

### ISSUE THREAD

**Issue by joneson** [widdowquinn/pyani#413]
#### Summary:
Cannot run anim in pyani 0.3.0-alpha using provided data, on macosx 12.6, nucmer fails.

#### Description:
Using pyani 0.3.0-alpha with the provided sample commands and data retrieved using pyani download. pyani is not able to use the data downloaded as is as it doesn't write file names with the expected extension genomic.fna.md5. After changing hash files to include the expected file name, pyani anim fails with nucmer fail. Using python 3.7.12 and MUMMer nucmer version: Darwin_4.0.0beta2.

#### Reproducible Steps 1:
pyani download -o C_blochmannia --email joneson@uwm.edu -t 203804 -v -l C_blochmannia_dl.log

This works except for the following:

 [INFO] [pyani.scripts.subcommands.subcmd_download]: Retrieving URLs for GCF_000185985.1_ASM18598v1
[WARNING] [pyani.download]: RefSeq download failed: skipping!
[WARNING] [pyani.scripts.subcommands.subcmd_download]: RefSeq failed. Trying GenBank alternative assembly
[WARNING] [pyani.download]: GenBank download failed: skipping!
[WARNING] [pyani.scripts.subcommands.subcmd_download]: GenBank failed.
...
[WARNING] [pyani.scripts.subcommands.subcmd_download]: 2 genome downloads were skipped
[WARNING] [pyani.scripts.subcommands.subcmd_download]: Candidatus Blochmannia vafer BVAF:
	taxon id: 203804
	accession: 275848
	URL: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/185/985/GCF_000185985.1_ASM18598v1/GCF_000185985.1_ASM18598v1_genomic.fna.gz
	source: RefSeq
[WARNING] [pyani.scripts.subcommands.subcmd_download]: Candidatus Blochmannia vafer BVAF:
	taxon id: 203804
	accession: 275848
	URL: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/185/985/GCA_000185985.1_ASM18598v1/GCA_000185985.1_ASM18598v1_genomic.fna.gz
	source: GenBank

#### Reproducible Steps 2:
pyani createdb -v -l C_blochmannia_createdb.log

This does not cause errors

#### Reproducible Steps 3:
pyani anim -i C_blochmannia -o C_blochmannia_ANIm -v -l C_blochmannia_ANIm.log --name "C. blochmannia run 1" --labels C_blochmannia/labels.txt --classes C_blochmannia/classes.txt

Causes the following errors
[INFO] [pyani.scripts.pyani_script]: Checking for database file: .pyani/pyanidb
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Running ANIm analysis
[INFO] [pyani.scripts.subcommands.subcmd_anim]: MUMMer nucmer version: Darwin_4.0.0beta2 (/Users/joneson/miniconda3/envs/pyani/bin/nucmer)
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Analysis name: C. blochmannia run 1
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_000011745.1_ASM1174v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_000011745.1_ASM1174v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_000011745.1_ASM1174v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_000043285.1_ASM4328v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_000043285.1_ASM4328v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_000043285.1_ASM4328v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_000185985.2_ASM18598v2_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_000185985.2_ASM18598v2_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_000185985.2_ASM18598v2_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_000331065.1_ASM33106v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_000331065.1_ASM33106v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_000331065.1_ASM33106v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_000973505.1_ASM97350v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_000973505.1_ASM97350v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_000973505.1_ASM97350v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_000973545.1_ASM97354v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_000973545.1_ASM97354v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_000973545.1_ASM97354v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_009827135.1_ASM982713v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_009827135.1_ASM982713v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_009827135.1_ASM982713v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_014857065.1_ASM1485706v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_014857065.1_ASM1485706v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_014857065.1_ASM1485706v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023016305.1_ASM2301630v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023016305.1_ASM2301630v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023016305.1_ASM2301630v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585685.1_ASM2358568v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023585685.1_ASM2358568v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023585685.1_ASM2358568v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585705.1_ASM2358570v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023585705.1_ASM2358570v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023585705.1_ASM2358570v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585725.1_ASM2358572v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023585725.1_ASM2358572v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023585725.1_ASM2358572v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585745.1_ASM2358574v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023585745.1_ASM2358574v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023585745.1_ASM2358574v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585765.1_ASM2358576v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023585765.1_ASM2358576v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023585765.1_ASM2358576v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585785.1_ASM2358578v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023585785.1_ASM2358578v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023585785.1_ASM2358578v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585805.1_ASM2358580v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023585805.1_ASM2358580v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023585805.1_ASM2358580v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585825.1_ASM2358582v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023585825.1_ASM2358582v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023585825.1_ASM2358582v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585845.1_ASM2358584v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023585845.1_ASM2358584v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023585845.1_ASM2358584v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585865.1_ASM2358586v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023585865.1_ASM2358586v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023585865.1_ASM2358586v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585885.1_ASM2358588v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023585885.1_ASM2358588v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023585885.1_ASM2358588v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585905.1_ASM2358590v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023585905.1_ASM2358590v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023585905.1_ASM2358590v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585925.1_ASM2358592v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023585925.1_ASM2358592v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023585925.1_ASM2358592v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023586085.1_ASM2358608v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023586085.1_ASM2358608v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023586085.1_ASM2358608v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023586245.1_ASM2358624v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023586245.1_ASM2358624v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023586245.1_ASM2358624v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023586365.1_ASM2358636v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023586365.1_ASM2358636v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023586365.1_ASM2358636v1_genomic.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023586525.1_ASM2358652v1_genomic.fna.md5.
[WARNING] [pyani.pyani_files]: Hashfile C_blochmannia/GCF_023586525.1_ASM2358652v1_genomic.fna.md5 does not exist...
[WARNING] [pyani.pyani_files]: ... trying C_blochmannia/GCF_023586525.1_ASM2358652v1_genomic.md5.
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Generating ANIm command-lines
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Compiling genomes for comparison
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Compiling pairwise comparisons (this can take time for large datasets)...
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 26/26 [00:00<00:00, 234016.96it/s]
[INFO] [pyani.scripts.subcommands.subcmd_anim]: 	...total pairwise comparisons to be performed: 325
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Checking database for existing comparison data...
[INFO] [pyani.scripts.subcommands.subcmd_anim]: 	...after check, still need to run 325 comparisons
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Creating NUCmer jobs for ANIm
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 325/325 [00:00<00:00, 5634.36it/s]
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Results not found for 325 comparisons; 325 new jobs built.
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Running jobs with multiprocessing
[ERROR] [pyani.scripts.subcommands.subcmd_anim]: At least one NUCmer comparison failed. Please investigate (exiting)
Traceback (most recent call last):
  File "/Users/joneson/miniconda3/bin/pyani", line 33, in <module>
    sys.exit(load_entry_point('pyani', 'console_scripts', 'pyani')())
  File "/usr/local/bin/pyani-master/pyani/scripts/pyani_script.py", line 143, in run_main
    returnval = args.func(args)
  File "/usr/local/bin/pyani-master/pyani/scripts/subcommands/subcmd_anim.py", line 301, in subcmd_anim
    run_anim_jobs(joblist, args)
  File "/usr/local/bin/pyani-master/pyani/scripts/subcommands/subcmd_anim.py", line 400, in run_anim_jobs
    raise PyaniException("Multiprocessing run failed in ANIm")
pyani.PyaniException: Multiprocessing run failed in ANIm

#### Reproducible Steps 4:
The above errors show that pyani cannot find the hash files ending with "genomic.fna.md5". The hash files that were created using pyani createdb were instead called "genomic.md5". If I go in and rename all of the hash files to include "genomic.fna.md5" and remake the .pyani/pyanidb using the updated names and then rerun the following:

pyani anim -i C_blochmannia -o C_blochmannia_ANIm -v -l C_blochmannia_ANIm.log --name "C. blochmannia run 1" --labels C_blochmannia/labels.txt --classes C_blochmannia/classes.txt

Then I get the error output, below.

#### Current Output:
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Running ANIm analysis
[INFO] [pyani.scripts.subcommands.subcmd_anim]: MUMMer nucmer version: Darwin_4.0.0beta2 (/Users/joneson/miniconda3/envs/pyani/bin/nucmer)
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Analysis name: C. blochmannia run 1
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_000011745.1_ASM1174v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_000043285.1_ASM4328v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_000185985.2_ASM18598v2_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_000331065.1_ASM33106v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_000973505.1_ASM97350v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_000973545.1_ASM97354v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_009827135.1_ASM982713v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_014857065.1_ASM1485706v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023016305.1_ASM2301630v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585685.1_ASM2358568v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585705.1_ASM2358570v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585725.1_ASM2358572v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585745.1_ASM2358574v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585765.1_ASM2358576v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585785.1_ASM2358578v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585805.1_ASM2358580v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585825.1_ASM2358582v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585845.1_ASM2358584v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585865.1_ASM2358586v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585885.1_ASM2358588v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585905.1_ASM2358590v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023585925.1_ASM2358592v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023586085.1_ASM2358608v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023586245.1_ASM2358624v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023586365.1_ASM2358636v1_genomic.fna.md5.
[INFO] [pyani.pyani_files]: Checking for hashfile: C_blochmannia/GCF_023586525.1_ASM2358652v1_genomic.fna.md5.
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Generating ANIm command-lines
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Compiling genomes for comparison
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Compiling pairwise comparisons (this can take time for large datasets)...
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 26/26 [00:00<00:00, 454382.93it/s]
[INFO] [pyani.scripts.subcommands.subcmd_anim]: 	...total pairwise comparisons to be performed: 325
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Checking database for existing comparison data...
[INFO] [pyani.scripts.subcommands.subcmd_anim]: 	...after check, still need to run 325 comparisons
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Creating NUCmer jobs for ANIm
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 325/325 [00:00<00:00, 6746.09it/s]
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Results not found for 325 comparisons; 325 new jobs built.
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Running jobs with multiprocessing
[ERROR] [pyani.scripts.subcommands.subcmd_anim]: At least one NUCmer comparison failed. Please investigate (exiting)
Traceback (most recent call last):
  File "/Users/joneson/miniconda3/bin/pyani", line 33, in <module>
    sys.exit(load_entry_point('pyani', 'console_scripts', 'pyani')())
  File "/usr/local/bin/pyani-master/pyani/scripts/pyani_script.py", line 143, in run_main
    returnval = args.func(args)
  File "/usr/local/bin/pyani-master/pyani/scripts/subcommands/subcmd_anim.py", line 301, in subcmd_anim
    run_anim_jobs(joblist, args)
  File "/usr/local/bin/pyani-master/pyani/scripts/subcommands/subcmd_anim.py", line 400, in run_anim_jobs
    raise PyaniException("Multiprocessing run failed in ANIm")
pyani.PyaniException: Multiprocessing run failed in ANIm

#### pyani Version:
pyani version: 0.3.0-alpha

#### installed dependencies
System information
	Platorm==Darwin-21.6.0-x86_64-i386-64bit
	Python==3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:57:50) 
[Clang 11.1.0 ]
Installed pyani Python dependendencies...
	Pillow==Not Installed (-)
	biopython==1.76 (/Users/joneson/miniconda3/lib/python3.7/site-packages)
	matplotlib==3.2.0 (/Users/joneson/miniconda3/lib/python3.7/site-packages)
	namedlist==1.8 (/Users/joneson/miniconda3/lib/python3.7/site-packages)
	networkx==2.6.3 (/Users/joneson/miniconda3/lib/python3.7/site-packages)
	numpy==1.18.1 (/Users/joneson/miniconda3/lib/python3.7/site-packages)
	openpyxl==Not Installed (-)
	pandas==1.0.1 (/Users/joneson/miniconda3/lib/python3.7/site-packages)
	scipy==1.4.1 (/Users/joneson/miniconda3/lib/python3.7/site-packages)
	seaborn==0.10.0 (/Users/joneson/miniconda3/lib/python3.7/site-packages)
	sqlalchemy==1.4.45 (/Users/joneson/miniconda3/lib/python3.7/site-packages)
	tqdm==4.64.1 (/Users/joneson/miniconda3/lib/python3.7/site-packages)
Installed pyani development dependendencies...
	bandit==Not Installed (-)
	black==Not Installed (-)
	codecov==Not Installed (-)
	coverage==Not Installed (-)
	doc8==Not Installed (-)
	flake8==Not Installed (-)
	jinja2==Not Installed (-)
	mypy==Not Installed (-)
	pydocstyle==Not Installed (-)
	pylint==Not Installed (-)
	pytest==Not Installed (-)
	pytest-cov==Not Installed (-)
	sphinx==Not Installed (-)
Installed pyani pip-install dependendencies...
	pre-commit==Not Installed (-)
	pytest-ordering==Not Installed (-)
	sphinx-rtd-theme==Not Installed (-)
Installed third-party tool versions...
	blast+==Darwin_2.9.0+ (/Users/joneson/miniconda3/envs/pyani/bin/blastn)
	nucmer==Darwin_4.0.0beta2 (/Users/joneson/miniconda3/envs/pyani/bin/nucmer)
	blastall==Darwin_2.2.26 (/Users/joneson/miniconda3/envs/pyani/bin/blastall)
	fastani==Darwin_1.33 (/Users/joneson/miniconda3/envs/pyani/bin/fastANI)

#### Python Version:
python                    3.7.12
using within pyani environment

#### Operating System:
macosx 12.6

conda list -n pyani
packages in environment at /Users/joneson/miniconda3/envs/pyani:
Name                    Version                   Build  Channel
biopython                 1.78             py37h9ed2024_0  
blast                     2.9.0                h58d6d27_1    bioconda
blast-legacy              2.2.26               h527b516_3    bioconda
boost                     1.68.0          py37h9888f84_1001    conda-forge
boost-cpp                 1.68.0            h6f8c590_1000    conda-forge
bottleneck                1.3.5            py37h4de8ad1_0    conda-forge
brotlipy                  0.7.0           py37h69ee0a8_1004    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2022.12.7            h033912b_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py37h7346b73_1    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     4.14.0           py37hf985489_0    conda-forge
conda-package-handling    1.9.0            py37h8052db5_0    conda-forge
cryptography              38.0.1           py37hf6deb26_0  
curl                      7.86.0               h581aaea_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
entrez-direct             16.2                 h193322a_1    bioconda
fastani                   1.33                 h0a26cfa_1    bioconda
freetype                  2.12.1               h3f81eb7_1    conda-forge
gettext                   0.21.1               h8a4c099_0    conda-forge
gmp                       6.2.1                h2e338ed_0    conda-forge
gnutls                    3.6.13               hc269f14_0    conda-forge
gsl                       2.7                  h93259b0_0    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
jpeg                      9e                   hac89ed1_2    conda-forge
kiwisolver                1.4.4            py37h229a17a_0    conda-forge
krb5                      1.19.3               hb98e516_0    conda-forge
lcms2                     2.14                 h90f4b2a_0    conda-forge
lerc                      4.0.0                hb486fe8_0    conda-forge
libblas                   3.9.0           16_osx64_openblas    conda-forge
libcblas                  3.9.0           16_osx64_openblas    conda-forge
libcurl                   7.86.0               h581aaea_1    conda-forge
libcxx                    14.0.6               hccf4f1f_0    conda-forge
libdeflate                1.14                 hb7f2c08_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           9_5_0_h97931a8_26    conda-forge
libgfortran5              11.3.0              h082f757_26    conda-forge
libiconv                  1.17                 hac89ed1_0    conda-forge
libidn2                   2.3.4                hb7f2c08_0    conda-forge
liblapack                 3.9.0           16_osx64_openblas    conda-forge
libnghttp2                1.47.0               h5aae05b_1    conda-forge
libopenblas               0.3.21               h54e7dc3_0  
libpng                    1.6.39               ha978bb4_0    conda-forge
libsqlite                 3.40.0               ha978bb4_0    conda-forge
libssh2                   1.10.0               h47af595_3    conda-forge
libtiff                   4.4.0                hdb44e8a_4    conda-forge
libunistring              0.9.10               h0d85af4_0    conda-forge
libwebp-base              1.2.4                h775f41a_0    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libzlib                   1.2.13               hfd90126_4    conda-forge
llvm-openmp               8.0.1                h770b8ee_0    conda-forge
matplotlib-base           3.4.3            py37h3147e9e_2    conda-forge
mummer                    3.23                h589c0e0_12    bioconda
ncurses                   6.3                  h96cf925_1    conda-forge
nettle                    3.4.1             h3efe00b_1002    conda-forge
numexpr                   2.8.3            py37h233bc55_0    conda-forge
numpy                     1.21.6           py37h345d48f_0    conda-forge
openjpeg                  2.5.0                h5d0d7b0_1    conda-forge
openmp                    8.0.1                         0    conda-forge
openssl                   3.0.7                hfd90126_1    conda-forge
packaging                 22.0               pyhd8ed1ab_0    conda-forge
pandas                    1.3.5            py37h743cdd8_0  
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
perl                      5.32.1          2_h0d85af4_perl5    conda-forge
perl-archive-tar          2.40            pl5321hdfd78af_0    bioconda
perl-carp                 1.50            pl5321hd8ed1ab_0    conda-forge
perl-common-sense         3.75            pl5321hd8ed1ab_0    conda-forge
perl-compress-raw-bzip2   2.201           pl5321h775f41a_0    conda-forge
perl-compress-raw-zlib    2.202           pl5321h775f41a_0    conda-forge
perl-encode               3.19            pl5321hb7f2c08_0    conda-forge
perl-exporter             5.74            pl5321hd8ed1ab_0    conda-forge
perl-exporter-tiny        1.002002        pl5321hd8ed1ab_0    conda-forge
perl-extutils-makemaker   7.64            pl5321hd8ed1ab_0    conda-forge
perl-io-compress          2.201           pl5321h9722bc1_0    bioconda
perl-io-zlib              1.11            pl5321hdfd78af_0    bioconda
perl-json                 4.10            pl5321hdfd78af_0    bioconda
perl-json-xs              2.34            pl5321hcd10b59_5    bioconda
perl-list-moreutils       0.430           pl5321hdfd78af_0    bioconda
perl-list-moreutils-xs    0.430           pl5321ha5712d3_1    bioconda
perl-parent               0.239           pl5321hd8ed1ab_0    conda-forge
perl-pathtools            3.75            pl5321h775f41a_0    conda-forge
perl-scalar-list-utils    1.63            pl5321h775f41a_0    conda-forge
perl-storable             3.15            pl5321h775f41a_0    conda-forge
perl-types-serialiser     1.01            pl5321hdfd78af_0    bioconda
pillow                    9.2.0            py37ha6ba2b9_2    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
pyani                     0.2.12             pyhdfd78af_0    bioconda
pycosat                   0.6.4            py37h8052db5_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py37hf985489_5    conda-forge
python                    3.7.12          hf3644f1_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.7                     3_cp37m    conda-forge
pytz                      2022.6             pyhd8ed1ab_0    conda-forge
readline                  8.1.2                h3899abd_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
ruamel_yaml               0.15.80         py37h994c40b_1007    conda-forge
scipy                     1.7.3            py37h4e3cf02_0    conda-forge
seaborn                   0.10.1                     py_0    conda-forge
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.40.0               h9ae0607_0    conda-forge
statsmodels               0.9.0           py37h917ab60_1000    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py37h994c40b_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
urllib3                   1.26.13            pyhd8ed1ab_0    conda-forge
wget                      1.20.3               hd3787cc_1    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
zlib                      1.2.13               hfd90126_4    conda-forge
zstd                      1.5.2                hfa58983_4    conda-forge

**Comment by joneson** [comment]
Great! Thank-you much. Downgrading mummer got me through "pyani anim" as expected. After this I wasn't able to run "pyani report" for either --formats html or excel until after I installed jinja2 and openpyxl in the environment, and then re-installing pyani.  After that I am able to get through the First Analysis with expected results.

**Comment by liamfriar** [comment]
Hi. I just want to confirm that I had the same problem and the downgrade also appears to have fixed it. I am running v 0.2.x via a conda install. So, this might also be the solution to this old issue https://github.com/widdowquinn/pyani/issues/93 .

**Comment by widdowquinn** [comment]
Thanks for the info @liamfriar  - i'm a little reluctant to pin a `mummer` version, in case of updates, but I should make a FAQ page or something in the docs.

Cheers,

L.
