### ISSUE TITLE
Error "Cannot update because the update target is missing these hooks" when trying to use autoupdate on my repo

### ISSUE THREAD

**Issue by dmentock** [widdowquinn/pyani#414]
#### Summary:

I created a new repo [here](https://github.com/dmentock/fep_hook) and tried to use it with another repo. I created a `.pre-commit-config.yaml` file that looks as following:

```
repos:
-   repo: https://github.com/dmentock/fep_hook
    rev: v0.1
    hooks:
    -   id: line-length-checker
```

Using this locally with 

`pre-commit try-repo fep_hook line-length-checker --verbose --all-files`

works fine and allows me to test the functionality of `line-length-checker`. However, trying to access it remotely by issuing `pre-commit autoupdate` results in the error message 

```
Updating https://github.com/dmentock/fep_hook ... Cannot update because the update target is missing these hooks:
line-length-checker
```

I tried adopting the structure from the main pre-commit hook repo, but as opposed to this one for some reason I am unable to integrate my fep8 repo into my testrepo.
What am I still missing in my configuration?

**Comment by widdowquinn** [comment]
Hi @dmentock - I'm not sure what's wrong with your configuration, and this is really a question for the `pre-commit` issue tracker, rather than `pyani`, so I'm going to close this for now.

L.
