### ISSUE TITLE
sending some love for this script: " genbank_get_genomes_by_taxon.py"

### ISSUE THREAD

**Issue by peterthorpe5** [widdowquinn/pyani#415]
This is not an issue - just saying, this script is awesome and saves loads of time! Thanks Leighton. 

Pete

**Comment by stevebaeyen** [comment]
Totally agree !

**Comment by widdowquinn** [comment]
I'm blushing! Thank you both!

The `download` option in `pyani` v0.3 might be a very slight improvement, but if this script works and is in your pipelines then there's not a huge amount of difference and no need for disruption.

In the interests of fairness, Kai Blin's download tool is pretty awesome, too ;)
