### ISSUE TITLE
Pyani not installing through conda

### ISSUE THREAD

**Issue by conmeehan** [widdowquinn/pyani#419]
#### Summary:
When using conda to install the package, everything says it installs correctly but the pyani executable just isn't there. 

#### Description:
Installation instructions followed as per github (environment then install) but used mamba instead. 
When I type 'pyani' on the command line, it just says command not found.

I also tried with pip3 and it didn't work for some reason.

#### Reproducible Steps:
mamba create --name pyani_env python=3.8 -y
mamba activate pyani_env
mamba install pyani
pyani

#### Current Output:
N/A

#### Python Version:
3.8 inside the conda environment

#### Operating System:
OSX and Ubuntu (tried separately)

**Comment by widdowquinn** [comment]
Thanks for the report, Conor - this is an outstanding issue re: the landing page documentation. Many apologies that it's (still) not yet fixed and/or clear.

`conda` installs pyani v0.2; the `pyani <command>` syntax is new to pyani v0.3/development. For the `conda`-installed version, you'll need to follow this documentation: https://github.com/widdowquinn/pyani/blob/master/README_v_0_2_x.md

I hope that helps get things moving.

Cheers,

L.

**Comment by conmeehan** [comment]
Hi,

Yes that clears it up a bit. That means that to use pyani the conda doesn't work at all? I have to install from source?


C

**Comment by widdowquinn** [comment]
Sadly, yes. The `average_nucleotide_identity.py` script runs with teh `conda` installation, but the `pyani <XXXX>` form does not.

**Comment by conmeehan** [comment]
Ok no worries, I can work with that. Thanks!

C

**Comment by widdowquinn** [comment]
Only closing because it's an idle issue - please do reopen if you need to.
