### ISSUE TITLE
AttributeError: module 'matplotlib.pyplot' has no attribute 'register_cmap'

### ISSUE THREAD

**Issue by despathe** [widdowquinn/pyani#431]
#### Summary:
Attribute error whenever I am trying to use **_average_nucleotide_identity.py_** command, having downloaded pyani v0.2

#### Description:
I have downloaded pyani v0.2, and had to download biopython and matplotlib (most updated versions) separately because when using the conda install pyani script, I would be getting lots of errors because biopython and matplotlib could not be downloaded as packages through pyani. 

Now, I have downloaded my desired taxon genomes using the _**genbank_get_genomes_by_taxon.py**_ . However, every time I am trying to use **_average_nucleotide_identity.py_** I get this error 

**_Traceback (most recent call last):
  File "/home/desvathen/miniconda3/envs/bioenv/bin/average_nucleotide_identity.py", line 168, in <module>
    from pyani import (
  File "/home/desvathen/miniconda3/envs/bioenv/lib/python3.12/site-packages/pyani/pyani_graphics.py", line 70, in <module>
    plt.register_cmap(cmap=pyani_config.CMAP_SPBND_BURD)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'matplotlib.pyplot' has no attribute 'register_cmap'_**

This has also happened simply when using : **_average_nucleotide_identity.py -h_**

#### Reproducible Steps:
~$ average_nucleotide_identity.py -h
Traceback (most recent call last):
  File "/home/desvathen/miniconda3/envs/bioenv/bin/average_nucleotide_identity.py", line 168, in <module>
    from pyani import (
  File "/home/desvathen/miniconda3/envs/bioenv/lib/python3.12/site-packages/pyani/pyani_graphics.py", line 70, in <module>
    plt.register_cmap(cmap=pyani_config.CMAP_SPBND_BURD)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'matplotlib.pyplot' has no attribute 'register_cmap'

I am completely new to Python, and have just started learning about channels and packages and environments, been trying to figure my way around this for the first time, so any input would be appreciated. 

#### Current Output:
The output you get from `pyani` or at the terminal, with this issue. It is very useful to know the current "wrong" behavior on your system.

#### Expected Output:
Describe what you expect the output to be. It is also very useful to know the expected "correct" behavior on your systems.

#### installed dependencies
If you are running a version of `pyani` v0.3 or later, then please run the command `pyani listdeps` at the command line, and enter the output below.

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.12               h4ab18f5_0    conda-forge
biopython                 1.84            py312h9a8786e_0    conda-forge
blast                     2.5.0                hc0b0e79_3    bioconda
blast-legacy              2.2.26               h9ee0642_3    bioconda
boost                     1.85.0               h9cebb41_4    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
cairo                     1.18.0               hebfffa5_3    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1           py312h8572e83_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
double-conversion         3.3.0                h59595ed_0    conda-forge
expat                     2.6.2                h59595ed_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.1          py312h41a817b_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
harfbuzz                  9.0.0                hda332d3_1    conda-forge
icu                       75.1                 he02047a_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py312h8572e83_1    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           23_linux64_openblas    conda-forge
libboost                  1.85.0               h0ccab89_4    conda-forge
libboost-devel            1.85.0               h00ab1b0_4    conda-forge
libboost-headers          1.85.0               ha770c72_4    conda-forge
libboost-python           1.85.0          py312hf74af30_4    conda-forge
libboost-python-devel     1.85.0          py312h9cebb41_4    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           23_linux64_openblas    conda-forge
libclang-cpp18.1          18.1.8          default_hf981a13_1    conda-forge
libclang13                18.1.8          default_h9def88c_1    conda-forge
libcups                   2.3.3                h4637d8d_4    conda-forge
libdeflate                1.21                 h4bc722e_0    conda-forge
libdrm                    2.4.122              h4ab18f5_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgfortran-ng            14.1.0               h69a702a_0    conda-forge
libgfortran5              14.1.0               hc5f4f2c_0    conda-forge
libglib                   2.80.3               h8a4344b_1    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           23_linux64_openblas    conda-forge
libllvm18                 18.1.8               h8b73ec9_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libpciaccess              0.18                 hd590300_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libpq                     16.3                 ha72fbe1_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libtiff                   4.6.0                h46a8edc_4    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.16                 hd590300_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.7.0                h2c5496b_1    conda-forge
libxml2                   2.12.7               he7c6b58_4    conda-forge
libxslt                   1.1.39               h76b75d6_0    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
matplotlib                3.9.1           py312h7900ff3_2    conda-forge
matplotlib-base           3.9.1           py312h854627b_2    conda-forge
mummer                    3.23            pl5321hdbdd923_19    bioconda
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.3.0                h70512c7_5    conda-forge
mysql-libs                8.3.0                ha479ceb_5    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
numpy                     2.0.1           py312h1103770_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.3.1                h4bc722e_2    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py312h1d6d2e6_1    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pcre2                     10.44                h0f59acf_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
pillow                    10.4.0          py312h287a98d_0    conda-forge
pip                       24.2               pyhd8ed1ab_0    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyani                     0.2.12             pyhdfd78af_0    bioconda
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyside6                   6.7.2           py312hb5137db_2    conda-forge
python                    3.12.4          h194c7f8_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
qhull                     2020.2               h434a139_5    conda-forge
qt6-main                  6.7.2                hb12f9c5_4    conda-forge
readline                  8.2                  h8228510_1    conda-forge
scipy                     1.14.0          py312hc2bc53b_1    conda-forge
seaborn                   0.13.2               hd8ed1ab_2    conda-forge
seaborn-base              0.13.2             pyhd8ed1ab_2    conda-forge
setuptools                72.1.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
statsmodels               0.14.2          py312h085067d_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tornado                   6.4.1           py312h9a8786e_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
wayland                   1.23.0               h5291e77_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xcb-util                  0.4.1                hb711507_2    conda-forge
xcb-util-cursor           0.1.4                h4ab18f5_2    conda-forge
xcb-util-image            0.4.0                hb711507_2    conda-forge
xcb-util-keysyms          0.4.1                hb711507_0    conda-forge
xcb-util-renderutil       0.3.10               hb711507_0    conda-forge
xcb-util-wm               0.4.2                hb711507_0    conda-forge
xkeyboard-config          2.42                 h4ab18f5_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                hb711507_1    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.3.1                h4ab18f5_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

**Comment by widdowquinn** [comment]
Hi @despathe - thank you for your interest in `pyani`.

It looks like the `register_cmap()` function was deprecated in `matplotlib` with the update to v3.9.0 this year - see [https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.9.0.html](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.9.0.html).

This can possibly be fixed in the short term by installing an earlier version of `matplotlib` with, for example:

```bash
conda install matplotlib=3.8.1
```

Your note that "[I] had to download biopython and matplotlib (most updated versions) separately because when using the conda install pyani script, I would be getting lots of errors because biopython and matplotlib could not be downloaded as packages through pyani." is surprising. Can you please provide those errors so we can see what's going on?

L.

**Comment by widdowquinn** [comment]
I've changed the function calls that were to blame and pushed a new release (v0.2.13) - this should fix that issue. I expect the `bioconda` bot to pick it up and rebuild shortly. Please keep an eye on this page for the version number ticking over on the `-noarch` build: https://anaconda.org/bioconda/pyani and reopen this issue if the problem persists.
