### ISSUE TITLE
Error installing pyani

### ISSUE THREAD

**Issue by cutykaka** [widdowquinn/pyani#45]
Hello, guys.
I installed python Version 3.5.2 to set up pyani.
But after performing with pip3 install pyani command, I have an error in the command python setup.py .
How can I solve this problem??

**Comment by widdowquinn** [comment]
I can't really tell without seeing the error message - please could you copy/paste the message, below.

**Comment by cutykaka** [comment]
when I tried to set up Pyani, everytime has changed the error message like below script.

"Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-0hnh2qp_/scipy
Storing debug log for failure in /root/.pip/pip.log"

Why did the error message happen?
I am looking forward to hearing a helpful reply.
Thank you.

**Comment by widdowquinn** [comment]
The problem appears to be in the attempt to install SciPy, so may not be a problem with `pyani`.

What does the installation log in `/root/.pip/pip.log` tell you about the failure (this is indicated as the place to check, in the error message you got)

**Comment by widdowquinn** [comment]
This thread on StackOverflow might be helpful: [http://stackoverflow.com/questions/26575587/cant-install-scipy-through-pip](http://stackoverflow.com/questions/26575587/cant-install-scipy-through-pip)

**Comment by widdowquinn** [comment]
Issue closed because problem appears to be with `scipy` installation.
