### ISSUE TITLE
module object has no attribute run

### ISSUE THREAD

**Issue by swuyts** [widdowquinn/pyani#46]
Hi there,

I've recently installed pyani and tried to run it using 8 cores with the following command:

`average_nucleotide_identity.py -i $pin -o $pout -m ANIb --workers 8`

This leads to the following error output:

`Traceback (most recent call last):
  File "/usr/local/bin/average_nucleotide_identity.py", line 806, in <module>
    results = methods[args.method][0](infiles, org_lengths)
  File "/usr/local/bin/average_nucleotide_identity.py", line 532, in unified_anib
    logger=logger)
  File "/usr/local/lib/python3.4/dist-packages/pyani/run_multiprocessing.py", line 45, in run_dependency_graph
    cumretval += multiprocessing_run(cmdset, workers, verbose)
  File "/usr/local/lib/python3.4/dist-packages/pyani/run_multiprocessing.py", line 86, in multiprocessing_run
    for cline in cmdlines]
  File "/usr/local/lib/python3.4/dist-packages/pyani/run_multiprocessing.py", line 86, in <listcomp>
    for cline in cmdlines]
AttributeError: 'module' object has no attribute 'run'`

I've checked and module seems to be installed correctly in my ptyhon3.4. Am I doing something wrong, or do you have any advice to overcome this?

Thanks in advance,
Sander

**Comment by widdowquinn** [comment]
Hi Sander.

I'm afraid you'll need Python 3.5 or later for `pyani`, now. To distribute the third-party application jobs we're now using `subprocess.run()` which was added in Python 3.5.

* [`subprocess`](https://docs.python.org/3/library/subprocess.html)

It's the lack of `run` under `subprocess` in Python 3.4 that's causing your error message.

Cheers,

L.

**Comment by swuyts** [comment]
My apologies,

I've must have read over the fact that Python >= 3.5 is needed.

Thanks for the fast support!

**Comment by widdowquinn** [comment]
It appears not to be very clear in the documentation, which is my fault. Sorry about that.

**Comment by widdowquinn** [comment]
Also, thanks for using `pyani` - any questions or problems, please do raise another issue.
