### ISSUE TITLE
ImportError: No module named 'openpyxl'

### ISSUE THREAD

**Issue by jpearl01** [widdowquinn/pyani#47]
#### Summary:
Attempted to run the test data with the command: 
`average_nucleotide_identity.py -i test_ani_data/ -o my_test_ANIb -g --gformat png -m ANIb -l ANIb_log --write_excel`

Currently running python 3.5.0b4 (installed with pyenv) on Fedora 23

#### Description:

```
$ average_nucleotide_identity.py -i test_ani_data/ -o my_test_ANIb -g --gformat png -m ANIb -l ANIb_log --write_excel
Traceback (most recent call last):
  File "/home/jearl/.pyenv/versions/3.5.0b4/bin/average_nucleotide_identity.py", line 807, in <module>
    write(results, methods[args.method][1])
  File "/home/jearl/.pyenv/versions/3.5.0b4/bin/average_nucleotide_identity.py", line 617, in write
    index=True)
  File "/home/jearl/.pyenv/versions/3.5.0b4/lib/python3.5/site-packages/pandas/core/frame.py", line 1453, in to_excel
    excel_writer = ExcelWriter(excel_writer, engine=engine)
  File "/home/jearl/.pyenv/versions/3.5.0b4/lib/python3.5/site-packages/pandas/io/excel.py", line 771, in __init__
    if not openpyxl_compat.is_compat(major_ver=self.openpyxl_majorver):
  File "/home/jearl/.pyenv/versions/3.5.0b4/lib/python3.5/site-packages/pandas/compat/openpyxl_compat.py", line 27, in is_compat
    import openpyxl
ImportError: No module named 'openpyxl'
```

#### Reproducible Steps:
only seems to happen if I use the '--write_excel' option, otherwise program seems to run fine on the test data

**Comment by widdowquinn** [comment]
Hi,

Yes - that's a problem in Pandas, I'm afraid. There was a period when everything worked fine (and pyani wrote out Excel by default), and then the openpyxl support broke for some reason. Honestly, I forgot about it, and I've not been back to see if Pandas has caught up yet.

Would you be able to let me know which version of Pandas you have installed?

Cheers,

L.

**Comment by jpearl01** [comment]
Ah, I just have the version of Pandas which pip installs while installing pyani (although I've been interested in checking it out since everyone seems to be using/enjoying it).  Currently looks like version
0.19.1

~josh

**Comment by widdowquinn** [comment]
I guess they haven't fixed it yet, then ;) I'll take a look and see what I can do.

**Comment by widdowquinn** [comment]
Returning to this after a while. `openpyxl` and `pandas` seem to talk to each other nicely again, at least, at the following version points:

```
>>> import openpyxl
>>> openpyxl.__version__
'2.5.8'
>>> import pandas
>>> pandas.__version__
'0.23.4'
```

So I'm going to close this, for now.
