### ISSUE TITLE
Description of Heatmap Outputs

### ISSUE THREAD

**Issue by jpearl01** [widdowquinn/pyani#48]
#### Summary:
I'm familiar with ANI (and there is a very good description of it in the README), so the *_percentage_identity, *_alignment_length, and *_alignment_coverage make sense to me.

I'm not so sure about the *_hadamard or *_similarity_errors graphs.  Is there a good resource to find out more as to how to interpret these?  Or the algorithms used to generate them?

#### Operating System: Fedora 23

**Comment by widdowquinn** [comment]
Other than the source code, I'm just going to have to explain them here ;)

The *_hadamard output is the [https://en.wikipedia.org/wiki/Hadamard_product_(matrices)](Hadamard product) of identity and coverage. It's meant to provide a measure that allows you to interpret identity and coverage simultaneously - it's not provided by any other ANI package so far as I know. It'll be a new thing for the pyani paper.

The *_similarity_errors graphs come out of using MUMmer - it's a value provided in MUMmer output that essentially counts up SNPs (but doesn't identify them directly).

**Comment by jpearl01** [comment]
Aha.  That's far more straightforward than I was expecting :-) 

Looking forward to the paper!

Thanks for the clarification,

~josh
