### ISSUE TITLE
Error in TETRA calculation

### ISSUE THREAD

**Issue by ytanizaw** [widdowquinn/pyani#49]
Thank you for a wonderful tool. I've used your scripts in some of my recent works.
I got An error while conducting the TETRA calculation as below.

#### Reproducible Steps and Current Output:

```
$ python average_nucleotide_identity.py -m TETRA -i INPUTDIR -o OUTPUTDIR
Traceback (most recent call last):
  File "average_nucleotide_identity.py", line 770, in <module>
    write(results)
  File "average_nucleotide_identity.py", line 586, in write
    for dfr, filestem in results.data:
AttributeError: 'tuple' object has no attribute 'data'
```
(It works if I use the "-m ANIb" option.)

#### Proposal for amendment:
To avoid the error, I changed line 460 in the "calculate_tetra" method.
```
    return (tetra_correlations, )
```
to
```
    return tetra_correlations  # returns Pandas DataFrame object, not tuple
```

Also I needed to change the "write" method as following.
This was because other methods (ANIb or ANIm) return the results in ANIResults objects, while TETRA method does not.

```
def write(results):

    if args.method == "TETRA":
        if args.write_excel:
            results.to_excel(os.path.join(args.outdirname, "tetra_result") + '.xlsx', index=True)
        results.to_csv(os.path.join(args.outdirname, "tetra_result") + '.tab',
                   index=True, sep="\t")
    else:

        logger.info("Writing %s results to %s", args.method, args.outdirname)
        for dfr, filestem in results.data:
            logger.info("\t%s", filestem)
            if args.write_excel:
                dfr.to_excel(os.path.join(args.outdirname, filestem) + '.xlsx',
                             index=True)
            dfr.to_csv(os.path.join(args.outdirname, filestem) + '.tab',
                       index=True, sep="\t")
```
I am not sure if this is the best way.
Please let me know if you have any other good ideas.

**Comment by widdowquinn** [comment]
I can reproduce this. I'll get on it.

**Comment by widdowquinn** [comment]
Thank you for the report, and apologies again for the delay. The fix is implemented in commit https://github.com/widdowquinn/pyani/commit/e46c7f5f27e4b44219bdab6a674b63bbf65f0767 on the master branch.
