### ISSUE TITLE
Maxmatch flag not being applied when using ANIm

### ISSUE THREAD

**Issue by ntopaz** [widdowquinn/pyani#53]
#### Summary:
**Please provide a short summary (a couple of sentences).**
When using the --maxmatch flag with ANIm, the nucmer commands use -mum instead of -maxmatch. This results in some incorrect results, such as two organisms in different genuses returning .95+ ANI based on the alignment of a single, short fragment.  

#### Description:
**Describe the issue as clearly as possible.**
The maxmatch flag seems to always be defaulted to False even if specified for use. 

#### Reproducible Steps:
**Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.**

Noticed several results that did not make sense, as mentioned above. 

#### Expected Output:
**Describe what you expect the output to be. Knowing the correct behavior is also very useful.**
I manually ran nucmer with maxmatch and received a result of ~.81, which makes more sense. I also ran nucmer without maxmatch and received the .95 result based on the single short fragment alignment that corresponded to the result from pyani. 

#### pyani Version:
0.2.1
#### Python Version:
3.6 
#### Operating System:
CentOS 6.8

**Comment by widdowquinn** [comment]
Thank you for the report. I think that this bug is fixed with commit https://github.com/widdowquinn/pyani/commit/a528d630bce13341301e0e27b3898a633b9db3ec on the `master` branch - please could you check with your data and reopen the issue if it's not fixed for you.

Cheers,

L.
