### ISSUE TITLE
Is it possible to set a reference genome? pairwise one takes too long

### ISSUE THREAD

**Issue by a1204350** [widdowquinn/pyani#55]
pairwise comparison takes too long and if it is possible to set a reference genome to be compared?

**Comment by widdowquinn** [comment]
Sorry, there's no option to do that at the moment. If you're looking to obtain pairwise comparisons against a single reference with MUMmer (or BLAST), then might a `for` loop be sufficient for you?

Comparison against a single reference is something we could consider for a future enhancement, though.

**Comment by a1204350** [comment]
Thanks
