### ISSUE TITLE
What are the differences between classes.txt and labels.txt

### ISSUE THREAD

**Issue by sbridel** [widdowquinn/pyani#57]
I was wondering what are the differences between theses 2 files and how these differences and how these files works in plots construction

**Comment by widdowquinn** [comment]
* `labels.txt` defines the text that is printed to identify each genome sequence
* `classes.txt` defines the group that is used for colouring the sidebars in the heatmap/tree

**Comment by sbridel** [comment]
oh nice! 
So i can add class information like i know genomes A B D H belong to the same species.
Thanks !
