### ISSUE TITLE
Minimum version of pandas required?

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#6]
I am exploring automating the pyani tests with TravisCI.

Ideally I would run this within their Python VM, but currently I am trying the TravisCI R support on the assumption this is the easiest way to get R and thus rpy2 installed. This https://travis-ci.org/peterjc/pyani/builds/82568268 build was using the system python, and:

```
$ sudo apt-get install python-pandas
```

This installed pandas 0.7.0 which turns out to be too old:

```
$ make test
./average_nucleotide_identity.py -i tests/test_ani_data -o tests/test_ANIm_output \
	  -m ANIm --classes tests/test_ani_data/classes.tab --labels tests/test_ani_data/labels.tab -g -v
INFO: Namespace(blastall_exe='blastall', blastn_exe='blastn', classes='tests/test_ani_data/classes.tab', force=False, formatdb_exe='formatdb', fragsize=1020, gformat='pdf', gmethod='mpl', graphics=True, indirname='tests/test_ani_data', labels='tests/test_ani_data/labels.tab', logfile=None, makeblastdb_exe='makeblastdb', maxmatch=False, method='ANIm', noclobber=False, nucmer_exe='nucmer', outdirname='tests/test_ANIm_output', scheduler='multiprocessing', skip_blastn=False, skip_nucmer=False, verbose=True, write_excel=False)
INFO: Input directory: tests/test_ani_data
INFO: Creating directory tests/test_ANIm_output
INFO: Output directory: tests/test_ANIm_output
INFO: Using ANI method: ANIm
INFO: Using scheduler method: multiprocessing
INFO: Identifying FASTA files in tests/test_ani_data
INFO: Input files:
	tests/test_ani_data/NC_011916.fna
	tests/test_ani_data/NC_010338.fna
	tests/test_ani_data/NC_014100.fna
	tests/test_ani_data/NC_002696.fna
INFO: Processing input sequence lengths
INFO: Sequence lengths:
	NC_002696: 4016947
	NC_014100: 4655622
	NC_010338: 5477872
	NC_011916: 4042929
INFO: Carrying out ANIm analysis
INFO: Running ANIm
INFO: Generating NUCmer command-lines
INFO: Running jobs with multiprocessing
INFO: Command pool now running:
INFO: nucmer -mum -p tests/test_ANIm_output/NC_010338_vs_NC_002696 tests/test_ani_data/NC_010338.fna tests/test_ani_data/NC_002696.fna
INFO: nucmer -mum -p tests/test_ANIm_output/NC_011916_vs_NC_010338 tests/test_ani_data/NC_011916.fna tests/test_ani_data/NC_010338.fna
INFO: nucmer -mum -p tests/test_ANIm_output/NC_011916_vs_NC_014100 tests/test_ani_data/NC_011916.fna tests/test_ani_data/NC_014100.fna
INFO: nucmer -mum -p tests/test_ANIm_output/NC_010338_vs_NC_014100 tests/test_ani_data/NC_010338.fna tests/test_ani_data/NC_014100.fna
INFO: nucmer -mum -p tests/test_ANIm_output/NC_014100_vs_NC_002696 tests/test_ani_data/NC_014100.fna tests/test_ani_data/NC_002696.fna
INFO: nucmer -mum -p tests/test_ANIm_output/NC_011916_vs_NC_002696 tests/test_ani_data/NC_011916.fna tests/test_ani_data/NC_002696.fna
INFO: Command pool done.
INFO: Cumulative return value: 0
INFO: All multiprocessing jobs complete.
INFO: Processing NUCmer .delta files.
Traceback (most recent call last):
  File "./average_nucleotide_identity.py", line 658, in <module>
    results = methods[args.method][0](infiles, org_lengths)
  File "./average_nucleotide_identity.py", line 349, in calculate_anim
    data = anim.process_deltadir(args.outdirname, org_lengths, logger=logger)
  File "/home/travis/build/peterjc/pyani/pyani/anim.py", line 185, in process_deltadir
    alignment_lengths.loc[qname, sname] = tot_length
  File "/usr/lib/pymodules/python2.7/pandas/core/frame.py", line 1437, in __getattr__
    (type(self).__name__, name))
AttributeError: 'DataFrame' object has no attribute 'loc'
make: *** [ANIm] Error 1
```

The ``.loc`` attribute was added in pandas 0.11 http://pandas.pydata.org/pandas-docs/stable/whatsnew.html

Should the main ``README.md`` say it requires at least pandas 0.11?

**Comment by widdowquinn** [comment]
Thanks, Peter. Yes you're right - it would be helpful to indicate at least which versions of each dependency the module is known to work with.

In general, these days I'm happier to indicate known compatibilities, and earliest known working versions, than I am "should work with more recent than…" statements. As you know all too well, there's always the likelihood that a later version can deprecate a usage, or introduce a new incompatibility.

It might be useful to add reporting of each dependency version to the script logfile, and also a dependency checker. I'll get on to that shortly (or will accept a PR ;) )

**Comment by peterjc** [comment]
I was looking at a ``requirements.txt`` file for use with ``pip install -r requirements.txt`` which can include minimum versions of packages...

**Comment by widdowquinn** [comment]
That's a good idea. From a quick read of [https://pip.readthedocs.org/en/stable/reference/pip_install/#requirements-file-format](https://pip.readthedocs.org/en/stable/reference/pip_install/#requirements-file-format) it looks like we can specify exact and ranged version numbers, which is what I'd be looking for.

**Comment by widdowquinn** [comment]
I've added a `requirements.txt` file that reflects the state in my `virtualenv` for `pyani`. This may help the automated build (or, at least, will allow `pip install -r requirements.txt` to create a known working environment).
