### ISSUE TITLE
error in running average_nucleotide_identity

### ISSUE THREAD

**Issue by kengcher** [widdowquinn/pyani#62]
Hi

I tried running pyani on the test dataset but ran into this error:

> average_nucleotide_identity.py -i tests/test_ani_data/ -o tests/test_ANIm_output -m ANIm -g
WARNING: At least one NUCmer comparison failed. ANIm may fail.
/home/dnanexus/py350/lib/python3.5/site-packages/scipy/cluster/hierarchy.py:667: RuntimeWarning: invalid value encountered in greater_equal
  if np.all(y >= 0) and np.allclose(y, y.T):
Traceback (most recent call last):
  File "/home/dnanexus/py350/bin/average_nucleotide_identity.py", line 791, in <module>
    draw(methods[args.method][1], gfmt, args.rerender)
  File "/home/dnanexus/py350/bin/average_nucleotide_identity.py", line 627, in draw
    params=params)
  File "/home/dnanexus/py350/lib/python3.5/site-packages/pyani/pyani_graphics.py", line 322, in heatmap_mpl
    orientation='col')
  File "/home/dnanexus/py350/lib/python3.5/site-packages/pyani/pyani_graphics.py", line 200, in add_mpl_dendrogram
    dend = sch.dendrogram(sch.linkage(dists, method='complete'),
  File "/home/dnanexus/py350/lib/python3.5/site-packages/scipy/cluster/hierarchy.py", line 676, in linkage
    raise ValueError("The condensed distance matrix must contain only finite values.")
ValueError: The condensed distance matrix must contain only finite values.

Pls advise.

Thank you.

**Comment by widdowquinn** [comment]
Hi,

Can you please complete the information in the issues template (which version you are running, where you're running the script from, etc.) - that would help diagnose what's going on.

L.

**Comment by widdowquinn** [comment]
Can you also please confirm that you have MUMmer installed and are able to run it from the command line.

It would help greatly if you could also please generate a logfile and attach it to your issue report.

L.

**Comment by widdowquinn** [comment]
I've just tried the latest version, and cannot reproduce your error. The log and other information - especially confirming that you have MUMmer installed - would help very much.

**Comment by kengcher** [comment]
Hi Leighton

Indeed, that was my mistake, and it works now after installing MUMmer.

Thank you for pointing that out.
