### ISSUE TITLE
Request adding --version switch to the command line tools

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#65]
#### Summary:

It does not seem to be possible to determine the version of the pyani command line scripts from running the scripts themselves.

#### Description:

The convention ``--version`` is not supported (``-v`` is taken for verbose mode), and the help text does include the version either.

#### Reproducible Steps:

```
$ average_nucleotide_identity.py --version
usage: average_nucleotide_identity.py [-h] [-o OUTDIRNAME] [-i INDIRNAME] [-v]
                                      [-f] [-s FRAGSIZE] [-l LOGFILE]
                                      [--skip_nucmer] [--skip_blastn]
                                      [--noclobber] [--nocompress] [-g]
                                      [--gformat GFORMAT] [--gmethod GMETHOD]
                                      [--labels LABELS] [--classes CLASSES]
                                      [-m METHOD] [--scheduler SCHEDULER]
                                      [--workers WORKERS]
                                      [--SGEgroupsize SGEGROUPSIZE]
                                      [--maxmatch] [--nucmer_exe NUCMER_EXE]
                                      [--blastn_exe BLASTN_EXE]
                                      [--makeblastdb_exe MAKEBLASTDB_EXE]
                                      [--blastall_exe BLASTALL_EXE]
                                      [--formatdb_exe FORMATDB_EXE]
                                      [--write_excel] [--rerender]
                                      [--subsample SUBSAMPLE] [--seed SEED]
                                      [--jobprefix JOBPREFIX]
average_nucleotide_identity.py: error: unrecognized arguments: --version
```

#### Current Output:

See above.

#### Expected Output:

I propose something like this, and would be willing to implement it:

```
$ average_nucleotide_identity.py --version
pyani 0.2.3
```

Or if you prefer, a longer string giving the script version number as well as the pyani version number?

#### pyani Version:

```
$ python3 -c "import pyani; print(pyani.__version__)"
0.2.3
```

#### Python Version:

Should not be relevant, but:

```
$ python3 --version
Python 3.5.0
```

#### Operating System:

Should not be relevant, but 64-bit Linux CentOS.

**Comment by widdowquinn** [comment]
Yes to the `--version` option, and to it returning the overall `pyani` version.

I'm not yet convinced that individual version numbers for each script in the package is the way to go. It requires an attention to individual versioning that would be easy to forget about (though I accept that a codified set of guidelines for pushing changes might help avoid that). As scripts are added to the package, the problem increases, and they can be out of sync with the overall package version.

To the extent that each individual point release of `pyani` implies a *specific* version of all scripts in the package, I would say that the point release covers the use case, and I think it would satisfy my needs.

The `.devN` versions semantically imply that the codebase is in a state of flux and may change (though if I'm misinterpreting, correction is welcomed!).

FWIW, the version number is reported in the log file, which I hope all users would be generating by choice ;)

**Comment by peterjc** [comment]
I agree that (for now) using the pyani overall version number would suffice.

**Comment by widdowquinn** [comment]
This gets dealt with in https://github.com/widdowquinn/pyani/pull/66
