### ISSUE TITLE
Include citation information in README

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#67]
This could be a link to the ``CITATION`` file.

**Comment by widdowquinn** [comment]
I'll also add a `--citation` flag to both scripts, and a `.citation()` function to the module (which will be called when the `--citation` flag is specified) that takes whatever's in `CITATION` and prints to `STDOUT`.

**Comment by raymondkiu** [comment]
How should I cite this pipeline - is there any paper published yet to describe this tool?

**Comment by widdowquinn** [comment]
Hi Raymond - there's a paper that can be cited, here: [https://github.com/widdowquinn/pyani/blob/master/CITATIONS](https://github.com/widdowquinn/pyani/blob/master/CITATIONS).

**Comment by raymondkiu** [comment]
Thank you!
