### ISSUE TITLE
Check assembly_status.txt for failed downloads?

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#70]
#### Summary:

Sometimes FTP downloads attempted by ``genbank_get_genomes_by_taxon.py`` fail for a reason, e.g.

ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/336/365/GCF_000336365.1_ASM33636v1/GCF_000336365.1_ASM33636v1_genomic.fna.gz

ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/186/485/GCA_000186485.1_ASM18648v1/GCA_000186485.1_ASM18648v1_genomic.fna.gz

Here there are ``assembly_status.txt`` files on the FTP site which explain why, both contain one line of plain text:

> status=replaced

ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/176/835/GCA_000176835.1_ASM17683v1/assembly_status.txt

ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/186/485/GCA_000186485.1_ASM18648v1/assembly_status.txt

#### Expected Output:

When an FTP download fails, it is worth examining the ``assembly_status.txt`` file automatically?

#### pyani Version:

0.2.3.dev

#### Python Version:

3.5

#### Operating System:

Linux

**Comment by widdowquinn** [comment]
Why not - I'm inclined to think it's a very thorough thing to do (beyond the scope of the tool, but very nice for the user - who otherwise would have to do it for themselves).
