### ISSUE TITLE
Downloading md5checksums.txt from NCBI FTP site?

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#75]
#### Summary:

The NCBI FTP site the ``genbank_get_genomes_by_taxon.py`` script downloads sequences from (in FASTA or GenBank format) provides MD5 checksums, which we could fetch, record, and verify.

(This *may* also be useful with long terms goals on the roadmap https://github.com/widdowquinn/pyani/wiki/roadmap for pyani, although the NCBI gives hashes of the gzipped files which may not be as helpful)

#### Description:

e.g. ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/564/475/GCA_001564475.1_12082_3_81/ provides multiple files including the FASTA genome, ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/564/475/GCA_001564475.1_12082_3_81/GCA_001564475.1_12082_3_81_genomic.fna.gz

In particular it offers ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/564/475/GCA_001564475.1_12082_3_81/md5checksums.txt which contains:

```
2a2c33ee1ce27114e28ae1d34f07e1ab  ./GCA_001564475.1_12082_3_81_assembly_report.txt
154272f854dece3959b9321a21ec107b  ./GCA_001564475.1_12082_3_81_assembly_stats.txt
6fe8468575a1884c63565a96128fd7d6  ./GCA_001564475.1_12082_3_81_assembly_structure/Primary_Assembly/component_localID2acc
20e600cc92c0ff47a7ef3babd5b337c3  ./GCA_001564475.1_12082_3_81_assembly_structure/Primary_Assembly/scaffold_localID2acc
f1796bfc28ace76fa5ee3acc22a7d082  ./GCA_001564475.1_12082_3_81_assembly_structure/Primary_Assembly/unplaced_scaffolds/AGP/unplaced.scaf.agp.gz
69768f693e3faeff9d1db36be46bf04e  ./GCA_001564475.1_12082_3_81_assembly_structure/Primary_Assembly/unplaced_scaffolds/FASTA/unplaced.scaf.fna.gz
76a9e6c5153d64fb1240a878d0324c6f  ./GCA_001564475.1_12082_3_81_cds_from_genomic.fna.gz
cd7202a6459f3786fb391a7346d002d7  ./GCA_001564475.1_12082_3_81_feature_table.txt.gz
69768f693e3faeff9d1db36be46bf04e  ./GCA_001564475.1_12082_3_81_genomic.fna.gz
1a9d9720c54cf391cabc9b7690d60be2  ./GCA_001564475.1_12082_3_81_genomic.gbff.gz
22390a0d63a06f516bbf813b78a61dab  ./GCA_001564475.1_12082_3_81_genomic.gff.gz
303e1e045d97b149f569859f04375f7d  ./GCA_001564475.1_12082_3_81_protein.faa.gz
c1961cb0f31a03efc369bb46486cfe2f  ./GCA_001564475.1_12082_3_81_protein.gpff.gz
da00d9bcfd6fe6fdcb419727695eee65  ./GCA_001564475.1_12082_3_81_rna_from_genomic.fna.gz
95b8e7e2668bcee46919eb43127e996e  ./GCA_001564475.1_12082_3_81_wgsmaster.gbff.gz
900e1650239d0b71b2c671c98518907f  ./annotation_hashes.txt
```

Sadly the static filename ``md5checksums.txt`` would clash, so it would have to be renamed, perhaps to ``GCA_001564475.1_12082_3_81.mf5`` - or we could extract the checksums for the files of interest (those the script downloads) and create for example  ``GCA_001564475.1_12082_3_81_genomic.fna.gz.md5`` containing:

```
69768f693e3faeff9d1db36be46bf04e  ./GCA_001564475.1_12082_3_81_genomic.fna.gz
```

or:

```
69768f693e3faeff9d1db36be46bf04e  GCA_001564475.1_12082_3_81_genomic.fna.gz
```

This would match the naming convention used elsewhere on the NCBI FTP site and more widely of ``filename.ext.md5`` containing the checksum for ``filename.ext``, using the ``md5sum`` command line tool's format.

The download script could then verify the download file has the expected checksum:

```
$ md5sum -c GCA_001564475.1_12082_3_81_genomic.fna.gz.md5 
GCA_001564475.1_12082_3_81_genomic.fna.gz: OK
```

**Comment by widdowquinn** [comment]
Good idea.

I prefer the idea of extracting the checksum only for the files we download.

**Comment by widdowquinn** [comment]
Checksums are now used with the `pyani download` subcommand in the `classify` branch (and coming to v0.3.0 shortly, I hope). This will supersede the `genbank_get_genomes_by_taxon.py` script, which will be deprecated for a period (I'm not sure how long, yet). The checksums are validated on download.

When downloading NCBI files and modifying their headers for use with Kraken, a new checksum is calculated with the modified header.

The checksum for the file used in ANI analysis (modified header or not) is used to uniquely identify an input, in the new database backend.
