### ISSUE TITLE
Defaults for labels and classes matching fetch script output

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#77]
#### Summary:

The ``genbank_get_genomes_by_taxon.py`` script puts ``labels.txt`` and ``classes.txt`` in the output folder with the FASTA files.

If the ``--labels`` and ``--classes`` arguments to ``average_nucleotide_identity.py`` are not given they could default to these filesnames in the ``--indir`` folder.

**Comment by widdowquinn** [comment]
Yes. Good point.

**Comment by widdowquinn** [comment]
I think this is now done on the `classify` branch.
