### ISSUE TITLE
ValueError: The condensed distance matrix must contain only finite values.

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#80]
#### Summary:

Dendrogram step failed with an exception, perhaps due to an infinity from a divide by zero?

#### Description:

Stack trace below.

#### Reproducible Steps:

I'm not yet sure if this is reproducible, recently I have been re-running ``average_nucleotide_identity.py`` on the same input folder (after first unzipping the nucmer tar-ball), while tweaking the input to add a species of interest.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

```
$ average_nucleotide_identity.py -i interesting_serratia -o interesting_serratia_cmp -l interesting_serratia_cmp.log -g --labels interesting_serratia/labels.txt --classes interesting_serratia/classes.txt --scheduler SGE --jobprefix "Serratia" --noclobber --force --skip_nucmer
WARNING: NOCLOBBER: not actually deleting directory
WARNING: Skipping NUCmer run (as instructed)!
WARNING: Total alignment length reported in interesting_serratia_cmp/nucmer_output/GCF_000988045.1_GFC_24_genomic_vs_GCA_900016775.1_STsPazieg1.0_genomic.delta is zero!
...
WARNING: Total alignment length reported in interesting_serratia_cmp/nucmer_output/GCF_001514455.1_ASM151445v1_genomic_vs_GCA_900016775.1_STsPazieg1.0_genomic.delta is zero!/mnt/shared/users/pc40583/lib/python3.5/site-packages/scipy/cluster/hierarchy.py:667: RuntimeWarning: invalid value encountered in greater_equal
  if np.all(y >= 0) and np.allclose(y, y.T):
Traceback (most recent call last):
  File "/home/pc40583/bin/average_nucleotide_identity.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyani==0.2.3.dev0', 'average_nucleotide_identity.py')
  File "/home/pc40583/lib/python3.5/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/pc40583/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/mnt/shared/users/pc40583/lib/python3.5/site-packages/pyani-0.2.3.dev0-py3.5.egg/EGG-INFO/scripts/average_nucleotide_identity.py", line 811, in <module>
  File "/mnt/shared/users/pc40583/lib/python3.5/site-packages/pyani-0.2.3.dev0-py3.5.egg/EGG-INFO/scripts/average_nucleotide_identity.py", line 640, in draw
  File "/mnt/shared/users/pc40583/lib/python3.5/site-packages/pyani-0.2.3.dev0-py3.5.egg/pyani/pyani_graphics.py", line 322, in heatmap_mpl
  File "/mnt/shared/users/pc40583/lib/python3.5/site-packages/pyani-0.2.3.dev0-py3.5.egg/pyani/pyani_graphics.py", line 200, in add_mpl_dendrogram
  File "/mnt/shared/users/pc40583/lib/python3.5/site-packages/scipy/cluster/hierarchy.py", line 676, in linkage
    raise ValueError("The condensed distance matrix must contain only finite values.")
ValueError: The condensed distance matrix must contain only finite values.
```

#### Expected Output:
I would expect the failure to be caught and a nicer error message to be shown.

Once we understand where the non-finite value comes from, perhaps NaN might work instead...

#### pyani Version:

```
$ python3 -c "import pyani; print(pyani.__version__)"
0.2.3.dev
```

Specifically running from my recently rebased resume branch, see #76 

Also relevant,

```
$ python3 -c "import scipy; print(scipy.__version__)"
0.19.0
```

#### Python Version:

```
$ python3 --version
Python 3.6.0
```

#### Operating System:

Linux, 64-bit.

**Comment by peterjc** [comment]
It was reproducible on the same dataset - it could be a corrupted nucmer output, but I suspect an outlier genome was to blame. I removed it and am re-running the script.

**Comment by widdowquinn** [comment]
I should handle it more gracefully, but that's my usual advice. You'll not get an informative biological result even if it is included ;)

**Comment by peterjc** [comment]
I now suspect this was due to re-running a job in place where I did not have a full set of delta files but used ``--skip_nucmer``, meaning some of the results would be default values?

**Comment by peterjc** [comment]
Something like this may help with a graceful error...

```
$ git diff
diff --git a/pyani/anim.py b/pyani/anim.py
index 3f0f85c..d50d643 100644
--- a/pyani/anim.py
+++ b/pyani/anim.py
@@ -204,4 +204,9 @@ def process_deltadir(delta_dir, org_lengths, logger=None):
         results.add_sim_errors(qname, sname, tot_sim_error)
         results.add_pid(qname, sname, perc_id)
         results.add_coverage(qname, sname, query_cover, sbjct_cover)
+    # Check for missing data by using fact that alignment_lengths
+    # default to NaN (other values default to zero or one):
+    if results.alignment_lengths.isnull().values.any():
+        # Run with --skip_nucmer and missing (some) delta files?
+        logger.warning("Missing some alignment lengths!")
     return results
```

**Comment by peterjc** [comment]
Confirmed - while tinkering with auto-reuse of the nucmer files, I was accidentally running a job with ``--skip_nucmer`` and a partial set of delta files.

As discussed, this is outside the current design scope, and my use-case would be superseded with the database ideas in the https://github.com/widdowquinn/pyani/wiki/roadmap roadmap.

Never the less, while triggering the error was my fault, a less a cryptic failure would be ideal. I'll look at making a pull request to improve the error message.

**Comment by widdowquinn** [comment]
As your case is… unsual… ;) and I hope we'll be accounting for it in the new interface, I'm inclined to leave this as a motivation for people to move on when we release that ;)

**Comment by tilmanbeck** [comment]
I encountered the same problem when trying to cluster text documents. I don't think that this is an usual case as the one above.
It happens when I execute the following code:

```python
import numpy as np
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import AgglomerativeClustering
def main():
        dataset = fetch_20newsgroups(data_home='./resources/scikit_data', subset='all', shuffle=True, 
								random_state=42, remove=('headers', 'footers', 'quotes') )
        data_samples = dataset.data
	targets = dataset.target
	categories = dataset.target_names
	k = np.unique(targets).shape[0]
	tf_vectorizer = TfidfVectorizer(max_features=50000, max_df=1.0, min_df=1)
	tfs = tf_vectorizer.fit_transform(data_samples)
	agg = AgglomerativeClustering(linkage="complete", n_clusters=k, affinity="cosine")
	agg.fit(tfs.toarray())
	return dataset

if __name__ == '__main__':
	main()
```
and produces following error msg:

```shell
File "/data13/tbeck/masterthesis/venv/lib/python3.5/site-packages/sklearn/cluster/hierarchical.py", line 750, in fit
    **kwargs)
  File "/data13/tbeck/masterthesis/venv/lib/python3.5/site-packages/sklearn/externals/joblib/memory.py", line 362, in __call__
    return self.func(*args, **kwargs)
  File "/data13/tbeck/masterthesis/venv/lib/python3.5/site-packages/sklearn/cluster/hierarchical.py", line 527, in _complete_linkage
    return linkage_tree(*args, **kwargs)
  File "/data13/tbeck/masterthesis/venv/lib/python3.5/site-packages/sklearn/cluster/hierarchical.py", line 417, in linkage_tree
    out = hierarchy.linkage(X, method=linkage, metric=affinity)
  File "/data13/tbeck/masterthesis/venv/lib/python3.5/site-packages/scipy/cluster/hierarchy.py", line 713, in linkage
    raise ValueError("The condensed distance matrix must contain only "
ValueError: The condensed distance matrix must contain only finite values.
```
**Python Version**:
```
$ python -V
Python 3.5.2
```

**Scipy Version**:
```
$ python -c "import scipy; print(scipy.__version__)"
1.0.0
$ python -c "import sklearn; print(sklearn.__version__)"
0.19.0
```
**OS**:
Linux Ubuntu, 64 Bit

Actually, I don't really understand when this case happens that matrix parameter contains infinite values. From the running time I assume that it happens quite late in the clustering process.

**Comment by peterjc** [comment]
@tilmanbeck are you using the software ``pyani`` here? If not, then probably you should look at the ``scipy`` or ``sklearn`` issue trackers.

**Comment by tilmanbeck** [comment]
Hey @peterjc ,
sorry, I simply stumbled in here via google without rechecking!
I'll switch to their issue trackers.

**Comment by selahlynch** [comment]
I've discovered (with help) that this error shows up when an input dataset has columns that contain no information, in other words, they contain only one unique value, such as a column that is all 0's.

**Comment by widdowquinn** [comment]
Thanks, Selah.

In the next version/release (currently on the `development` branch) we are moving to an SQLite backend to store results, and we should be able to catch/report this sort of thing earlier, and maybe prevent this error from being shown.

Cheers,

L.
