### ISSUE TITLE
Labels and Class flags

### ISSUE THREAD

**Issue by ksoca** [widdowquinn/pyani#82]
Hello, 
 
I had a question on the maps generated from pyani. Is it possible to specify user-defined labes? If it is, what format would be required in order to do so?
 
-Ksoca

pyani Version: pyani-0.2.1
Python Version: 3.5.0b4
Operating System: Centos 6 Linux

**Comment by widdowquinn** [comment]
HI Ksoca,

The labels can be defined as in the example file at https://github.com/widdowquinn/pyani/blob/master/tests/test_ani_data/labels.tab

It's a plain text, tab-separated format file with two columns. The first column is the filename stem for the genome sequence, and the second column is the label you want to see in the heatmap for that genome.

You can use the `--labels` argument with `average_nucleotide_identity.py`to specify a label file.

Cheers,

L.
