### ISSUE TITLE
Order of genomes 

### ISSUE THREAD

**Issue by CynthiaChibani** [widdowquinn/pyani#84]
#### Summary:
Please provide a short summary (a couple of sentences).

#### Description:
Describe the issue as clearly as possible.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

**Comment by CynthiaChibani** [comment]
Hello,
I am wondering if there is a way to control the order of the genomes in the output?

**Comment by widdowquinn** [comment]
If you mean in the sense of "provide an ordered list of genomes as input, and have the heatmap render with either the columns or rows (or both) respecting that order", then not within pyani.

However, the `.tab` file output can be imported into `R` or `Python` with `pandas`, and you can then have complete control of rendering output, including row/column order.
