### ISSUE TITLE
Make Heatmap/dendogram figure just from ANI matrix table?

### ISSUE THREAD

**Issue by TonyMannion** [widdowquinn/pyani#85]
I have an ANI matrix table that I calculated using a different program, but I like the heatmap/dendogram output generated by pyani.  Is it possible to use my ANI results to create a heatmap/dendogram figure using pyani code? 

Thank you!

Tony

**Comment by widdowquinn** [comment]
Hi Tony,

If it's named appropriately (with corresponding class and label files as appropriate), you could drop it into a results directory and use the `--rerender` options.

If you're comfortable in Python you could import `pyani` as a package in Python, load your matrix as a `pandas` dataframe, and use the `pyani_graphics` module functions, e.g. call `heatmap_seaborn()`.

Cheers,

L.

**Comment by TonyMannion** [comment]
I ran the below command with known data and got expected results.

average_nucleotide_identity.py -v -i Contigs -o Genomes_ANIb_output/ -g
--gmethod seaborn --gformat png,pdf,eps,svg --write_excel -m ANIb

However, I got the error below when I then changed one value in the
ANIb_percentage_identity.tab output and ran the command with --rerender

average_nucleotide_identity.py -v -i Contigs -o Genomes_ANIb_output/ -g
--gmethod seaborn --gformat png,pdf,eps,svg --write_excel -m ANIb --rerender
INFO: pyani version: 0.2.3
INFO: Namespace(blastall_exe='blastall', blastn_exe='blastn', classes=None,
force=False, formatdb_exe='formatdb', fragsize=1020,
gformat='png,pdf,eps,svg', gmethod='seaborn', graphics=True,
indirname='Contigs', jobprefix='ANI', labels=None, logfile=None,
makeblastdb_exe='makeblastdb', maxmatch=False, method='ANIb',
noclobber=False, nocompress=False, nucmer_exe='nucmer',
outdirname='Genomes_ANIb_output/', rerender=True,
scheduler='multiprocessing', seed=None, sgegroupsize=10000,
skip_blastn=False, skip_nucmer=False, subsample=None, verbose=True,
workers=None, write_excel=True)
INFO: command-line: /usr/local/bin/average_nucleotide_identity.py -v -i
Contigs -o Genomes_ANIb_output/ -g --gmethod seaborn --gformat
png,pdf,eps,svg --write_excel -m ANIb --rerender
INFO: Input directory: Contigs
INFO: Removing directory Genomes_ANIb_output/ and everything below it
WARNING: NOCLOBBER: not actually deleting directory
INFO: Creating directory Genomes_ANIb_output/
INFO: NOCLOBBER+FORCE: not creating directory
INFO: Output directory: Genomes_ANIb_output/
INFO: Using ANI method: ANIb
WARNING: --rerender option used
WARNING: Producing graphics with no new recalculations
INFO: Rendering output graphics
INFO: Formats requested: png,pdf,eps,svg
INFO: Graphics format: png
INFO: Graphics method: seaborn
Traceback (most recent call last):
  File "/usr/local/bin/average_nucleotide_identity.py", line 791, in
<module>
    draw(methods[args.method][1], gfmt, args.rerender)
  File "/usr/local/bin/average_nucleotide_identity.py", line 620, in draw
    logger.info("Writing heatmap to %s", outfilename)
AttributeError: 'bool' object has no attribute 'info'

Any ideas how to fix this?

Thank you!
Tony

**Comment by widdowquinn** [comment]
Would you be able to provide the `.tab` file before and after the change you made?

**Comment by TonyMannion** [comment]
Before and after files are attached.  Note I only changed the
ANIb_percentage_identity.tab file and not the other .tab outputs such for
alignment coverage.  The before and after files had the same name:
ANIb_percentage_identity.tab

On Mon, Jun 5, 2017 at 2:30 PM, Leighton Pritchard <notifications@github.com

**Comment by widdowquinn** [comment]
I can't see any files on the thread. Do you see them?

**Comment by widdowquinn** [comment]
I think you sent your last comment by email. This strips out attachments. Would you be able to drag-and-drop the files into this thread on GitHub, please?

**Comment by TonyMannion** [comment]
I did attach them in my email response, sorry about that!  Now attached in the zip folder.

[Mannion_GitHub.zip](https://github.com/widdowquinn/pyani/files/1053160/Mannion_GitHub.zip)

**Comment by widdowquinn** [comment]
Hi Tony - `pyani` requires all the `.tab` files for a rerender - could you please attach a .zip with all the relevant output?

**Comment by widdowquinn** [comment]
For info, I've attempted to reproduce this with the test data provided in the repository.

First, I generated specific output data:

```
average_nucleotide_identity.py -i tests/test_ani_data/ -o tests/issue_85 -m ANIm -g --gmethod seaborn -v -l issue_85.log
```

Then copied this to a new location:

```
cp -R tests/issue_85 tests/issue_85_after
```

I modified the `ANIm_percentage_identity.tab` data in a similar way to your modification, replacing 1.0 values on the diagonal with 0.5 (this makes no biological sense, BTW - it implies a sequence has only 50% identity with itself), and then ran the rerender:

```
average_nucleotide_identity.py -i tests/test_ani_data/ -o tests/issue_85_after -m ANIm -g --gmethod seaborn -v -l issue_85_rerender.log --rerender
```

This gave the same error you see:

```
INFO: Graphics method: seaborn
Traceback (most recent call last):
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/bin/average_nucleotide_identity.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyani==0.2.3', 'average_nucleotide_identity.py')
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/pyani-0.2.3-py3.6.egg/EGG-INFO/scripts/average_nucleotide_identity.py", line 791, in <module>
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/pyani-0.2.3-py3.6.egg/EGG-INFO/scripts/average_nucleotide_identity.py", line 620, in draw
AttributeError: 'bool' object has no attribute 'info'
```

But so does the unmodified output:

```
average_nucleotide_identity.py -i tests/test_ani_data/ -o tests/issue_85 -m ANIm -g --gmethod seaborn -v -l issue_85_rerender.log --rerender
```

So this is an issue with the rerender code in general. I'll get onto it.

**Comment by widdowquinn** [comment]
OK - I've found the issue, and I'll push the change in a few minutes.

Before:

![anim_percentage_identity](https://cloud.githubusercontent.com/assets/63981/26820357/7b9a28bc-4a9a-11e7-98cd-cb2530530c31.png)

After:

![anim_percentage_identity](https://cloud.githubusercontent.com/assets/63981/26820367/833b5302-4a9a-11e7-8c62-dfae1dd658e6.png)

**Comment by widdowquinn** [comment]
That's the fix implemented with commit 99bb596 - please could you clone the latest version, install, and check it works for you?

**Comment by TonyMannion** [comment]
Works perfectly now!  Thank you so much! 

Best,
Tony

**Comment by widdowquinn** [comment]
No worries - please raise another issue if you get any problems.

L.
