### ISSUE TITLE
matplotlib collections.py FutureWarning

### ISSUE THREAD

**Issue by widdowquinn** [widdowquinn/pyani#9]
```
$ ./average_nucleotide_identity.py -i tests/test_ani_data/  -o tests/test_ANIm_output/ -g --gformat png \
    --classes tests/test_ani_data/classes.tab     --labels tests/test_ani_data/labels.tab --force
/Users/lpritc/Virtualenvs/pyani/lib/python2.7/site-packages/matplotlib/collections.py:590:
FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform
 elementwise comparison
  if self._edgecolors == str('face'):
```

**Comment by jfinnimore** [comment]
Hi, I'm doing a joinplot in Seaborn and received the same warning. Here's my code:
sns.jointplot('CPST','OXY',tech_rets,kind='scatter',color='seagreen')

Any idea how to get rid of the warning?

**Comment by rlabbe** [comment]
I think you are seeing this bug:
https://github.com/matplotlib/matplotlib/issues/5209

It has been fixed, and will be released "soon".

**Comment by widdowquinn** [comment]
Thanks, rlabbe - I'll keep my eye on that thread.
